// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class CaixaEventosConfiguration : IEntityTypeConfiguration<CaixaEventos>
    {
        public void Configure(EntityTypeBuilder<CaixaEventos> entity)
        {
            entity.HasKey(e => new { e.NumTerminal, e.DtEvento, e.CodEvento });

            entity.ToTable("CAIXA_EVENTOS");

            entity.HasIndex(e => e.Deletado, "CAIXA_EVENTOS_IDX1");

            entity.HasIndex(e => e.RefCaixaDtAbertura, "CAIXA_EVENTOS_IDX2");

            entity.HasIndex(e => e.NumDocServer, "CAIXA_EVENTOS_IDX3");

            entity.HasIndex(e => new { e.CodEvento, e.NumTerminal, e.DtEvento }, "PK_CAIXA_EVENTOS")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.DtEvento).HasColumnName("DT_EVENTO");

            entity.Property(e => e.CodEvento).HasColumnName("COD_EVENTO");

            entity.Property(e => e.AcrescimoUnitQtd).HasColumnName("ACRESCIMO_UNIT_QTD");

            entity.Property(e => e.AcrescimoUnitVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRESCIMO_UNIT_VAL");

            entity.Property(e => e.AcrescimosVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRESCIMOS_VAL");

            entity.Property(e => e.Cancelado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CANCELADO");

            entity.Property(e => e.CdCliente).HasColumnName("CD_CLIENTE");

            entity.Property(e => e.CrId).HasColumnName("CR_ID");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DescontarCaixa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESCONTAR_CAIXA");

            entity.Property(e => e.DescontosUnitQtd).HasColumnName("DESCONTOS_UNIT_QTD");

            entity.Property(e => e.DescontosUnitVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOS_UNIT_VAL");

            entity.Property(e => e.DescontosVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOS_VAL");

            entity.Property(e => e.DevolucaoId).HasColumnName("DEVOLUCAO_ID");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Especie)
                .HasMaxLength(200)
                .HasColumnName("ESPECIE");

            entity.Property(e => e.Evento)
                .HasMaxLength(20)
                .HasColumnName("EVENTO");

            entity.Property(e => e.Historico)
                .HasMaxLength(200)
                .HasColumnName("HISTORICO");

            entity.Property(e => e.ItemMaiorValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ITEM_MAIOR_VALOR");

            entity.Property(e => e.ItemMenorValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ITEM_MENOR_VALOR");

            entity.Property(e => e.Login)
                .HasMaxLength(80)
                .HasColumnName("LOGIN");

            entity.Property(e => e.NumDocLocal).HasColumnName("NUM_DOC_LOCAL");

            entity.Property(e => e.NumDocOrdem).HasColumnName("NUM_DOC_ORDEM");

            entity.Property(e => e.NumDocServer).HasColumnName("NUM_DOC_SERVER");

            entity.Property(e => e.Obs)
                .HasMaxLength(800)
                .HasColumnName("OBS");

            entity.Property(e => e.Origem)
                .IsRequired()
                .HasColumnType("CHAR(3) ")
                .HasColumnName("ORIGEM");

            entity.Property(e => e.PecaMaiorValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PECA_MAIOR_VALOR");

            entity.Property(e => e.PecaMenorValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PECA_MENOR_VALOR");

            entity.Property(e => e.QtdeItens).HasColumnName("QTDE_ITENS");

            entity.Property(e => e.QtdePecas).HasColumnName("QTDE_PECAS");

            entity.Property(e => e.RefCaixaDtAbertura).HasColumnName("REF_CAIXA_DT_ABERTURA");

            entity.Property(e => e.RefCartaoCred)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_CARTAO_CRED");

            entity.Property(e => e.RefCartaoDeb)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_CARTAO_DEB");

            entity.Property(e => e.RefCartaoParc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_CARTAO_PARC");

            entity.Property(e => e.RefChequeAto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_CHEQUE_ATO");

            entity.Property(e => e.RefChequePre)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_CHEQUE_PRE");

            entity.Property(e => e.RefCredcli)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_CREDCLI");

            entity.Property(e => e.RefCrediario)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_CREDIARIO");

            entity.Property(e => e.RefDinheiro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_DINHEIRO");

            entity.Property(e => e.RefMoedasocial)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_MOEDASOCIAL");

            entity.Property(e => e.RefOutros)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_OUTROS");

            entity.Property(e => e.RefTickets)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REF_TICKETS");

            entity.Property(e => e.RegEcf)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("REG_ECF");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Valor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CaixaEventos> entity);
    }
}
