// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class CaixaConfiguration : IEntityTypeConfiguration<Caixa>
    {
        public void Configure(EntityTypeBuilder<Caixa> entity)
        {
            entity.HasKey(e => new { e.DtFechamento, e.DtAbertura, e.NumTerminal });

            entity.ToTable("CAIXA");

            entity.HasComment("Esta tabela contém apenas os Caixas Fechados.\r\nOs valores dos Caixas Abertos são obtidos através da soma dos Eventos.");

            entity.HasIndex(e => new { e.NumTerminal, e.DtFechamento, e.DtAbertura }, "PK_CAIXA")
                .IsUnique();

            entity.Property(e => e.DtFechamento).HasColumnName("DT_FECHAMENTO");

            entity.Property(e => e.DtAbertura).HasColumnName("DT_ABERTURA");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.AcrescimoUnitQtd).HasColumnName("ACRESCIMO_UNIT_QTD");

            entity.Property(e => e.AcrescimoUnitVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRESCIMO_UNIT_VAL");

            entity.Property(e => e.AcrescimosQtd).HasColumnName("ACRESCIMOS_QTD");

            entity.Property(e => e.AcrescimosVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRESCIMOS_VAL");

            entity.Property(e => e.CancelItensQtd).HasColumnName("CANCEL_ITENS_QTD");

            entity.Property(e => e.CancelItensVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CANCEL_ITENS_VAL");

            entity.Property(e => e.CancelPedidosQtd).HasColumnName("CANCEL_PEDIDOS_QTD");

            entity.Property(e => e.CancelPedidosVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CANCEL_PEDIDOS_VAL");

            entity.Property(e => e.CancelVendasQtd).HasColumnName("CANCEL_VENDAS_QTD");

            entity.Property(e => e.CancelVendasVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CANCEL_VENDAS_VAL");

            entity.Property(e => e.ConfCartao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CONF_CARTAO");

            entity.Property(e => e.ConfCheque)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CONF_CHEQUE");

            entity.Property(e => e.ConfCredcli)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CONF_CREDCLI");

            entity.Property(e => e.ConfCrediarios)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CONF_CREDIARIOS");

            entity.Property(e => e.ConfDinheiro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CONF_DINHEIRO");

            entity.Property(e => e.ConfQtdeCedula10).HasColumnName("CONF_QTDE_CEDULA_10");

            entity.Property(e => e.ConfQtdeCedula100).HasColumnName("CONF_QTDE_CEDULA_100");

            entity.Property(e => e.ConfQtdeCedula2).HasColumnName("CONF_QTDE_CEDULA_2");

            entity.Property(e => e.ConfQtdeCedula20).HasColumnName("CONF_QTDE_CEDULA_20");

            entity.Property(e => e.ConfQtdeCedula5).HasColumnName("CONF_QTDE_CEDULA_5");

            entity.Property(e => e.ConfQtdeCedula50).HasColumnName("CONF_QTDE_CEDULA_50");

            entity.Property(e => e.ConfQtdeMoeda01).HasColumnName("CONF_QTDE_MOEDA_01");

            entity.Property(e => e.ConfQtdeMoeda1).HasColumnName("CONF_QTDE_MOEDA_1");

            entity.Property(e => e.ConfQtdeMoeda10).HasColumnName("CONF_QTDE_MOEDA_10");

            entity.Property(e => e.ConfQtdeMoeda25).HasColumnName("CONF_QTDE_MOEDA_25");

            entity.Property(e => e.ConfQtdeMoeda5).HasColumnName("CONF_QTDE_MOEDA_5");

            entity.Property(e => e.ConfQtdeMoeda50).HasColumnName("CONF_QTDE_MOEDA_50");

            entity.Property(e => e.ConfTickets)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CONF_TICKETS");

            entity.Property(e => e.ContasrecebQtd).HasColumnName("CONTASRECEB_QTD");

            entity.Property(e => e.ContasrecebVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CONTASRECEB_VAL");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DescontosQtd).HasColumnName("DESCONTOS_QTD");

            entity.Property(e => e.DescontosUnitQtd).HasColumnName("DESCONTOS_UNIT_QTD");

            entity.Property(e => e.DescontosUnitVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOS_UNIT_VAL");

            entity.Property(e => e.DescontosVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOS_VAL");

            entity.Property(e => e.DevolucoesQtd).HasColumnName("DEVOLUCOES_QTD");

            entity.Property(e => e.DevolucoesVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DEVOLUCOES_VAL");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.EstItensMaiorvlr)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_ITENS_MAIORVLR");

            entity.Property(e => e.EstItensMenorvlr)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_ITENS_MENORVLR");

            entity.Property(e => e.EstItensQtde)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_ITENS_QTDE");

            entity.Property(e => e.EstPecasMaiorvlr)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_PECAS_MAIORVLR");

            entity.Property(e => e.EstPecasMenorvlr)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_PECAS_MENORVLR");

            entity.Property(e => e.EstPecasQtde)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_PECAS_QTDE");

            entity.Property(e => e.EstVendasMaiorvlr)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_VENDAS_MAIORVLR");

            entity.Property(e => e.EstVendasMenorvlr)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_VENDAS_MENORVLR");

            entity.Property(e => e.EstVendasQtde)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("EST_VENDAS_QTDE");

            entity.Property(e => e.Fundotroco)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FUNDOTROCO");

            entity.Property(e => e.GavCartaoCred)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_CARTAO_CRED");

            entity.Property(e => e.GavCartaoDeb)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_CARTAO_DEB");

            entity.Property(e => e.GavCartaoParc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_CARTAO_PARC");

            entity.Property(e => e.GavChequeAto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_CHEQUE_ATO");

            entity.Property(e => e.GavChequePre)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_CHEQUE_PRE");

            entity.Property(e => e.GavCredcli)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_CREDCLI");

            entity.Property(e => e.GavCrediarios)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_CREDIARIOS");

            entity.Property(e => e.GavDinheiro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_DINHEIRO");

            entity.Property(e => e.GavMoedasocial)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_MOEDASOCIAL");

            entity.Property(e => e.GavOutros)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_OUTROS");

            entity.Property(e => e.GavTickets)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("GAV_TICKETS");

            entity.Property(e => e.LoginFechamento)
                .HasMaxLength(80)
                .HasColumnName("LOGIN_FECHAMENTO");

            entity.Property(e => e.Obs)
                .HasMaxLength(200)
                .HasColumnName("OBS");

            entity.Property(e => e.ObsFechamento)
                .HasMaxLength(200)
                .HasColumnName("OBS_FECHAMENTO");

            entity.Property(e => e.OrigemAbertura)
                .IsRequired()
                .HasColumnType("CHAR(3) ")
                .HasColumnName("ORIGEM_ABERTURA");

            entity.Property(e => e.OrigemFechamento)
                .HasColumnType("CHAR(3) ")
                .HasColumnName("ORIGEM_FECHAMENTO");

            entity.Property(e => e.QtdeConsultas).HasColumnName("QTDE_CONSULTAS");

            entity.Property(e => e.Reducaoz)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("REDUCAOZ");

            entity.Property(e => e.SangriaQtd).HasColumnName("SANGRIA_QTD");

            entity.Property(e => e.SangriaVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("SANGRIA_VAL");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.SuprimentoQtd).HasColumnName("SUPRIMENTO_QTD");

            entity.Property(e => e.SuprimentoVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("SUPRIMENTO_VAL");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.VenCartaoCred)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_CARTAO_CRED");

            entity.Property(e => e.VenCartaoDeb)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_CARTAO_DEB");

            entity.Property(e => e.VenCartaoParc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_CARTAO_PARC");

            entity.Property(e => e.VenChequeAto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_CHEQUE_ATO");

            entity.Property(e => e.VenChequePre)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_CHEQUE_PRE");

            entity.Property(e => e.VenCredcli)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_CREDCLI");

            entity.Property(e => e.VenCrediarios)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_CREDIARIOS");

            entity.Property(e => e.VenDinheiro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_DINHEIRO");

            entity.Property(e => e.VenMoedasocial)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_MOEDASOCIAL");

            entity.Property(e => e.VenOutros)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_OUTROS");

            entity.Property(e => e.VenTickets)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VEN_TICKETS");

            entity.Property(e => e.VendasVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VENDAS_VAL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Caixa> entity);
    }
}
