// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class CaixaSituacaoConfiguration : IEntityTypeConfiguration<CaixaSituacao>
    {
        public void Configure(EntityTypeBuilder<CaixaSituacao> entity)
        {
            entity.HasKey(e => e.NumTerminal);

            entity.ToTable("CAIXA_SITUACAO");

            entity.HasIndex(e => e.NumTerminal, "PK_CAIXA_SITUACAO")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.DtAbertura).HasColumnName("DT_ABERTURA");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtUltFechamento).HasColumnName("DT_ULT_FECHAMENTO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Situacao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SITUACAO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CaixaSituacao> entity);
    }
}
