// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class CestNcmConfiguration : IEntityTypeConfiguration<CestNcm>
    {
        public void Configure(EntityTypeBuilder<CestNcm> entity)
        {
            entity.ToTable("CEST_NCM");

            entity.HasIndex(e => e.Id, "PK_CEST_NCM")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Cest)
                .HasMaxLength(7)
                .HasColumnName("CEST");

            entity.Property(e => e.Ncm)
                .HasMaxLength(10)
                .HasColumnName("NCM");

            entity.Property(e => e.Obs)
                .HasMaxLength(1000)
                .HasColumnName("OBS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CestNcm> entity);
    }
}
