// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClientesConfiguration : IEntityTypeConfiguration<Clientes>
    {
        public void Configure(EntityTypeBuilder<Clientes> entity)
        {
            entity.HasKey(e => e.CdCliente);

            entity.ToTable("CLIENTES");

            entity.HasIndex(e => e.NmCliente, "CLIENTES_IDX1");

            entity.HasIndex(e => e.Apelido, "CLIENTES_IDX2");

            entity.HasIndex(e => e.CdVendedor, "CLIENTES_IDX3");

            entity.HasIndex(e => e.CpfCnpj, "CLIENTES_IDX4");

            entity.HasIndex(e => e.Inativo, "IDX_CLIINATIVO");

            entity.HasIndex(e => e.CdPraca, "IDX_PRACAS");

            entity.HasIndex(e => e.CdCliente, "PK_CLIENTES")
                .IsUnique();

            entity.Property(e => e.CdCliente).HasColumnName("CD_CLIENTE");

            entity.Property(e => e.AcresDescEspecial)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ACRES_DESC_ESPECIAL");

            entity.Property(e => e.Apelido)
                .HasMaxLength(60)
                .HasColumnName("APELIDO");

            entity.Property(e => e.AtrasoJurosaodia)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ATRASO_JUROSAODIA");

            entity.Property(e => e.AtrasoMulta)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ATRASO_MULTA");

            entity.Property(e => e.BloqAutoImune)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BLOQ_AUTO_IMUNE");

            entity.Property(e => e.BloqAutomatico)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BLOQ_AUTOMATICO");

            entity.Property(e => e.CdClienteCategoria).HasColumnName("CD_CLIENTE_CATEGORIA");

            entity.Property(e => e.CdClienteGrupos).HasColumnName("CD_CLIENTE_GRUPOS");

            entity.Property(e => e.CdClienteSeller).HasColumnName("CD_CLIENTE_SELLER");

            entity.Property(e => e.CdPraca).HasColumnName("CD_PRACA");

            entity.Property(e => e.CdTipoPreco).HasColumnName("CD_TIPO_PRECO");

            entity.Property(e => e.CdVendedor).HasColumnName("CD_VENDEDOR");

            entity.Property(e => e.Celular)
                .HasMaxLength(70)
                .HasColumnName("CELULAR");

            entity.Property(e => e.CondicoesPersonalizadas)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CONDICOES_PERSONALIZADAS");

            entity.Property(e => e.Condicoespagamento)
                .HasMaxLength(100)
                .HasColumnName("CONDICOESPAGAMENTO");

            entity.Property(e => e.Conjuge)
                .HasMaxLength(40)
                .HasColumnName("CONJUGE");

            entity.Property(e => e.Contato)
                .HasMaxLength(80)
                .HasColumnName("CONTATO");

            entity.Property(e => e.CpfCnpj)
                .HasMaxLength(18)
                .HasColumnName("CPF_CNPJ");

            entity.Property(e => e.Crt).HasColumnName("CRT");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtCasamento)
                .HasColumnType("DATE")
                .HasColumnName("DT_CASAMENTO");

            entity.Property(e => e.DtExpPalm).HasColumnName("DT_EXP_PALM");

            entity.Property(e => e.DtNascimento)
                .HasColumnType("DATE")
                .HasColumnName("DT_NASCIMENTO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincMarketplace).HasColumnName("DT_SINC_MARKETPLACE");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.Email)
                .HasMaxLength(1000)
                .HasColumnName("EMAIL");

            entity.Property(e => e.EndBairro)
                .HasMaxLength(35)
                .HasColumnName("END_BAIRRO");

            entity.Property(e => e.EndCdMunicipio).HasColumnName("END_CD_MUNICIPIO");

            entity.Property(e => e.EndCdPais).HasColumnName("END_CD_PAIS");

            entity.Property(e => e.EndCep)
                .HasMaxLength(9)
                .HasColumnName("END_CEP");

            entity.Property(e => e.EndComplemento)
                .HasMaxLength(60)
                .HasColumnName("END_COMPLEMENTO");

            entity.Property(e => e.EndLogradouro)
                .HasMaxLength(60)
                .HasColumnName("END_LOGRADOURO");

            entity.Property(e => e.EndNmMunicipio)
                .HasMaxLength(35)
                .HasColumnName("END_NM_MUNICIPIO");

            entity.Property(e => e.EndNumero)
                .HasMaxLength(20)
                .HasColumnName("END_NUMERO");

            entity.Property(e => e.EndReferencia)
                .HasMaxLength(200)
                .HasColumnName("END_REFERENCIA");

            entity.Property(e => e.EndUf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("END_UF");

            entity.Property(e => e.EnviarEmailAniversario)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ENVIAR_EMAIL_ANIVERSARIO");

            entity.Property(e => e.Estcivil)
                .HasMaxLength(10)
                .HasColumnName("ESTCIVIL");

            entity.Property(e => e.Exportar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR");

            entity.Property(e => e.Fax)
                .HasMaxLength(70)
                .HasColumnName("FAX");

            entity.Property(e => e.Foto).HasColumnName("FOTO");

            entity.Property(e => e.IdSellerWeb)
                .HasMaxLength(20)
                .HasColumnName("ID_SELLER_WEB"); 

            entity.Property(e => e.IeCpf)
                .HasMaxLength(15)
                .HasColumnName("IE_CPF");

            entity.Property(e => e.ImpSaldodivida)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_SALDODIVIDA");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.InscMunicipal)
                .HasMaxLength(15)
                .HasColumnName("INSC_MUNICIPAL");

            entity.Property(e => e.Lembrete)
                .HasMaxLength(150)
                .HasColumnName("LEMBRETE");

            entity.Property(e => e.Limitecredito)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("LIMITECREDITO");

            entity.Property(e => e.NmCliente)
                .HasMaxLength(80)
                .HasColumnName("NM_CLIENTE");

            entity.Property(e => e.NmMae)
                .HasMaxLength(80)
                .HasColumnName("NM_MAE");

            entity.Property(e => e.NmPai)
                .HasMaxLength(80)
                .HasColumnName("NM_PAI");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.ObsCobranca).HasColumnName("OBS_COBRANCA");

            entity.Property(e => e.Pessoa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PESSOA")
                .HasDefaultValueSql("'0'");

            entity.Property(e => e.Prazopagamento).HasColumnName("PRAZOPAGAMENTO");

            entity.Property(e => e.ProfEmail)
                .HasMaxLength(100)
                .HasColumnName("PROF_EMAIL");

            entity.Property(e => e.ProfEmpresa)
                .HasMaxLength(80)
                .HasColumnName("PROF_EMPRESA");

            entity.Property(e => e.ProfEndereco).HasColumnName("PROF_ENDERECO");

            entity.Property(e => e.ProfFax)
                .HasMaxLength(70)
                .HasColumnName("PROF_FAX");

            entity.Property(e => e.ProfProfissao)
                .HasMaxLength(30)
                .HasColumnName("PROF_PROFISSAO");

            entity.Property(e => e.ProfSite)
                .HasMaxLength(50)
                .HasColumnName("PROF_SITE");

            entity.Property(e => e.ProfTelefone)
                .HasMaxLength(70)
                .HasColumnName("PROF_TELEFONE");

            entity.Property(e => e.Refbanco).HasColumnName("REFBANCO");

            entity.Property(e => e.Referencia1)
                .HasMaxLength(80)
                .HasColumnName("REFERENCIA1");

            entity.Property(e => e.Referencia2)
                .HasMaxLength(80)
                .HasColumnName("REFERENCIA2");

            entity.Property(e => e.Referencia3)
                .HasMaxLength(80)
                .HasColumnName("REFERENCIA3");

            entity.Property(e => e.RgIe)
                .HasMaxLength(15)
                .HasColumnName("RG_IE");

            entity.Property(e => e.Selecionado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SELECIONADO");

            entity.Property(e => e.Sexo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SEXO");

            entity.Property(e => e.Sincronizado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZADO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Spc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SPC");

            entity.Property(e => e.SpcData)
                .HasColumnType("DATE")
                .HasColumnName("SPC_DATA");

            entity.Property(e => e.SpcNumero)
                .HasMaxLength(15)
                .HasColumnName("SPC_NUMERO");

            entity.Property(e => e.Suframa)
                .HasMaxLength(10)
                .HasColumnName("SUFRAMA");

            entity.Property(e => e.TelRef1)
                .HasMaxLength(70)
                .HasColumnName("TEL_REF1");

            entity.Property(e => e.TelRef2)
                .HasMaxLength(70)
                .HasColumnName("TEL_REF2");

            entity.Property(e => e.TelRef3)
                .HasMaxLength(70)
                .HasColumnName("TEL_REF3");

            entity.Property(e => e.Telefone)
                .HasMaxLength(70)
                .HasColumnName("TELEFONE");

            entity.Property(e => e.TipoCliente)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_CLIENTE");

            entity.Property(e => e.TipoContribIcms)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_CONTRIB_ICMS");

            entity.Property(e => e.TrayId).HasColumnName("TRAY_ID");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Website)
                .HasMaxLength(50)
                .HasColumnName("WEBSITE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Clientes> entity);
    }
}
