// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteComputadorSistemaModuConfiguration : IEntityTypeConfiguration<ClienteComputadorSistemaModu>
    {
        public void Configure(EntityTypeBuilder<ClienteComputadorSistemaModu> entity)
        {
            entity.HasKey(e => new { e.ComputadorId, e.SistemaId, e.ModuloId })
                .HasName("COMPUTADOR_SISTEMA_MODULO_ID");

            entity.ToTable("CLIENTE_COMPUTADOR_SISTEMA_MODU");

            entity.HasIndex(e => new { e.ModuloId, e.ComputadorId, e.SistemaId }, "COMPUTADOR_SISTEMA_MODULO_ID")
                .IsUnique();

            entity.Property(e => e.ComputadorId).HasColumnName("COMPUTADOR_ID");

            entity.Property(e => e.SistemaId).HasColumnName("SISTEMA_ID");

            entity.Property(e => e.ModuloId).HasColumnName("MODULO_ID");

            entity.Property(e => e.DataSincronia).HasColumnName("DATA_SINCRONIA");

            entity.Property(e => e.UltimoAcesso).HasColumnName("ULTIMO_ACESSO");

            entity.Property(e => e.Versao)
                .HasMaxLength(10)
                .HasColumnName("VERSAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteComputadorSistemaModu> entity);
    }
}
