// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClientesRefConfiguration : IEntityTypeConfiguration<ClientesRef>
    {
        public void Configure(EntityTypeBuilder<ClientesRef> entity)
        {
            entity.HasKey(e => e.CdCliente);

            entity.ToTable("CLIENTES_REF");

            entity.HasIndex(e => e.CdCliente, "PK_CLIENTES_REF")
                .IsUnique();

            entity.Property(e => e.CdCliente).HasColumnName("CD_CLIENTE");

            entity.Property(e => e.Bloqueado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BLOQUEADO");

            entity.Property(e => e.Bloqueiomanual)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BLOQUEIOMANUAL");

            entity.Property(e => e.Creditoaberto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CREDITOABERTO");

            entity.Property(e => e.Dividaavencer)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DIVIDAAVENCER");

            entity.Property(e => e.Dividasemjuros)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DIVIDASEMJUROS");

            entity.Property(e => e.Dividavencida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DIVIDAVENCIDA");

            entity.Property(e => e.DtBloqueado).HasColumnName("DT_BLOQUEADO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtUltimacompra).HasColumnName("DT_ULTIMACOMPRA");

            entity.Property(e => e.DtUltimoservico).HasColumnName("DT_ULTIMOSERVICO");

            entity.Property(e => e.Juros)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("JUROS");

            entity.Property(e => e.Maioratraso).HasColumnName("MAIORATRASO");

            entity.Property(e => e.Pontuacaoatual).HasColumnName("PONTUACAOATUAL");

            entity.Property(e => e.Pontuacaototal).HasColumnName("PONTUACAOTOTAL");

            entity.Property(e => e.ProgFidelidadePontos).HasColumnName("PROG_FIDELIDADE_PONTOS");

            entity.Property(e => e.Saldodadivida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("SALDODADIVIDA");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClientesRef> entity);
    }
}
