// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteHistoricoConfiguration : IEntityTypeConfiguration<ClienteHistorico>
    {
        public void Configure(EntityTypeBuilder<ClienteHistorico> entity)
        {
            entity.HasKey(e => new { e.Id, e.CdCliente, e.Datahora });

            entity.ToTable("CLIENTE_HISTORICO");

            entity.HasIndex(e => new { e.Id, e.Datahora, e.CdCliente }, "PK_CLIENTE_HISTORICO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.CdCliente).HasColumnName("CD_CLIENTE");

            entity.Property(e => e.Datahora).HasColumnName("DATAHORA");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Historico)
                .HasMaxLength(150)
                .HasColumnName("HISTORICO");

            entity.Property(e => e.Login)
                .HasMaxLength(80)
                .HasColumnName("LOGIN");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteHistorico> entity);
    }
}
