// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteGruposConfiguration : IEntityTypeConfiguration<ClienteGrupos>
    {
        public void Configure(EntityTypeBuilder<ClienteGrupos> entity)
        {
            entity.HasKey(e => e.CdClienteGrupos);

            entity.ToTable("CLIENTE_GRUPOS");

            entity.HasIndex(e => e.CdClienteGrupos, "PK_CLIENTE_GRUPOS")
                .IsUnique();

            entity.Property(e => e.CdClienteGrupos).HasColumnName("CD_CLIENTE_GRUPOS");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.NmClienteGrupos)
                .HasMaxLength(40)
                .HasColumnName("NM_CLIENTE_GRUPOS");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteGrupos> entity);
    }
}
