// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteComputadorDiscoConfiguration : IEntityTypeConfiguration<ClienteComputadorDisco>
    {
        public void Configure(EntityTypeBuilder<ClienteComputadorDisco> entity)
        {
            entity.ToTable("CLIENTE_COMPUTADOR_DISCO");

            entity.HasIndex(e => e.Id, "PK_CLIENTE_COMPUTADOR_DISCO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.ComputadorId).HasColumnName("COMPUTADOR_ID");

            entity.Property(e => e.DataApuracao).HasColumnName("DATA_APURACAO");

            entity.Property(e => e.DataSincronia).HasColumnName("DATA_SINCRONIA");

            entity.Property(e => e.Disco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DISCO");

            entity.Property(e => e.EspacoDisponivel).HasColumnName("ESPACO_DISPONIVEL");

            entity.Property(e => e.EspacoTotal).HasColumnName("ESPACO_TOTAL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteComputadorDisco> entity);
    }
}
