// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteContabancariaConfiguration : IEntityTypeConfiguration<ClienteContabancaria>
    {
        public void Configure(EntityTypeBuilder<ClienteContabancaria> entity)
        {
            entity.HasKey(e => e.CdClienteContabancaria);

            entity.ToTable("CLIENTE_CONTABANCARIA");

            entity.HasIndex(e => new { e.Agencia, e.NumBanco, e.NumConta }, "CLIENTE_CONTABANCARIA_IDX1");

            entity.HasIndex(e => e.CdCliente, "CLIENTE_CONTABANCARIA_IDX2");

            entity.HasIndex(e => e.CdClienteContabancaria, "PK_CLIENTE_CONTABANCARIA")
                .IsUnique();

            entity.Property(e => e.CdClienteContabancaria).HasColumnName("CD_CLIENTE_CONTABANCARIA");

            entity.Property(e => e.Agencia)
                .HasMaxLength(8)
                .HasColumnName("AGENCIA");

            entity.Property(e => e.CdCliente).HasColumnName("CD_CLIENTE");

            entity.Property(e => e.CpfCnpj)
                .HasMaxLength(18)
                .HasColumnName("CPF_CNPJ");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.NmTitular)
                .HasMaxLength(80)
                .HasColumnName("NM_TITULAR");

            entity.Property(e => e.NumBanco)
                .HasColumnType("CHAR(3) ")
                .HasColumnName("NUM_BANCO");

            entity.Property(e => e.NumConta)
                .HasMaxLength(10)
                .HasColumnName("NUM_CONTA");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteContabancaria> entity);
    }
}
