// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteComputadorConfiguration : IEntityTypeConfiguration<ClienteComputador>
    {
        public void Configure(EntityTypeBuilder<ClienteComputador> entity)
        {
            entity.HasKey(e => new { e.Id, e.DataApuracao })
                .HasName("CLIENTE_COMPUTADOR_ID");

            entity.ToTable("CLIENTE_COMPUTADOR");

            entity.HasIndex(e => new { e.Id, e.DataApuracao }, "CLIENTE_COMPUTADOR_ID")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.DataApuracao).HasColumnName("DATA_APURACAO");

            entity.Property(e => e.AntivirusNome)
                .HasMaxLength(200)
                .HasColumnName("ANTIVIRUS_NOME");

            entity.Property(e => e.DataSincronia).HasColumnName("DATA_SINCRONIA");

            entity.Property(e => e.FirebirdVersao)
                .HasMaxLength(50)
                .HasColumnName("FIREBIRD_VERSAO");

            entity.Property(e => e.Ip)
                .HasMaxLength(15)
                .HasColumnName("IP");

            entity.Property(e => e.NomeFisico)
                .HasMaxLength(100)
                .HasColumnName("NOME_FISICO");

            entity.Property(e => e.NomeFocus)
                .HasMaxLength(200)
                .HasColumnName("NOME_FOCUS");

            entity.Property(e => e.WindowsVersao)
                .HasMaxLength(200)
                .HasColumnName("WINDOWS_VERSAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteComputador> entity);
    }
}
