// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteCategoriasFormpagConfiguration : IEntityTypeConfiguration<ClienteCategoriasFormpag>
    {
        public void Configure(EntityTypeBuilder<ClienteCategoriasFormpag> entity)
        {
            entity.HasKey(e => new { e.CdClienteCategoria, e.CdFormapagamento });

            entity.ToTable("CLIENTE_CATEGORIAS_FORMPAG");

            entity.HasIndex(e => new { e.CdClienteCategoria, e.CdFormapagamento }, "PK_CLIENTE_CATEGORIAS_FORMPAG")
                .IsUnique();

            entity.Property(e => e.CdClienteCategoria).HasColumnName("CD_CLIENTE_CATEGORIA");

            entity.Property(e => e.CdFormapagamento).HasColumnName("CD_FORMAPAGAMENTO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.FaixaFinal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FAIXA_FINAL");

            entity.Property(e => e.FaixaInicial)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FAIXA_INICIAL");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteCategoriasFormpag> entity);
    }
}
