// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ClienteUsuarioConfiguration : IEntityTypeConfiguration<ClienteUsuario>
    {
        public void Configure(EntityTypeBuilder<ClienteUsuario> entity)
        {
            entity.HasKey(e => new { e.ClienteId, e.Id })
                .HasName("PK_CLIENTE_USUARIO_ID");

            entity.ToTable("CLIENTE_USUARIO");

            entity.HasIndex(e => new { e.Id, e.ClienteId }, "PK_CLIENTE_USUARIO_ID")
                .IsUnique();

            entity.Property(e => e.ClienteId).HasColumnName("CLIENTE_ID");

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Ativo)
                .HasMaxLength(1)
                .HasColumnName("ATIVO");

            entity.Property(e => e.DataSincronia).HasColumnName("DATA_SINCRONIA");

            entity.Property(e => e.Email)
                .HasMaxLength(300)
                .HasColumnName("EMAIL");

            entity.Property(e => e.Login)
                .HasMaxLength(200)
                .HasColumnName("LOGIN");

            entity.Property(e => e.Nome)
                .HasMaxLength(300)
                .HasColumnName("NOME");

            entity.Property(e => e.UltimoAcesso).HasColumnName("ULTIMO_ACESSO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteUsuario> entity);
    }
}
