// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ConfigSpedConfiguration : IEntityTypeConfiguration<ConfigSped>
    {
        public void Configure(EntityTypeBuilder<ConfigSped> entity)
        {
            entity.HasKey(e => e.IdCdEmpresa);

            entity.ToTable("CONFIG_SPED");

            entity.HasIndex(e => e.IdCdEmpresa, "PK_CONFIG_SPED")
                .IsUnique();

            entity.Property(e => e.IdCdEmpresa).HasColumnName("ID_CD_EMPRESA");

            entity.Property(e => e.CodLayout)
                .HasMaxLength(5)
                .HasColumnName("COD_LAYOUT");

            entity.Property(e => e.CstCofins)
                .HasMaxLength(2)
                .HasColumnName("CST_COFINS");

            entity.Property(e => e.CstIpi)
                .HasMaxLength(2)
                .HasColumnName("CST_IPI");

            entity.Property(e => e.CstPis)
                .HasMaxLength(2)
                .HasColumnName("CST_PIS");

            entity.Property(e => e.PerfilSped).HasColumnName("PERFIL_SPED");

            entity.Property(e => e.TipoAtividade).HasColumnName("TIPO_ATIVIDADE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConfigSped> entity);
    }
}
