// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ConfigSincronizacaoConfiguration : IEntityTypeConfiguration<ConfigSincronizacao>
    {
        public void Configure(EntityTypeBuilder<ConfigSincronizacao> entity)
        {
            entity.HasNoKey();

            entity.ToTable("CONFIG_SINCRONIZACAO");

            entity.Property(e => e.Ativado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ATIVADO");

            entity.Property(e => e.Caminho)
                .HasMaxLength(1000)
                .HasColumnName("CAMINHO");

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Ip)
                .HasMaxLength(20)
                .HasColumnName("IP");

            entity.Property(e => e.Porta)
                .HasMaxLength(10)
                .HasColumnName("PORTA");

            entity.Property(e => e.Ultimasinccliente).HasColumnName("ULTIMASINCCLIENTE");

            entity.Property(e => e.Ultimasincclientecategoria).HasColumnName("ULTIMASINCCLIENTECATEGORIA");

            entity.Property(e => e.Ultimasincfaixadesconto).HasColumnName("ULTIMASINCFAIXADESCONTO");

            entity.Property(e => e.Ultimasincformaspagamento).HasColumnName("ULTIMASINCFORMASPAGAMENTO");

            entity.Property(e => e.Ultimasincfornecedor).HasColumnName("ULTIMASINCFORNECEDOR");

            entity.Property(e => e.Ultimasincusuarios).HasColumnName("ULTIMASINCUSUARIOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConfigSincronizacao> entity);
    }
}
