// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ConfimpdocConfiguration : IEntityTypeConfiguration<Confimpdoc>
    {
        public void Configure(EntityTypeBuilder<Confimpdoc> entity)
        {
            entity.HasKey(e => new { e.Doc, e.Papel });

            entity.ToTable("CONFIMPDOC");

            entity.HasIndex(e => new { e.Doc, e.Papel }, "PK_CONFIMPDOC")
                .IsUnique();

            entity.Property(e => e.Doc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DOC");

            entity.Property(e => e.Papel)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PAPEL");

            entity.Property(e => e.BobCabecalho).HasColumnName("BOB_CABECALHO");

            entity.Property(e => e.BobCompletaitensEsp)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BOB_COMPLETAITENS_ESP");

            entity.Property(e => e.BobFormato)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BOB_FORMATO");

            entity.Property(e => e.BobItens)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BOB_ITENS");

            entity.Property(e => e.BobNaocortadescr)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BOB_NAOCORTADESCR");

            entity.Property(e => e.BobOmitircodigo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BOB_OMITIRCODIGO");

            entity.Property(e => e.BobPulalinhaitem)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BOB_PULALINHAITEM");

            entity.Property(e => e.BobQuantmaxitens).HasColumnName("BOB_QUANTMAXITENS");

            entity.Property(e => e.ComprovReceb)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("COMPROV_RECEB");

            entity.Property(e => e.Descricaoabreviada)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESCRICAOABREVIADA");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.ImpCabecalho)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_CABECALHO");

            entity.Property(e => e.ImpCarneNumvias)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_CARNE_NUMVIAS");

            entity.Property(e => e.ImpCliente)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_CLIENTE");

            entity.Property(e => e.ImpCodbarrasnumpedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_CODBARRASNUMPEDIDO");

            entity.Property(e => e.ImpConcatenardesc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_CONCATENARDESC");

            entity.Property(e => e.ImpContasAbertas)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_CONTAS_ABERTAS");

            entity.Property(e => e.ImpDataemissao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_DATAEMISSAO");

            entity.Property(e => e.ImpExibeEstoqueLocalizacao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_EXIBE_ESTOQUE_LOCALIZACAO");

            entity.Property(e => e.ImpExibircodbarras)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_EXIBIRCODBARRAS");

            entity.Property(e => e.ImpFormaspagamento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_FORMASPAGAMENTO");

            entity.Property(e => e.ImpIndiceAtivo)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_INDICE_ATIVO");

            entity.Property(e => e.ImpIndiceFinalizarvenda)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_INDICE_FINALIZARVENDA");

            entity.Property(e => e.ImpItemCancelado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_ITEM_CANCELADO");

            entity.Property(e => e.ImpJuntarpedidos)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_JUNTARPEDIDOS");

            entity.Property(e => e.ImpJuros)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_JUROS");

            entity.Property(e => e.ImpLogotipo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_LOGOTIPO");

            entity.Property(e => e.ImpMatricial)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_MATRICIAL");

            entity.Property(e => e.ImpMensagemfinal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_MENSAGEMFINAL");

            entity.Property(e => e.ImpNmFantasia)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_NM_FANTASIA");

            entity.Property(e => e.ImpNumDocVenda)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_NUM_DOC_VENDA");

            entity.Property(e => e.ImpNumserie)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_NUMSERIE");

            entity.Property(e => e.ImpObs)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_OBS");

            entity.Property(e => e.ImpOrientacaoLocalizao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_ORIENTACAO_LOCALIZAO");

            entity.Property(e => e.ImpPesototal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_PESOTOTAL");

            entity.Property(e => e.ImpQtdeItens)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_QTDE_ITENS");

            entity.Property(e => e.ImpQtdeTotProd)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_QTDE_TOT_PROD");

            entity.Property(e => e.ImpReciboRecebimentos)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_RECIBO_RECEBIMENTOS");

            entity.Property(e => e.ImpSaldodivida)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_SALDODIVIDA");

            entity.Property(e => e.ImpSeqdiario)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_SEQDIARIO");

            entity.Property(e => e.ImpTipopreco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_TIPOPRECO");

            entity.Property(e => e.ImpValeCrediario)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_VALE_CREDIARIO");

            entity.Property(e => e.ImpVencimentos)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_VENCIMENTOS");

            entity.Property(e => e.ImpVencimentosCrediario)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_VENCIMENTOS_CREDIARIO");

            entity.Property(e => e.ImpVendedor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_VENDEDOR");

            entity.Property(e => e.Mensagemfinal).HasColumnName("MENSAGEMFINAL");

            entity.Property(e => e.Numvias).HasColumnName("NUMVIAS");

            entity.Property(e => e.Ordenadopor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ORDENADOPOR");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TipoDocNumVias)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_DOC_NUM_VIAS");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Viacaracteres)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("VIACARACTERES");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Confimpdoc> entity);
    }
}
