// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ConfigPedidoConfiguration : IEntityTypeConfiguration<ConfigPedido>
    {
        public void Configure(EntityTypeBuilder<ConfigPedido> entity)
        {
            entity.ToTable("CONFIG_PEDIDO");

            entity.HasIndex(e => e.Id, "PK_CONFIG_PEDIDO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.AcaoAltSubtotal).HasColumnName("ACAO_ALT_SUBTOTAL");

            entity.Property(e => e.AltCampoDesconto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALT_CAMPO_DESCONTO");

            entity.Property(e => e.AltCampoDescricao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALT_CAMPO_DESCRICAO");

            entity.Property(e => e.AltCampoPreco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALT_CAMPO_PRECO");

            entity.Property(e => e.AltCampoSubtotal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALT_CAMPO_SUBTOTAL");

            entity.Property(e => e.BloqItemSemEstoque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BLOQ_ITEM_SEM_ESTOQUE");

            entity.Property(e => e.CalculaSt)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CALCULA_ST");

            entity.Property(e => e.Categoriapadrao).HasColumnName("CATEGORIAPADRAO");

            entity.Property(e => e.ControlaEngradados)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CONTROLA_ENGRADADOS");

            entity.Property(e => e.CorDestaqueSt)
                .HasMaxLength(10)
                .HasColumnName("COR_DESTAQUE_ST");

            entity.Property(e => e.DefinirPesoAoInserir)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DEFINIR_PESO_AO_INSERIR");

            entity.Property(e => e.DesbloquearPedidoEmAberto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESBLOQUEAR_PEDIDO_EM_ABERTO");

            entity.Property(e => e.DescMaxDoc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESC_MAX_DOC");

            entity.Property(e => e.DescMaxItem)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESC_MAX_ITEM");

            entity.Property(e => e.DescmaxConsdescunit)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESCMAX_CONSDESCUNIT");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.EngradadoTipoSaida)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ENGRADADO_TIPO_SAIDA");

            entity.Property(e => e.ExibeLembrete)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBE_LEMBRETE");

            entity.Property(e => e.Exibmargemlucro)
                .HasMaxLength(20)
                .HasColumnName("EXIBMARGEMLUCRO");

            entity.Property(e => e.GerarProducao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("GERAR_PRODUCAO");

            entity.Property(e => e.GerarProducaoAuto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("GERAR_PRODUCAO_AUTO");

            entity.Property(e => e.IgnorarAsteristicoQtd)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IGNORAR_ASTERISTICO_QTD");

            entity.Property(e => e.IgnorarZero)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IGNORAR_ZERO");

            entity.Property(e => e.ImpCestNcm)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_CEST_NCM");

            entity.Property(e => e.IncluirDespesa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INCLUIR_DESPESA");

            entity.Property(e => e.IncluirFrete)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INCLUIR_FRETE");

            entity.Property(e => e.Incluirfretenascontas)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INCLUIRFRETENASCONTAS");

            entity.Property(e => e.Indicardimensoesitens)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INDICARDIMENSOESITENS");

            entity.Property(e => e.ItemDataExpirada)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ITEM_DATA_EXPIRADA");

            entity.Property(e => e.ItemDataExpiradaDias).HasColumnName("ITEM_DATA_EXPIRADA_DIAS");

            entity.Property(e => e.ItemDataExpiradaTipo).HasColumnName("ITEM_DATA_EXPIRADA_TIPO");

            entity.Property(e => e.ItemEstoqueNegativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ITEM_ESTOQUE_NEGATIVO");

            entity.Property(e => e.ModoCompacto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("MODO_COMPACTO");

            entity.Property(e => e.Mostramargemlucro)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("MOSTRAMARGEMLUCRO");

            entity.Property(e => e.Mostrarbotoespeso)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("MOSTRARBOTOESPESO");

            entity.Property(e => e.Mostrarsubtotalpdv)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("MOSTRARSUBTOTALPDV");

            entity.Property(e => e.NaoselecClientesbloq)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NAOSELEC_CLIENTESBLOQ");

            entity.Property(e => e.NaoselecClientesbloqman)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NAOSELEC_CLIENTESBLOQMAN");

            entity.Property(e => e.Numserieobrigatorio)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NUMSERIEOBRIGATORIO");

            entity.Property(e => e.Ocultaclientesbloq)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("OCULTACLIENTESBLOQ");

            entity.Property(e => e.Ocultaclientesbloqman)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("OCULTACLIENTESBLOQMAN");

            entity.Property(e => e.PassaCampoDesconto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PASSA_CAMPO_DESCONTO");

            entity.Property(e => e.PassaCampoDimensoes)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PASSA_CAMPO_DIMENSOES");

            entity.Property(e => e.PassaCampoPreco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PASSA_CAMPO_PRECO");

            entity.Property(e => e.PassaCampoQuantidade)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PASSA_CAMPO_QUANTIDADE");

            entity.Property(e => e.PassaCampoSubtotal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PASSA_CAMPO_SUBTOTAL");

            entity.Property(e => e.PdvAbrecupomcodbarras)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_ABRECUPOMCODBARRAS");

            entity.Property(e => e.PdvBloqInsercaoItemPesquisa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_BLOQ_INSERCAO_ITEM_PESQUISA");

            entity.Property(e => e.PdvCadastrarProdutos)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_CADASTRAR_PRODUTOS");

            entity.Property(e => e.PdvCadastrarcliente)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_CADASTRARCLIENTE");

            entity.Property(e => e.PdvConcatenarDimensoes)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_CONCATENAR_DIMENSOES");

            entity.Property(e => e.PdvDefinirFormaPgtoPedido)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_DEFINIR_FORMA_PGTO_PEDIDO");

            entity.Property(e => e.PdvEscondermouse)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_ESCONDERMOUSE");

            entity.Property(e => e.PdvExibefinalOrcped)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_EXIBEFINAL_ORCPED");

            entity.Property(e => e.PdvExibetroco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_EXIBETROCO");

            entity.Property(e => e.PdvImpAuto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO");

            entity.Property(e => e.PdvImpAutoCancelado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_CANCELADO");

            entity.Property(e => e.PdvImpAutoFiscal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_FISCAL");

            entity.Property(e => e.PdvImpAutoFiscalCartao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_FISCAL_CARTAO");

            entity.Property(e => e.PdvImpAutoFiscalCheque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_FISCAL_CHEQUE");

            entity.Property(e => e.PdvImpAutoFiscalCrediario)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_FISCAL_CREDIARIO");

            entity.Property(e => e.PdvImpAutoFiscalDinheiro)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_FISCAL_DINHEIRO");

            entity.Property(e => e.PdvImpAutoFiscalPix)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_FISCAL_PIX");

            entity.Property(e => e.PdvImpAutoFiscalTudo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_FISCAL_TUDO");

            entity.Property(e => e.PdvImpAutoOrcamento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_ORCAMENTO");

            entity.Property(e => e.PdvImpAutoPedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_PEDIDO");

            entity.Property(e => e.PdvImpAutoVenda)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTO_VENDA");

            entity.Property(e => e.PdvImpAutocond)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMP_AUTOCOND");

            entity.Property(e => e.PdvIncluirProdF3)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_INCLUIR_PROD_F3");

            entity.Property(e => e.PdvManterPedAberto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_MANTER_PED_ABERTO");

            entity.Property(e => e.PdvMsgFinalOrcped)
                .HasMaxLength(50)
                .HasColumnName("PDV_MSG_FINAL_ORCPED");

            entity.Property(e => e.PdvMsgFinalVenda)
                .HasMaxLength(50)
                .HasColumnName("PDV_MSG_FINAL_VENDA");

            entity.Property(e => e.PdvPedirvendedor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_PEDIRVENDEDOR");

            entity.Property(e => e.PdvPesquisarproduto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_PESQUISARPRODUTO");

            entity.Property(e => e.PdvSenhaSelecVendedor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_SENHA_SELEC_VENDEDOR");

            entity.Property(e => e.PdvSoarbeep)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_SOARBEEP");

            entity.Property(e => e.PdvTelaimportarpedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_TELAIMPORTARPEDIDO");

            entity.Property(e => e.PdvTempoUltimaTela).HasColumnName("PDV_TEMPO_ULTIMA_TELA");

            entity.Property(e => e.PdvUtilizarTpAutomatico)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_UTILIZAR_TP_AUTOMATICO");

            entity.Property(e => e.Pedircategoria)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRCATEGORIA");

            entity.Property(e => e.Pedirclienteaosalvarpedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRCLIENTEAOSALVARPEDIDO");

            entity.Property(e => e.Pedirdataabertura)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRDATAABERTURA");

            entity.Property(e => e.Pedirdataentrega)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRDATAENTREGA");

            entity.Property(e => e.Pedirdespesa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRDESPESA");

            entity.Property(e => e.Pedirfrete)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRFRETE");

            entity.Property(e => e.Pedirnumpedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRNUMPEDIDO");

            entity.Property(e => e.Pedirordem)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRORDEM");

            entity.Property(e => e.Pedirtipopreco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PEDIRTIPOPRECO");

            entity.Property(e => e.PermiteDesconto100)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITE_DESCONTO100");

            entity.Property(e => e.PermiteKitNegativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITE_KIT_NEGATIVO");

            entity.Property(e => e.PermiteVendaUsoInterno)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITE_VENDA_USO_INTERNO");

            entity.Property(e => e.Permitirvalorzerado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITIRVALORZERADO");

            entity.Property(e => e.Quantidadefracionada)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("QUANTIDADEFRACIONADA");

            entity.Property(e => e.Quantmaxitens).HasColumnName("QUANTMAXITENS");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.SolicitaMotivoCancelamento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SOLICITA_MOTIVO_CANCELAMENTO");

            entity.Property(e => e.SolicitarDadosCargaObs)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SOLICITAR_DADOS_CARGA_OBS");

            entity.Property(e => e.SugerirObsContasXObsPedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SUGERIR_OBS_CONTAS_X_OBS_PEDIDO");

            entity.Property(e => e.TabelaSincSeller).HasColumnName("TABELA_SINC_SELLER");

            entity.Property(e => e.Tipodescmaxitem).HasColumnName("TIPODESCMAXITEM");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.UsarNmFantasiaApelido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("USAR_NM_FANTASIA_APELIDO");

            entity.Property(e => e.VenderProdutoInativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("VENDER_PRODUTO_INATIVO");

            entity.Property(e => e.VerificarPesoAoFaturar)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("VERIFICAR_PESO_AO_FATURAR");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConfigPedido> entity);
    }
}
