// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ConfigCadastroConfiguration : IEntityTypeConfiguration<ConfigCadastro>
    {
        public void Configure(EntityTypeBuilder<ConfigCadastro> entity)
        {
            entity.ToTable("CONFIG_CADASTRO");

            entity.HasIndex(e => e.Id, "PK_CONFIG_CADASTRO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.BuscaprodCodbalanca)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODBALANCA");

            entity.Property(e => e.BuscaprodCodbarras)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODBARRAS");

            entity.Property(e => e.BuscaprodCodcaixa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODCAIXA");

            entity.Property(e => e.BuscaprodCodfornecedor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODFORNECEDOR");

            entity.Property(e => e.BuscaprodCodgrade)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODGRADE");

            entity.Property(e => e.BuscaprodCodigo2)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODIGO2");

            entity.Property(e => e.BuscaprodCodigo3)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODIGO3");

            entity.Property(e => e.BuscaprodCodigo4)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_CODIGO4");

            entity.Property(e => e.BuscaprodNumserie)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BUSCAPROD_NUMSERIE");

            entity.Property(e => e.CliCategoriaobrigatoria)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CLI_CATEGORIAOBRIGATORIA");

            entity.Property(e => e.CliValidaBairro)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CLI_VALIDA_BAIRRO");

            entity.Property(e => e.CliValidaCep)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CLI_VALIDA_CEP");

            entity.Property(e => e.CliValidaCpf)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CLI_VALIDA_CPF");

            entity.Property(e => e.CliValidaEndereco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CLI_VALIDA_ENDERECO");

            entity.Property(e => e.CliValidaTelefone)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CLI_VALIDA_TELEFONE");

            entity.Property(e => e.CodigosProdutosGas)
                .HasMaxLength(20)
                .HasColumnName("CODIGOS_PRODUTOS_GAS");

            entity.Property(e => e.Codproddigfinal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CODPRODDIGFINAL");

            entity.Property(e => e.Codproddiginicial)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CODPRODDIGINICIAL");

            entity.Property(e => e.Codprodnumdigtotal).HasColumnName("CODPRODNUMDIGTOTAL");

            entity.Property(e => e.CorEstoqueMinimo).HasColumnName("COR_ESTOQUE_MINIMO");

            entity.Property(e => e.CorEstoqueZerado).HasColumnName("COR_ESTOQUE_ZERADO");

            entity.Property(e => e.CorProdEmDestaque).HasColumnName("COR_PROD_EM_DESTAQUE");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.ExibePreco2)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBE_PRECO2");

            entity.Property(e => e.ExibePreco3)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBE_PRECO3");

            entity.Property(e => e.ExibirEstoque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBIR_ESTOQUE");

            entity.Property(e => e.ExibirPrecoPromocional)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBIR_PRECO_PROMOCIONAL");

            entity.Property(e => e.ExibirUltimasCompras)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBIR_ULTIMAS_COMPRAS");

            entity.Property(e => e.ExibirVendaMensal)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBIR_VENDA_MENSAL");

            entity.Property(e => e.Fatorcalculoestoqueminimoaut)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FATORCALCULOESTOQUEMINIMOAUT");

            entity.Property(e => e.GradeExibircodigo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("GRADE_EXIBIRCODIGO");

            entity.Property(e => e.Gradecampocodigo)
                .HasMaxLength(20)
                .HasColumnName("GRADECAMPOCODIGO");

            entity.Property(e => e.Gradecampodescricao)
                .HasMaxLength(20)
                .HasColumnName("GRADECAMPODESCRICAO");

            entity.Property(e => e.HabilitarExportacaoGas)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("HABILITAR_EXPORTACAO_GAS");

            entity.Property(e => e.LayoutTelaProduto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LAYOUT_TELA_PRODUTO");

            entity.Property(e => e.NomePreco2)
                .HasMaxLength(10)
                .HasColumnName("NOME_PRECO2");

            entity.Property(e => e.NomePreco3)
                .HasMaxLength(10)
                .HasColumnName("NOME_PRECO3");

            entity.Property(e => e.PerguntaAtualizaSimilar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERGUNTA_ATUALIZA_SIMILAR");

            entity.Property(e => e.PesqQtdeRegistros).HasColumnName("PESQ_QTDE_REGISTROS");

            entity.Property(e => e.PesquisaAbreTelaCheia)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PESQUISA_ABRE_TELA_CHEIA");

            entity.Property(e => e.ProdCodigo02)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_CODIGO02");

            entity.Property(e => e.ProdCodigo03)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_CODIGO03");

            entity.Property(e => e.ProdCodigo04)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_CODIGO04");

            entity.Property(e => e.ProdCodigoEan)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_CODIGO_EAN");

            entity.Property(e => e.ProdDescCod02)
                .HasMaxLength(30)
                .HasColumnName("PROD_DESC_COD02");

            entity.Property(e => e.ProdDescCod03)
                .HasMaxLength(30)
                .HasColumnName("PROD_DESC_COD03");

            entity.Property(e => e.ProdDescCod04)
                .HasMaxLength(30)
                .HasColumnName("PROD_DESC_COD04");

            entity.Property(e => e.ProdExibeprecoTp)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_EXIBEPRECO_TP");

            entity.Property(e => e.ProdExibirSincPreco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_EXIBIR_SINC_PRECO");

            entity.Property(e => e.ProdExibirnumserie)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_EXIBIRNUMSERIE");

            entity.Property(e => e.ProdPesqCodigoParcial)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PROD_PESQ_CODIGO_PARCIAL");

            entity.Property(e => e.Qtdmesesestoqueminimoautomatico).HasColumnName("QTDMESESESTOQUEMINIMOAUTOMATICO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Validarcadastrocliente)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("VALIDARCADASTROCLIENTE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConfigCadastro> entity);
    }
}
