// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ConfigLocalConfiguration : IEntityTypeConfiguration<ConfigLocal>
    {
        public void Configure(EntityTypeBuilder<ConfigLocal> entity)
        {
            entity.HasKey(e => e.NumTerminal);

            entity.ToTable("CONFIG_LOCAL");

            entity.HasIndex(e => e.NumTerminal, "PK_CONFIG_LOCAL")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.BalBaudrate).HasColumnName("BAL_BAUDRATE");

            entity.Property(e => e.BalDatabits).HasColumnName("BAL_DATABITS");

            entity.Property(e => e.BalHandshaking).HasColumnName("BAL_HANDSHAKING");

            entity.Property(e => e.BalMarca).HasColumnName("BAL_MARCA");

            entity.Property(e => e.BalMonitorar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BAL_MONITORAR");

            entity.Property(e => e.BalParity).HasColumnName("BAL_PARITY");

            entity.Property(e => e.BalPorta)
                .HasMaxLength(20)
                .HasColumnName("BAL_PORTA");

            entity.Property(e => e.BalStopbits).HasColumnName("BAL_STOPBITS");

            entity.Property(e => e.BalTimeout).HasColumnName("BAL_TIMEOUT");

            entity.Property(e => e.CaixaAutoimpAbertura).HasColumnName("CAIXA_AUTOIMP_ABERTURA");

            entity.Property(e => e.CaixaAutoimpFechamento).HasColumnName("CAIXA_AUTOIMP_FECHAMENTO");

            entity.Property(e => e.CaixaAutoimpSangria).HasColumnName("CAIXA_AUTOIMP_SANGRIA");

            entity.Property(e => e.CaixaClientePadraoAreceber).HasColumnName("CAIXA_CLIENTE_PADRAO_ARECEBER");

            entity.Property(e => e.CaixaExibesubtotaldincheq)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_EXIBESUBTOTALDINCHEQ");

            entity.Property(e => e.CaixaFpgtoLancamentoAreceber).HasColumnName("CAIXA_FPGTO_LANCAMENTO_ARECEBER");

            entity.Property(e => e.CaixaImpCaixaCego)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_IMP_CAIXA_CEGO");

            entity.Property(e => e.CaixaImpSangConferencia)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_IMP_SANG_CONFERENCIA");

            entity.Property(e => e.CaixaImpValorNfceCaixa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_IMP_VALOR_NFCE_CAIXA");

            entity.Property(e => e.CaixaLancarFaltasAreceber)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_LANCAR_FALTAS_ARECEBER");

            entity.Property(e => e.CaixaLancarSobrasAreceber)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_LANCAR_SOBRAS_ARECEBER");

            entity.Property(e => e.CaixaSomaCredCli)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_SOMA_CRED_CLI");

            entity.Property(e => e.CaixaVerpedaberto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CAIXA_VERPEDABERTO");

            entity.Property(e => e.Desabilitartransparencia)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESABILITARTRANSPARENCIA");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.GavModelo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("GAV_MODELO");

            entity.Property(e => e.GavPorta)
                .HasMaxLength(100)
                .HasColumnName("GAV_PORTA");

            entity.Property(e => e.GavStringlpt)
                .HasMaxLength(60)
                .HasColumnName("GAV_STRINGLPT");

            entity.Property(e => e.GerLoginautomatico)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("GER_LOGINAUTOMATICO");

            entity.Property(e => e.GerLoginautosenha)
                .HasMaxLength(10)
                .HasColumnName("GER_LOGINAUTOSENHA");

            entity.Property(e => e.GerLoginautousuario)
                .HasMaxLength(80)
                .HasColumnName("GER_LOGINAUTOUSUARIO");

            entity.Property(e => e.GerMultiplasinstancias)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("GER_MULTIPLASINSTANCIAS");

            entity.Property(e => e.LeitAtivado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LEIT_ATIVADO");

            entity.Property(e => e.LeitBaudrate)
                .HasMaxLength(10)
                .HasColumnName("LEIT_BAUDRATE");

            entity.Property(e => e.LeitDatabits)
                .HasMaxLength(10)
                .HasColumnName("LEIT_DATABITS");

            entity.Property(e => e.LeitExcluirSuf)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LEIT_EXCLUIR_SUF");

            entity.Property(e => e.LeitHandshake).HasColumnName("LEIT_HANDSHAKE");

            entity.Property(e => e.LeitHardflow)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LEIT_HARDFLOW");

            entity.Property(e => e.LeitIntervalo).HasColumnName("LEIT_INTERVALO");

            entity.Property(e => e.LeitParity).HasColumnName("LEIT_PARITY");

            entity.Property(e => e.LeitPortaserial)
                .HasMaxLength(10)
                .HasColumnName("LEIT_PORTASERIAL");

            entity.Property(e => e.LeitSoftflow)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LEIT_SOFTFLOW");

            entity.Property(e => e.LeitStopbits).HasColumnName("LEIT_STOPBITS");

            entity.Property(e => e.LeitSufixo)
                .HasMaxLength(10)
                .HasColumnName("LEIT_SUFIXO");

            entity.Property(e => e.PdvAbrirAutomatico)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_ABRIR_AUTOMATICO");

            entity.Property(e => e.PdvAtivaControleFoco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_ATIVA_CONTROLE_FOCO");

            entity.Property(e => e.PdvDocPadrao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_DOC_PADRAO");

            entity.Property(e => e.PdvFaturar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_FATURAR");

            entity.Property(e => e.PdvFaturarPedidoForaPdv)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_FATURAR_PEDIDO_FORA_PDV");

            entity.Property(e => e.PdvFecharPedidoZerado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_FECHAR_PEDIDO_ZERADO");

            entity.Property(e => e.PdvImportReabre)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_IMPORT_REABRE");

            entity.Property(e => e.PdvIndiceSomItem).HasColumnName("PDV_INDICE_SOM_ITEM");

            entity.Property(e => e.PdvLoginautomatico)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_LOGINAUTOMATICO");

            entity.Property(e => e.PdvLoginautosenha)
                .HasMaxLength(60)
                .HasColumnName("PDV_LOGINAUTOSENHA");

            entity.Property(e => e.PdvLoginautousuario)
                .HasMaxLength(80)
                .HasColumnName("PDV_LOGINAUTOUSUARIO");

            entity.Property(e => e.PdvMultiplasinstancias)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_MULTIPLASINSTANCIAS");

            entity.Property(e => e.PdvOrcamento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_ORCAMENTO");

            entity.Property(e => e.PdvPedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_PEDIDO");

            entity.Property(e => e.PdvRecebercontas)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_RECEBERCONTAS");

            entity.Property(e => e.PdvSalvaGridTerminal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_SALVA_GRID_TERMINAL");

            entity.Property(e => e.PdvStatus)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_STATUS");

            entity.Property(e => e.PdvTipoFiscal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_TIPO_FISCAL");

            entity.Property(e => e.PdvUsaTef)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_USA_TEF");

            entity.Property(e => e.PdvVendaManual)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PDV_VENDA_MANUAL");

            entity.Property(e => e.Permitirdescontopgtoconsumidor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITIRDESCONTOPGTOCONSUMIDOR");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Tipopreco).HasColumnName("TIPOPRECO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Ultimaexecintegracao)
                .HasColumnType("DATE")
                .HasColumnName("ULTIMAEXECINTEGRACAO");

            entity.Property(e => e.Usapesquisasimplificada)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("USAPESQUISASIMPLIFICADA");

            entity.Property(e => e.ZerarMoedasAberturaCx)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ZERAR_MOEDAS_ABERTURA_CX");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConfigLocal> entity);
    }
}
