// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ConfigEmpresaConsultaConfiguration : IEntityTypeConfiguration<ConfigEmpresaConsulta>
    {
        public void Configure(EntityTypeBuilder<ConfigEmpresaConsulta> entity)
        {
            entity.ToTable("CONFIG_EMPRESA_CONSULTA");

            entity.HasIndex(e => e.Id, "PK_CONFIG_EMPRESA_CONSULTA")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Caminho)
                .HasMaxLength(100)
                .HasColumnName("CAMINHO");

            entity.Property(e => e.Ip)
                .HasMaxLength(100)
                .HasColumnName("IP");

            entity.Property(e => e.Loja)
                .HasMaxLength(100)
                .HasColumnName("LOJA");

            entity.Property(e => e.Porta)
                .HasMaxLength(100)
                .HasColumnName("PORTA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConfigEmpresaConsulta> entity);
    }
}
