// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class DfeSerieNumeracaoConfiguration : IEntityTypeConfiguration<DfeSerieNumeracao>
    {
        public void Configure(EntityTypeBuilder<DfeSerieNumeracao> entity)
        {
            entity.ToTable("DFE_SERIE_NUMERACAO");

            entity.HasIndex(e => e.Id, "PK_DFE_SERIE_NUMERACAO")
                .IsUnique();

            entity.HasIndex(e => new { e.Ambiente, e.Numeracao, e.TipoDocumento, e.Serie }, "UNQ1_DFE_SERIE_NUMERACAO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Ambiente).HasColumnName("AMBIENTE");

            entity.Property(e => e.Numeracao).HasColumnName("NUMERACAO");

            entity.Property(e => e.NumeracaoExtraordinaria).HasColumnName("NUMERACAO_EXTRAORDINARIA");

            entity.Property(e => e.Serie).HasColumnName("SERIE");

            entity.Property(e => e.SerieExtraordinaria).HasColumnName("SERIE_EXTRAORDINARIA");

            entity.Property(e => e.TipoDocumento).HasColumnName("TIPO_DOCUMENTO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.ValorExtraordinario).HasColumnName("VALOR_EXTRAORDINARIO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DfeSerieNumeracao> entity);
    }
}
