// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EmpresasConfiguration : IEntityTypeConfiguration<Empresas>
    {
        public void Configure(EntityTypeBuilder<Empresas> entity)
        {
            entity.HasKey(e => e.CdEmpresa);

            entity.ToTable("EMPRESAS");

            entity.HasIndex(e => e.CdEmpresa, "PK_EMPRESAS")
                .IsUnique();

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.AliquotaCofins)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ALIQUOTA_COFINS");

            entity.Property(e => e.AliquotaIcms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ALIQUOTA_ICMS");

            entity.Property(e => e.AliquotaPis)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ALIQUOTA_PIS");

            entity.Property(e => e.Aliquotapadrao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ALIQUOTAPADRAO");

            entity.Property(e => e.CdContabilista).HasColumnName("CD_CONTABILISTA");

            entity.Property(e => e.ChavePix)
                .HasMaxLength(32)
                .HasColumnName("CHAVE_PIX");

            entity.Property(e => e.Cnaefiscal)
                .HasMaxLength(10)
                .HasColumnName("CNAEFISCAL");

            entity.Property(e => e.CpfCnpj)
                .HasMaxLength(18)
                .HasColumnName("CPF_CNPJ");

            entity.Property(e => e.Crt).HasColumnName("CRT");

            entity.Property(e => e.CstPadrao)
                .HasMaxLength(3)
                .HasColumnName("CST_PADRAO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtExpWeb).HasColumnName("DT_EXP_WEB");

            entity.Property(e => e.DtFundacao)
                .HasColumnType("DATE")
                .HasColumnName("DT_FUNDACAO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("EMAIL");

            entity.Property(e => e.EmailHost)
                .HasMaxLength(30)
                .HasColumnName("EMAIL_HOST");

            entity.Property(e => e.EmailPorta)
                .HasMaxLength(10)
                .HasColumnName("EMAIL_PORTA");

            entity.Property(e => e.EmailSenha)
                .HasMaxLength(30)
                .HasColumnName("EMAIL_SENHA");

            entity.Property(e => e.EmailSsl)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMAIL_SSL");

            entity.Property(e => e.EmailTipossl).HasColumnName("EMAIL_TIPOSSL");

            entity.Property(e => e.EmailTipotls).HasColumnName("EMAIL_TIPOTLS");

            entity.Property(e => e.EmailUsuario)
                .HasMaxLength(400)
                .HasColumnName("EMAIL_USUARIO");

            entity.Property(e => e.EmpresaPadrao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMPRESA_PADRAO");

            entity.Property(e => e.EndBairro)
                .HasMaxLength(35)
                .HasColumnName("END_BAIRRO");

            entity.Property(e => e.EndCdMunicipio).HasColumnName("END_CD_MUNICIPIO");

            entity.Property(e => e.EndCdPais).HasColumnName("END_CD_PAIS");

            entity.Property(e => e.EndCep)
                .HasMaxLength(9)
                .HasColumnName("END_CEP");

            entity.Property(e => e.EndComplemento)
                .HasMaxLength(60)
                .HasColumnName("END_COMPLEMENTO");

            entity.Property(e => e.EndLogradouro)
                .HasMaxLength(60)
                .HasColumnName("END_LOGRADOURO");

            entity.Property(e => e.EndNmMunicipio)
                .HasMaxLength(35)
                .HasColumnName("END_NM_MUNICIPIO");

            entity.Property(e => e.EndNumero)
                .HasMaxLength(20)
                .HasColumnName("END_NUMERO");

            entity.Property(e => e.EndReferencia)
                .HasMaxLength(200)
                .HasColumnName("END_REFERENCIA");

            entity.Property(e => e.EndUf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("END_UF");

            entity.Property(e => e.Fax)
                .HasMaxLength(70)
                .HasColumnName("FAX");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.IncentivadorCultural)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INCENTIVADOR_CULTURAL");

            entity.Property(e => e.InscMunicipal)
                .HasMaxLength(15)
                .HasColumnName("INSC_MUNICIPAL");

            entity.Property(e => e.IpiApuracao).HasColumnName("IPI_APURACAO");

            entity.Property(e => e.Logo).HasColumnName("LOGO");

            entity.Property(e => e.Logorelatorio).HasColumnName("LOGORELATORIO");

            entity.Property(e => e.MetroQuadrado).HasColumnName("METRO_QUADRADO");

            entity.Property(e => e.MsgAniversarioClientes).HasColumnName("MSG_ANIVERSARIO_CLIENTES");

            entity.Property(e => e.NmEmpresa)
                .HasMaxLength(60)
                .HasColumnName("NM_EMPRESA");

            entity.Property(e => e.Nomefantasia)
                .HasMaxLength(40)
                .HasColumnName("NOMEFANTASIA");

            entity.Property(e => e.NumFuncionariosAtivos).HasColumnName("NUM_FUNCIONARIOS_ATIVOS");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.ObsPix).HasColumnName("OBS_PIX");

            entity.Property(e => e.QrcodePix).HasColumnName("QRCODE_PIX");

            entity.Property(e => e.ResponsavelCpf)
                .HasMaxLength(18)
                .HasColumnName("RESPONSAVEL_CPF");

            entity.Property(e => e.ResponsavelNome)
                .HasMaxLength(80)
                .HasColumnName("RESPONSAVEL_NOME");

            entity.Property(e => e.RetemCreditoIcms)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("RETEM_CREDITO_ICMS");

            entity.Property(e => e.RetemCreditoIcmsst)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("RETEM_CREDITO_ICMSST");

            entity.Property(e => e.RgIe)
                .HasMaxLength(15)
                .HasColumnName("RG_IE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Slogan)
                .HasMaxLength(150)
                .HasColumnName("SLOGAN");

            entity.Property(e => e.Suframa)
                .HasMaxLength(10)
                .HasColumnName("SUFRAMA");

            entity.Property(e => e.Telefone)
                .HasMaxLength(70)
                .HasColumnName("TELEFONE");

            entity.Property(e => e.TipoSimplesNacional).HasColumnName("TIPO_SIMPLES_NACIONAL");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.UtilizaSeller)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("UTILIZA_SELLER");

            entity.Property(e => e.ValorMeta)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_META");

            entity.Property(e => e.Website)
                .HasMaxLength(50)
                .HasColumnName("WEBSITE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Empresas> entity);
    }
}
