// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EndCertificadoConfigConfiguration : IEntityTypeConfiguration<EndCertificadoConfig>
    {
        public void Configure(EntityTypeBuilder<EndCertificadoConfig> entity)
        {
            entity.ToTable("END_CERTIFICADO_CONFIG");

            entity.HasIndex(e => e.Id, "PK_END_CERTIFICADO_CONFIG")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.CertificadoCd).HasColumnName("CERTIFICADO_CD");

            entity.Property(e => e.CertificadoDesc)
                .HasMaxLength(60)
                .HasColumnName("CERTIFICADO_DESC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EndCertificadoConfig> entity);
    }
}
