// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaItemImportacaoConfiguration : IEntityTypeConfiguration<EntradaItemImportacao>
    {
        public void Configure(EntityTypeBuilder<EntradaItemImportacao> entity)
        {
            entity.HasKey(e => new { e.CdNota, e.CdItem });

            entity.ToTable("ENTRADA_ITEM_IMPORTACAO");

            entity.HasIndex(e => new { e.CdNota, e.CdItem }, "PK_ENTRADA_ITEM_IMPORTACAO")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.CdItem).HasColumnName("CD_ITEM");

            entity.Property(e => e.Cexportador).HasColumnName("CEXPORTADOR");

            entity.Property(e => e.Ddesemb)
                .HasColumnType("DATE")
                .HasColumnName("DDESEMB");

            entity.Property(e => e.Ddi)
                .HasColumnType("DATE")
                .HasColumnName("DDI");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Ndi).HasColumnName("NDI");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ufdesemb)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("UFDESEMB");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Xlocdesemb)
                .HasMaxLength(50)
                .HasColumnName("XLOCDESEMB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaItemImportacao> entity);
    }
}
