// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaGradeQuantidadeConfiguration : IEntityTypeConfiguration<EntradaGradeQuantidade>
    {
        public void Configure(EntityTypeBuilder<EntradaGradeQuantidade> entity)
        {
            entity.HasKey(e => new { e.CdNota, e.CdGrade, e.CdItem, e.CdDeposito });

            entity.ToTable("ENTRADA_GRADE_QUANTIDADE");

            entity.HasIndex(e => new { e.CdNota, e.CdGrade, e.CdItem, e.CdDeposito }, "PK_ENTRADA_GRADE_QUANTIDADE")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.CdGrade).HasColumnName("CD_GRADE");

            entity.Property(e => e.CdItem).HasColumnName("CD_ITEM");

            entity.Property(e => e.CdDeposito).HasColumnName("CD_DEPOSITO");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Quantidade)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QUANTIDADE");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaGradeQuantidade> entity);
    }
}
