// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaFiscalConfiguration : IEntityTypeConfiguration<EntradaFiscal>
    {
        public void Configure(EntityTypeBuilder<EntradaFiscal> entity)
        {
            entity.HasKey(e => e.CdNota);

            entity.ToTable("ENTRADA_FISCAL");

            entity.HasIndex(e => e.NotaFechada, "ENTRADA_FISCAL_IDX1");

            entity.HasIndex(e => e.CdFornecedor, "ENTRADA_FISCAL_IDX2");

            entity.HasIndex(e => e.DtEntrada, "ENTRADA_FISCAL_IDX3");

            entity.HasIndex(e => e.CdNota, "PK_ENTRADA_FISCAL")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.AcresDescEspecial)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ACRES_DESC_ESPECIAL");

            entity.Property(e => e.ArquivoXml).HasColumnName("ARQUIVO_XML");

            entity.Property(e => e.AtivoImobilizado)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ATIVO_IMOBILIZADO");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.CdFornecedor).HasColumnName("CD_FORNECEDOR");

            entity.Property(e => e.Cfop)
                .HasMaxLength(6)
                .HasColumnName("CFOP");

            entity.Property(e => e.ChaveNfe)
                .HasMaxLength(50)
                .HasColumnName("CHAVE_NFE");

            entity.Property(e => e.Cnpj)
                .HasMaxLength(18)
                .HasColumnName("CNPJ");

            entity.Property(e => e.CnpjDest)
                .HasMaxLength(18)
                .HasColumnName("CNPJ_DEST");

            entity.Property(e => e.CustoAdicional)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CUSTO_ADICIONAL");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DescontoPercentual)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESCONTO_PERCENTUAL");

            entity.Property(e => e.DescontoTotal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTO_TOTAL");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtEmissao)
                .HasColumnType("DATE")
                .HasColumnName("DT_EMISSAO");

            entity.Property(e => e.DtEntrada)
                .HasColumnType("DATE")
                .HasColumnName("DT_ENTRADA");

            entity.Property(e => e.DtExpWeb).HasColumnName("DT_EXP_WEB");

            entity.Property(e => e.DtFechamento).HasColumnName("DT_FECHAMENTO");

            entity.Property(e => e.DtSaida).HasColumnName("DT_SAIDA");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.FreteAdicional)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETE_ADICIONAL");

            entity.Property(e => e.Fretechegada)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETECHEGADA");

            entity.Property(e => e.IcmsBase)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_BASE");

            entity.Property(e => e.IcmsBasesubst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_BASESUBST");

            entity.Property(e => e.IcmsDesonerado)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_DESONERADO");

            entity.Property(e => e.IcmsValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_VALOR");

            entity.Property(e => e.IcmsValorsubst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_VALORSUBST");

            entity.Property(e => e.IndFrete)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IND_FRETE");

            entity.Property(e => e.IndPgto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IND_PGTO");

            entity.Property(e => e.Margemlucro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEMLUCRO");

            entity.Property(e => e.Modelo)
                .HasMaxLength(5)
                .HasColumnName("MODELO");

            entity.Property(e => e.NatOperacao)
                .HasMaxLength(100)
                .HasColumnName("NAT_OPERACAO");

            entity.Property(e => e.NfBonificacao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NF_BONIFICACAO");

            entity.Property(e => e.NmFornecedor)
                .HasMaxLength(100)
                .HasColumnName("NM_FORNECEDOR");

            entity.Property(e => e.NotaFechada)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NOTA_FECHADA");

            entity.Property(e => e.NumDocumento).HasColumnName("NUM_DOCUMENTO");

            entity.Property(e => e.Obs)
                .HasMaxLength(100)
                .HasColumnName("OBS");

            entity.Property(e => e.OutrasDespesas)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("OUTRAS_DESPESAS");

            entity.Property(e => e.Serie)
                .HasMaxLength(3)
                .HasColumnName("SERIE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasColumnName("STATUS");

            entity.Property(e => e.TipoNota)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_NOTA");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.UsoInterno)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("USO_INTERNO");

            entity.Property(e => e.ValorCofins)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_COFINS");

            entity.Property(e => e.ValorFrete)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_FRETE");

            entity.Property(e => e.ValorIi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_II");

            entity.Property(e => e.ValorIpi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_IPI");

            entity.Property(e => e.ValorPis)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_PIS");

            entity.Property(e => e.ValorSeguro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_SEGURO");

            entity.Property(e => e.ValorTotalNota)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_TOTAL_NOTA");

            entity.Property(e => e.ValorTotalNotaOriginal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR_TOTAL_NOTA_ORIGINAL");

            entity.Property(e => e.VrTotalProd)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VR_TOTAL_PROD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaFiscal> entity);
    }
}
