// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaItemImportLacresConfiguration : IEntityTypeConfiguration<EntradaItemImportLacres>
    {
        public void Configure(EntityTypeBuilder<EntradaItemImportLacres> entity)
        {
            entity.HasKey(e => new { e.CdNota, e.CdItem, e.Ndi });

            entity.ToTable("ENTRADA_ITEM_IMPORT_LACRES");

            entity.HasIndex(e => new { e.Ndi, e.CdNota, e.CdItem }, "PK_ENTRADA_ITEM_IMPORT_LACRES")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.CdItem).HasColumnName("CD_ITEM");

            entity.Property(e => e.Ndi).HasColumnName("NDI");

            entity.Property(e => e.Cfabricante).HasColumnName("CFABRICANTE");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Nadicao).HasColumnName("NADICAO");

            entity.Property(e => e.Nseqadic).HasColumnName("NSEQADIC");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Vdescdi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VDESCDI");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaItemImportLacres> entity);
    }
}
