// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaConfigConfiguration : IEntityTypeConfiguration<EntradaConfig>
    {
        public void Configure(EntityTypeBuilder<EntradaConfig> entity)
        {
            entity.HasKey(e => e.NumTerminal);

            entity.ToTable("ENTRADA_CONFIG");

            entity.HasIndex(e => e.NumTerminal, "PK_ENTRADA_CONFIG")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.AlterarCodFornecedor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALTERAR_COD_FORNECEDOR");

            entity.Property(e => e.AlterarCorProduto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALTERAR_COR_PRODUTO");

            entity.Property(e => e.AtualizaCofins)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ATUALIZA_COFINS");

            entity.Property(e => e.AtualizaIcms)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ATUALIZA_ICMS");

            entity.Property(e => e.AtualizaIpi)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ATUALIZA_IPI");

            entity.Property(e => e.AtualizaPis)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ATUALIZA_PIS");

            entity.Property(e => e.BloqPesqAutomaticaCodFornec)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BLOQ_PESQ_AUTOMATICA_COD_FORNEC");

            entity.Property(e => e.CaminhoExportarXml)
                .HasMaxLength(400)
                .HasColumnName("CAMINHO_EXPORTAR_XML");

            entity.Property(e => e.CampoPesqProdVincXml).HasColumnName("CAMPO_PESQ_PROD_VINC_XML");

            entity.Property(e => e.CampoPesquisaProduto).HasColumnName("CAMPO_PESQUISA_PRODUTO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.ExibeMsgPmc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBE_MSG_PMC");

            entity.Property(e => e.ExibirMsgValor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBIR_MSG_VALOR");

            entity.Property(e => e.ExibirValorOriginal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBIR_VALOR_ORIGINAL");

            entity.Property(e => e.ForcarVinculo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("FORCAR_VINCULO");

            entity.Property(e => e.HabilitaMargemGlobal)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("HABILITA_MARGEM_GLOBAL");

            entity.Property(e => e.NaoSomarImposto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NAO_SOMAR_IMPOSTO");

            entity.Property(e => e.PreencherFabricanteFornec)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PREENCHER_FABRICANTE_FORNEC");

            entity.Property(e => e.QtdeUltimosCustos).HasColumnName("QTDE_ULTIMOS_CUSTOS");

            entity.Property(e => e.TruncarValor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TRUNCAR_VALOR");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.UsaPrevisaoGastoPedidocompra)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("USA_PREVISAO_GASTO_PEDIDOCOMPRA");

            entity.Property(e => e.VerificarGradeZerada)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("VERIFICAR_GRADE_ZERADA");

            entity.Property(e => e.VinculoApenasCodbarras)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("VINCULO_APENAS_CODBARRAS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaConfig> entity);
    }
}
