// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaNumserieConfiguration : IEntityTypeConfiguration<EntradaNumserie>
    {
        public void Configure(EntityTypeBuilder<EntradaNumserie> entity)
        {
            entity.HasKey(e => new { e.CdNota, e.CdProduto, e.Numserie });

            entity.ToTable("ENTRADA_NUMSERIE");

            entity.HasIndex(e => new { e.Numserie, e.CdNota, e.CdProduto }, "PK_ENTRADA_NUMSERIE")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Numserie)
                .HasMaxLength(50)
                .HasColumnName("NUMSERIE");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaNumserie> entity);
    }
}
