// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaItemMedicamentoConfiguration : IEntityTypeConfiguration<EntradaItemMedicamento>
    {
        public void Configure(EntityTypeBuilder<EntradaItemMedicamento> entity)
        {
            entity.HasKey(e => new { e.CdNota, e.CdItem, e.Nlote });

            entity.ToTable("ENTRADA_ITEM_MEDICAMENTO");

            entity.HasIndex(e => new { e.Dval, e.Qlote }, "ENTRADA_ITEM_MEDICAMENTO_IDX1");

            entity.HasIndex(e => new { e.Nlote, e.CdNota, e.CdItem }, "PK_ENTRADA_ITEM_MEDICAMENTO")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.CdItem).HasColumnName("CD_ITEM");

            entity.Property(e => e.Nlote)
                .HasMaxLength(20)
                .HasColumnName("NLOTE");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.Dfab)
                .HasColumnType("DATE")
                .HasColumnName("DFAB");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Dval)
                .HasColumnType("DATE")
                .HasColumnName("DVAL");

            entity.Property(e => e.Qlote)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QLOTE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Vpmc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VPMC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaItemMedicamento> entity);
    }
}
