// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaItemFiscalConfiguration : IEntityTypeConfiguration<EntradaItemFiscal>
    {
        public void Configure(EntityTypeBuilder<EntradaItemFiscal> entity)
        {
            entity.HasKey(e => new { e.CdNota, e.CdItem });

            entity.ToTable("ENTRADA_ITEM_FISCAL");

            entity.HasIndex(e => new { e.CdNota, e.CdItem }, "PK_ENTRADA_ITEM_FISCAL")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.CdItem).HasColumnName("CD_ITEM");

            entity.Property(e => e.Atualizasimilares)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ATUALIZASIMILARES");

            entity.Property(e => e.CdEanTrib)
                .HasMaxLength(14)
                .HasColumnName("CD_EAN_TRIB");

            entity.Property(e => e.CdGrupo).HasColumnName("CD_GRUPO");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Cest)
                .HasMaxLength(7)
                .HasColumnName("CEST");

            entity.Property(e => e.Cfop)
                .HasMaxLength(6)
                .HasColumnName("CFOP");

            entity.Property(e => e.CfopEntrada)
                .HasMaxLength(6)
                .HasColumnName("CFOP_ENTRADA");

            entity.Property(e => e.Classfiscal)
                .HasMaxLength(12)
                .HasColumnName("CLASSFISCAL");

            entity.Property(e => e.CodBeneficioFiscal)
                .HasMaxLength(10)
                .HasColumnName("COD_BENEFICIO_FISCAL");

            entity.Property(e => e.CodProdFornec)
                .HasMaxLength(20)
                .HasColumnName("COD_PROD_FORNEC");

            entity.Property(e => e.CofinsAliqprodVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINS_ALIQPROD_VAL");

            entity.Property(e => e.CofinsBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINS_BC_VAL");

            entity.Property(e => e.CofinsCst)
                .HasMaxLength(3)
                .HasColumnName("COFINS_CST");

            entity.Property(e => e.CofinsPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINS_PORC");

            entity.Property(e => e.CofinsQuantBcprod)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINS_QUANT_BCPROD");

            entity.Property(e => e.CofinsVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINS_VAL");

            entity.Property(e => e.CofinsstAliqprodVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINSST_ALIQPROD_VAL");

            entity.Property(e => e.CofinsstBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINSST_BC_VAL");

            entity.Property(e => e.CofinsstPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINSST_PORC");

            entity.Property(e => e.CofinsstQuantBcprod)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINSST_QUANT_BCPROD");

            entity.Property(e => e.CofinsstVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINSST_VAL");

            entity.Property(e => e.Conferido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CONFERIDO");

            entity.Property(e => e.Cst)
                .HasMaxLength(3)
                .HasColumnName("CST");

            entity.Property(e => e.CustoAdicional)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CUSTO_ADICIONAL");

            entity.Property(e => e.CustoUnitario)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CUSTO_UNITARIO");

            entity.Property(e => e.Customedio)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CUSTOMEDIO");

            entity.Property(e => e.CxCodBarraCaixa)
                .HasMaxLength(14)
                .HasColumnName("CX_COD_BARRA_CAIXA");

            entity.Property(e => e.CxUndconversao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CX_UNDCONVERSAO");

            entity.Property(e => e.CxValorcaixa)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CX_VALORCAIXA");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DescontoVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTO_VAL");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Ean)
                .HasMaxLength(14)
                .HasColumnName("EAN");

            entity.Property(e => e.Extipi)
                .HasMaxLength(12)
                .HasColumnName("EXTIPI");

            entity.Property(e => e.Flag)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("FLAG");

            entity.Property(e => e.FreteAdicional)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETE_ADICIONAL");

            entity.Property(e => e.FreteVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETE_VAL");

            entity.Property(e => e.Fretechegada)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETECHEGADA");

            entity.Property(e => e.Fretesaida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETESAIDA");

            entity.Property(e => e.Icms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS");

            entity.Property(e => e.IcmsAliqRedBc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_ALIQ_RED_BC");

            entity.Property(e => e.IcmsBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_BC_VAL");

            entity.Property(e => e.IcmsCredSnPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_CRED_SN_PORC");

            entity.Property(e => e.IcmsCredSnVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_CRED_SN_VAL");

            entity.Property(e => e.IcmsCsosn)
                .HasMaxLength(3)
                .HasColumnName("ICMS_CSOSN");

            entity.Property(e => e.IcmsCst)
                .HasMaxLength(3)
                .HasColumnName("ICMS_CST");

            entity.Property(e => e.IcmsModbc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ICMS_MODBC");

            entity.Property(e => e.IcmsPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_PORC");

            entity.Property(e => e.IcmsVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_VAL");

            entity.Property(e => e.IcmsstBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSST_BC_VAL");

            entity.Property(e => e.IcmsstModbc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ICMSST_MODBC");

            entity.Property(e => e.IcmsstPmva)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSST_PMVA");

            entity.Property(e => e.IcmsstPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSST_PORC");

            entity.Property(e => e.IcmsstPred)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSST_PRED");

            entity.Property(e => e.IcmsstVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSST_VAL");

            entity.Property(e => e.IcmsstretBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSSTRET_BC_VAL");

            entity.Property(e => e.IcmsstretVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSSTRET_VAL");

            entity.Property(e => e.IiBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("II_BC_VAL");

            entity.Property(e => e.IiDespaduVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("II_DESPADU_VAL");

            entity.Property(e => e.IiIofVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("II_IOF_VAL");

            entity.Property(e => e.IiVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("II_VAL");

            entity.Property(e => e.Indtot)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INDTOT");

            entity.Property(e => e.Infoadprod)
                .HasMaxLength(400)
                .HasColumnName("INFOADPROD");

            entity.Property(e => e.Ipi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI");

            entity.Property(e => e.IpiBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI_BC_VAL");

            entity.Property(e => e.IpiCenq)
                .HasMaxLength(3)
                .HasColumnName("IPI_CENQ");

            entity.Property(e => e.IpiClenq)
                .HasMaxLength(5)
                .HasColumnName("IPI_CLENQ");

            entity.Property(e => e.IpiCnpjprod)
                .HasMaxLength(15)
                .HasColumnName("IPI_CNPJPROD");

            entity.Property(e => e.IpiCselo)
                .HasMaxLength(60)
                .HasColumnName("IPI_CSELO");

            entity.Property(e => e.IpiCst)
                .HasMaxLength(3)
                .HasColumnName("IPI_CST");

            entity.Property(e => e.IpiPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI_PORC");

            entity.Property(e => e.IpiQselo).HasColumnName("IPI_QSELO");

            entity.Property(e => e.IpiQunid)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI_QUNID");

            entity.Property(e => e.IpiVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI_VAL");

            entity.Property(e => e.IpiValunid)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI_VALUNID");

            entity.Property(e => e.IssqnAliqVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ISSQN_ALIQ_VAL");

            entity.Property(e => e.IssqnBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ISSQN_BC_VAL");

            entity.Property(e => e.IssqnClistserv).HasColumnName("ISSQN_CLISTSERV");

            entity.Property(e => e.IssqnCodmun).HasColumnName("ISSQN_CODMUN");

            entity.Property(e => e.IssqnVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ISSQN_VAL");

            entity.Property(e => e.LockPrecovenda)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LOCK_PRECOVENDA");

            entity.Property(e => e.Login)
                .HasMaxLength(80)
                .HasColumnName("LOGIN");

            entity.Property(e => e.LoteNum)
                .HasMaxLength(10)
                .HasColumnName("LOTE_NUM");

            entity.Property(e => e.LoteVencimento)
                .HasColumnType("DATE")
                .HasColumnName("LOTE_VENCIMENTO");

            entity.Property(e => e.Margem2)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM2");

            entity.Property(e => e.Margem3)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM3");

            entity.Property(e => e.Margem4)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM4");

            entity.Property(e => e.Margem5)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM5");

            entity.Property(e => e.Margemlucro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEMLUCRO");

            entity.Property(e => e.Motdesicms).HasColumnName("MOTDESICMS");

            entity.Property(e => e.NaoVende)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NAO_VENDE");

            entity.Property(e => e.Nitempedido).HasColumnName("NITEMPEDIDO");

            entity.Property(e => e.NomeCadastrado)
                .HasMaxLength(100)
                .HasColumnName("NOME_CADASTRADO");

            entity.Property(e => e.NomeXml)
                .HasMaxLength(100)
                .HasColumnName("NOME_XML");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.Origem)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ORIGEM");

            entity.Property(e => e.OutrosVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("OUTROS_VAL");

            entity.Property(e => e.Pfcp)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PFCP");

            entity.Property(e => e.Pfcpst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PFCPST");

            entity.Property(e => e.Pfcpstret)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PFCPSTRET");

            entity.Property(e => e.Pfcpufdest)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PFCPUFDEST");

            entity.Property(e => e.Picmsinter)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PICMSINTER");

            entity.Property(e => e.Picmsinterpart)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PICMSINTERPART");

            entity.Property(e => e.Picmsufdest)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PICMSUFDEST");

            entity.Property(e => e.PisAliqprodVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PIS_ALIQPROD_VAL");

            entity.Property(e => e.PisBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PIS_BC_VAL");

            entity.Property(e => e.PisCst)
                .HasMaxLength(3)
                .HasColumnName("PIS_CST");

            entity.Property(e => e.PisPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PIS_PORC");

            entity.Property(e => e.PisQuantBcprod)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PIS_QUANT_BCPROD");

            entity.Property(e => e.PisVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PIS_VAL");

            entity.Property(e => e.PisstAliqprodVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PISST_ALIQPROD_VAL");

            entity.Property(e => e.PisstBcVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PISST_BC_VAL");

            entity.Property(e => e.PisstPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PISST_PORC");

            entity.Property(e => e.PisstQuantBcprod)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PISST_QUANT_BCPROD");

            entity.Property(e => e.PisstVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PISST_VAL");

            entity.Property(e => e.PorcPerdaEstoque)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PORC_PERDA_ESTOQUE");

            entity.Property(e => e.Preco2)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO2");

            entity.Property(e => e.Preco3)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO3");

            entity.Property(e => e.Preco4)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO4");

            entity.Property(e => e.Preco5)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO5");

            entity.Property(e => e.Precocusto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTO");

            entity.Property(e => e.PrecocustoFiscal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTO_FISCAL");

            entity.Property(e => e.Precovenda)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOVENDA");

            entity.Property(e => e.Predbcst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PREDBCST");

            entity.Property(e => e.Pst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PST");

            entity.Property(e => e.QtTrib)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QT_TRIB");

            entity.Property(e => e.Quantidade)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QUANTIDADE");

            entity.Property(e => e.SeguroVal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("SEGURO_VAL");

            entity.Property(e => e.Sequencial).HasColumnName("SEQUENCIAL");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Tipocusto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPOCUSTO");

            entity.Property(e => e.TributosdespesasPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TRIBUTOSDESPESAS_PORC");

            entity.Property(e => e.TributosdespesasTipo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TRIBUTOSDESPESAS_TIPO");

            entity.Property(e => e.TributosdespesasValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TRIBUTOSDESPESAS_VALOR");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.UnTrib)
                .HasColumnType("CHAR(3) ")
                .HasColumnName("UN_TRIB");

            entity.Property(e => e.Undconversao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("UNDCONVERSAO");

            entity.Property(e => e.UnidCom)
                .HasColumnType("CHAR(3) ")
                .HasColumnName("UNID_COM");

            entity.Property(e => e.ValUnTrib)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VAL_UN_TRIB");

            entity.Property(e => e.Valortotal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALORTOTAL");

            entity.Property(e => e.Valorunitario)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALORUNITARIO");

            entity.Property(e => e.Vbcfcp)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VBCFCP");

            entity.Property(e => e.Vbcfcpst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VBCFCPST");

            entity.Property(e => e.Vbcfcpstret)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VBCFCPSTRET");

            entity.Property(e => e.Vbcufdest)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VBCUFDEST");

            entity.Property(e => e.Vfcp)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VFCP");

            entity.Property(e => e.Vfcpst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VFCPST");

            entity.Property(e => e.Vfcpstret)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VFCPSTRET");

            entity.Property(e => e.Vfcpufdest)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VFCPUFDEST");

            entity.Property(e => e.Vicmsdeson)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VICMSDESON");

            entity.Property(e => e.Vicmsufdest)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VICMSUFDEST");

            entity.Property(e => e.Vicmsufremet)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VICMSUFREMET");

            entity.Property(e => e.Xpedido)
                .HasMaxLength(50)
                .HasColumnName("XPEDIDO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaItemFiscal> entity);
    }
}
