// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EntradaGradeConfiguration : IEntityTypeConfiguration<EntradaGrade>
    {
        public void Configure(EntityTypeBuilder<EntradaGrade> entity)
        {
            entity.HasKey(e => new { e.CdNota, e.CdGrade, e.CdProduto });

            entity.ToTable("ENTRADA_GRADE");

            entity.HasIndex(e => new { e.CdNota, e.CdGrade, e.CdProduto }, "PK_ENTRADA_GRADE")
                .IsUnique();

            entity.Property(e => e.CdNota).HasColumnName("CD_NOTA");

            entity.Property(e => e.CdGrade).HasColumnName("CD_GRADE");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.CdGradeGrades).HasColumnName("CD_GRADE_GRADES");

            entity.Property(e => e.CdItem).HasColumnName("CD_ITEM");

            entity.Property(e => e.CodBarras)
                .HasMaxLength(14)
                .HasColumnName("COD_BARRAS");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.NmGrade)
                .HasMaxLength(20)
                .HasColumnName("NM_GRADE");

            entity.Property(e => e.Quantidade)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QUANTIDADE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EntradaGrade> entity);
    }
}
