// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EstoqueAlteracaomanualConfiguration : IEntityTypeConfiguration<EstoqueAlteracaomanual>
    {
        public void Configure(EntityTypeBuilder<EstoqueAlteracaomanual> entity)
        {
            entity.ToTable("ESTOQUE_ALTERACAOMANUAL");

            entity.HasIndex(e => e.Id, "PK_ESTOQUE_ALTERACAOMANUAL")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.CdDeposito).HasColumnName("CD_DEPOSITO");

            entity.Property(e => e.CdGrade).HasColumnName("CD_GRADE");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.DataHora).HasColumnName("DATA_HORA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EstoqueAlteracaomanual> entity);
    }
}
