// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EstoqueDataConfiguration : IEntityTypeConfiguration<EstoqueData>
    {
        public void Configure(EntityTypeBuilder<EstoqueData> entity)
        {
            entity.HasKey(e => new { e.CdProduto, e.Data });

            entity.ToTable("ESTOQUE_DATA");

            entity.HasIndex(e => new { e.Data, e.CdProduto }, "PK_ESTOQUE_DATA")
                .IsUnique();

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Data).HasColumnName("DATA");

            entity.Property(e => e.Estoque)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ESTOQUE");

            entity.Property(e => e.Precocusto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTO");

            entity.Property(e => e.TotalItem)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TOTAL_ITEM");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EstoqueData> entity);
    }
}
