// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class EstoqueConfiguration : IEntityTypeConfiguration<Estoque>
    {
        public void Configure(EntityTypeBuilder<Estoque> entity)
        {
            entity.HasKey(e => new { e.CdProduto, e.CdGrade, e.CdDeposito });

            entity.ToTable("ESTOQUE");

            entity.HasIndex(e => new { e.CdGrade, e.CdProduto, e.CdDeposito }, "PK_ESTOQUE")
                .IsUnique();

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.CdGrade).HasColumnName("CD_GRADE");

            entity.Property(e => e.CdDeposito).HasColumnName("CD_DEPOSITO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtExpPalm).HasColumnName("DT_EXP_PALM");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.Espelho)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ESPELHO");

            entity.Property(e => e.Estoqueanterior)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ESTOQUEANTERIOR");

            entity.Property(e => e.Estoqueatual)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ESTOQUEATUAL");

            entity.Property(e => e.Loginultimacorrecao)
                .HasMaxLength(80)
                .HasColumnName("LOGINULTIMACORRECAO");

            entity.Property(e => e.Loginultimaentrada)
                .HasMaxLength(80)
                .HasColumnName("LOGINULTIMAENTRADA");

            entity.Property(e => e.Loginultimasaida)
                .HasMaxLength(80)
                .HasColumnName("LOGINULTIMASAIDA");

            entity.Property(e => e.Pesoanterior)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOANTERIOR");

            entity.Property(e => e.Pesoatual)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOATUAL");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Ultimacorrecao).HasColumnName("ULTIMACORRECAO");

            entity.Property(e => e.Ultimaentrada).HasColumnName("ULTIMAENTRADA");

            entity.Property(e => e.Ultimasaida).HasColumnName("ULTIMASAIDA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Estoque> entity);
    }
}
