// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class FornecedoresConfiguration : IEntityTypeConfiguration<Fornecedores>
    {
        public void Configure(EntityTypeBuilder<Fornecedores> entity)
        {
            entity.HasKey(e => e.CdFornecedor);

            entity.ToTable("FORNECEDORES");

            entity.HasIndex(e => e.NmFornecedor, "FORNECEDORES_IDX1");

            entity.HasIndex(e => e.Nomefantasia, "FORNECEDORES_IDX2");

            entity.HasIndex(e => e.Inativo, "IDX_FORNINATIVO");

            entity.HasIndex(e => e.CdFornecedor, "PK_FORNECEDORES")
                .IsUnique();

            entity.Property(e => e.CdFornecedor).HasColumnName("CD_FORNECEDOR");

            entity.Property(e => e.CnaeFiscal)
                .HasMaxLength(10)
                .HasColumnName("CNAE_FISCAL");

            entity.Property(e => e.ContEmail)
                .HasMaxLength(100)
                .HasColumnName("CONT_EMAIL");

            entity.Property(e => e.ContTelefone)
                .HasMaxLength(70)
                .HasColumnName("CONT_TELEFONE");

            entity.Property(e => e.Contato)
                .HasMaxLength(40)
                .HasColumnName("CONTATO");

            entity.Property(e => e.CpContabancaria).HasColumnName("CP_CONTABANCARIA");

            entity.Property(e => e.CpPeriodicidade).HasColumnName("CP_PERIODICIDADE");

            entity.Property(e => e.CpPeriodmensal)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CP_PERIODMENSAL");

            entity.Property(e => e.CpQtdparcelas).HasColumnName("CP_QTDPARCELAS");

            entity.Property(e => e.CpUltimotipodoc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CP_ULTIMOTIPODOC");

            entity.Property(e => e.CpfCnpj)
                .HasMaxLength(18)
                .HasColumnName("CPF_CNPJ");

            entity.Property(e => e.Crt).HasColumnName("CRT");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DiasTempoEntrega).HasColumnName("DIAS_TEMPO_ENTREGA");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtExpWeb).HasColumnName("DT_EXP_WEB");

            entity.Property(e => e.DtFundacao)
                .HasColumnType("DATE")
                .HasColumnName("DT_FUNDACAO");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.DtUltimacompra)
                .HasColumnType("DATE")
                .HasColumnName("DT_ULTIMACOMPRA");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("EMAIL");

            entity.Property(e => e.EndBairro)
                .HasMaxLength(35)
                .HasColumnName("END_BAIRRO");

            entity.Property(e => e.EndCdMunicipio).HasColumnName("END_CD_MUNICIPIO");

            entity.Property(e => e.EndCdPais).HasColumnName("END_CD_PAIS");

            entity.Property(e => e.EndCep)
                .HasMaxLength(9)
                .HasColumnName("END_CEP");

            entity.Property(e => e.EndComplemento)
                .HasMaxLength(60)
                .HasColumnName("END_COMPLEMENTO");

            entity.Property(e => e.EndLogradouro)
                .HasMaxLength(60)
                .HasColumnName("END_LOGRADOURO");

            entity.Property(e => e.EndNmMunicipio)
                .HasMaxLength(35)
                .HasColumnName("END_NM_MUNICIPIO");

            entity.Property(e => e.EndNumero)
                .HasMaxLength(20)
                .HasColumnName("END_NUMERO");

            entity.Property(e => e.EndReferencia)
                .HasMaxLength(200)
                .HasColumnName("END_REFERENCIA");

            entity.Property(e => e.EndUf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("END_UF");

            entity.Property(e => e.Exportar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR");

            entity.Property(e => e.Fax)
                .HasMaxLength(70)
                .HasColumnName("FAX");

            entity.Property(e => e.IeIsento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IE_ISENTO");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.InscMunicipal)
                .HasMaxLength(15)
                .HasColumnName("INSC_MUNICIPAL");

            entity.Property(e => e.Lembrete)
                .HasMaxLength(400)
                .HasColumnName("LEMBRETE");

            entity.Property(e => e.NmFornecedor)
                .HasMaxLength(100)
                .HasColumnName("NM_FORNECEDOR");

            entity.Property(e => e.Nomefantasia)
                .HasMaxLength(40)
                .HasColumnName("NOMEFANTASIA");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.Pessoa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PESSOA");

            entity.Property(e => e.Refbanco)
                .HasMaxLength(400)
                .HasColumnName("REFBANCO");

            entity.Property(e => e.RgIe)
                .HasMaxLength(15)
                .HasColumnName("RG_IE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Suframa)
                .HasMaxLength(10)
                .HasColumnName("SUFRAMA");

            entity.Property(e => e.Telefone)
                .HasMaxLength(70)
                .HasColumnName("TELEFONE");

            entity.Property(e => e.Transporte)
                .HasMaxLength(200)
                .HasColumnName("TRANSPORTE");

            entity.Property(e => e.TransporteTel)
                .HasMaxLength(70)
                .HasColumnName("TRANSPORTE_TEL");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Website)
                .HasMaxLength(50)
                .HasColumnName("WEBSITE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Fornecedores> entity);
    }
}
