// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class FotosTransicaoConfiguration : IEntityTypeConfiguration<FotosTransicao>
    {
        public void Configure(EntityTypeBuilder<FotosTransicao> entity)
        {
            entity.HasKey(e => e.CdFoto);

            entity.ToTable("FOTOS_TRANSICAO");

            entity.HasIndex(e => e.CdFoto, "PK_FOTOS_TRANSICAO")
                .IsUnique();

            entity.Property(e => e.CdFoto).HasColumnName("CD_FOTO");

            entity.Property(e => e.Foto).HasColumnName("FOTO");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FotosTransicao> entity);
    }
}
