// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class GradesConfiguration : IEntityTypeConfiguration<Grades>
    {
        public void Configure(EntityTypeBuilder<Grades> entity)
        {
            entity.HasKey(e => new { e.CdProduto, e.CdGrade });

            entity.ToTable("GRADES");

            entity.HasIndex(e => e.CodBarras, "GRADES_IDX1");

            entity.HasIndex(e => e.CdGrade, "GRADES_IDX2");

            entity.HasIndex(e => new { e.CdGrade, e.CdProduto }, "PK_GRADES")
                .IsUnique();

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.CdGrade).HasColumnName("CD_GRADE");

            entity.Property(e => e.CodBarras)
                .HasMaxLength(14)
                .HasColumnName("COD_BARRAS");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtExpWeb).HasColumnName("DT_EXP_WEB");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincMarketplace).HasColumnName("DT_SINC_MARKETPLACE");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.IntegraMarketplace)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INTEGRA_MARKETPLACE");

            entity.Property(e => e.NmGrade)
                .HasMaxLength(20)
                .HasColumnName("NM_GRADE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TrayId).HasColumnName("TRAY_ID");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Grades> entity);
    }
}
