// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class GridsConfiguration : IEntityTypeConfiguration<Grids>
    {
        public void Configure(EntityTypeBuilder<Grids> entity)
        {
            entity.ToTable("GRIDS");

            entity.HasIndex(e => e.Id, "RDB$PRIMARY9")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.GridArquivoLayout)
                .IsRequired()
                .HasColumnName("GRID_ARQUIVO_LAYOUT");

            entity.Property(e => e.NmGrid)
                .IsRequired()
                .HasMaxLength(400)
                .HasColumnName("NM_GRID");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Grids> entity);
    }
}
