// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class GruposProdutosConfiguration : IEntityTypeConfiguration<GruposProdutos>
    {
        public void Configure(EntityTypeBuilder<GruposProdutos> entity)
        {
            entity.HasKey(e => e.CdGrupo);

            entity.ToTable("GRUPOS_PRODUTOS");

            entity.HasIndex(e => e.CdPai, "GRUPOS_PRODUTOS_IDX1");

            entity.HasIndex(e => e.CdGrupo, "PK_GRUPOS_PRODUTOS")
                .IsUnique();

            entity.Property(e => e.CdGrupo).HasColumnName("CD_GRUPO");

            entity.Property(e => e.CdPai).HasColumnName("CD_PAI");

            entity.Property(e => e.CdSetor).HasColumnName("CD_SETOR");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.Descricao)
                .HasMaxLength(80)
                .HasColumnName("DESCRICAO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.PermiteVendaEstZerado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITE_VENDA_EST_ZERADO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.UsuarioId).HasColumnName("USUARIO_ID");

            entity.Property(e => e.UsuarioNome)
                .HasMaxLength(80)
                .HasColumnName("USUARIO_NOME");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GruposProdutos> entity);
    }
}
