// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class GruposPromocionaisConfiguration : IEntityTypeConfiguration<GruposPromocionais>
    {
        public void Configure(EntityTypeBuilder<GruposPromocionais> entity)
        {
            entity.HasKey(e => e.CdGrupo);

            entity.ToTable("GRUPOS_PROMOCIONAIS");

            entity.HasIndex(e => e.CdGrupo, "PK_GRUPOS_PROMOCIONAIS")
                .IsUnique();

            entity.Property(e => e.CdGrupo).HasColumnName("CD_GRUPO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.NmGrupo)
                .HasMaxLength(80)
                .HasColumnName("NM_GRUPO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GruposPromocionais> entity);
    }
}
