// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceCanceladaConfiguration : IEntityTypeConfiguration<NfceCancelada>
    {
        public void Configure(EntityTypeBuilder<NfceCancelada> entity)
        {
            entity.HasKey(e => new { e.NumNfce, e.SerieNfce, e.NumTerminal, e.CdEmpresa });

            entity.ToTable("NFCE_CANCELADA");

            entity.HasIndex(e => new { e.NumNfce, e.NumTerminal, e.SerieNfce, e.CdEmpresa }, "PK_NFCE_CANCELADA")
                .IsUnique();

            entity.Property(e => e.NumNfce).HasColumnName("NUM_NFCE");

            entity.Property(e => e.SerieNfce).HasColumnName("SERIE_NFCE");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.ArqXmlProc).HasColumnName("ARQ_XML_PROC");

            entity.Property(e => e.Chave)
                .HasMaxLength(50)
                .HasColumnName("CHAVE");

            entity.Property(e => e.Cstat).HasColumnName("CSTAT");

            entity.Property(e => e.Cuf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("CUF");

            entity.Property(e => e.DhRecbto).HasColumnName("DH_RECBTO");

            entity.Property(e => e.Justificativa)
                .HasMaxLength(150)
                .HasColumnName("JUSTIFICATIVA");

            entity.Property(e => e.Motivo)
                .HasMaxLength(150)
                .HasColumnName("MOTIVO");

            entity.Property(e => e.Protocolo)
                .HasMaxLength(200)
                .HasColumnName("PROTOCOLO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TpAmb)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TP_AMB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceCancelada> entity);
    }
}
