// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceInutilizadaConfiguration : IEntityTypeConfiguration<NfceInutilizada>
    {
        public void Configure(EntityTypeBuilder<NfceInutilizada> entity)
        {
            entity.HasKey(e => e.CdNfceInutilizada);

            entity.ToTable("NFCE_INUTILIZADA");

            entity.HasIndex(e => e.CdNfceInutilizada, "PK_NFCE_INUTILIZADA")
                .IsUnique();

            entity.Property(e => e.CdNfceInutilizada).HasColumnName("CD_NFCE_INUTILIZADA");

            entity.Property(e => e.Ano).HasColumnName("ANO");

            entity.Property(e => e.ArqXml).HasColumnName("ARQ_XML");

            entity.Property(e => e.Cpfcnpj)
                .HasMaxLength(18)
                .HasColumnName("CPFCNPJ");

            entity.Property(e => e.Cstat).HasColumnName("CSTAT");

            entity.Property(e => e.Cuf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("CUF");

            entity.Property(e => e.DhRecbto).HasColumnName("DH_RECBTO");

            entity.Property(e => e.Justificativa)
                .HasMaxLength(150)
                .HasColumnName("JUSTIFICATIVA");

            entity.Property(e => e.Modelo).HasColumnName("MODELO");

            entity.Property(e => e.Motivo)
                .HasMaxLength(150)
                .HasColumnName("MOTIVO");

            entity.Property(e => e.NumFin).HasColumnName("NUM_FIN");

            entity.Property(e => e.NumIni).HasColumnName("NUM_INI");

            entity.Property(e => e.Protocolo)
                .HasMaxLength(60)
                .HasColumnName("PROTOCOLO");

            entity.Property(e => e.Serie).HasColumnName("SERIE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TpAmb)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TP_AMB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceInutilizada> entity);
    }
}
