// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceConfigConfiguration : IEntityTypeConfiguration<NfceConfig>
    {
        public void Configure(EntityTypeBuilder<NfceConfig> entity)
        {
            entity.HasKey(e => e.CdCertificado);

            entity.ToTable("NFCE_CONFIG");

            entity.HasIndex(e => e.CdCertificado, "PK_NFCE_CONFIG")
                .IsUnique();

            entity.Property(e => e.CdCertificado).HasColumnName("CD_CERTIFICADO");

            entity.Property(e => e.Autocontingencia)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("AUTOCONTINGENCIA");

            entity.Property(e => e.Danfe)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DANFE");

            entity.Property(e => e.DesabilitarBotaoNfce)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESABILITAR_BOTAO_NFCE");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.EmailAguardaenvio)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMAIL_AGUARDAENVIO");

            entity.Property(e => e.EmailAssunto)
                .HasMaxLength(200)
                .HasColumnName("EMAIL_ASSUNTO");

            entity.Property(e => e.EmailAutoenvia)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMAIL_AUTOENVIA");

            entity.Property(e => e.EmailHost)
                .HasMaxLength(30)
                .HasColumnName("EMAIL_HOST");

            entity.Property(e => e.EmailMensagem)
                .HasMaxLength(2000)
                .HasColumnName("EMAIL_MENSAGEM");

            entity.Property(e => e.EmailPorta)
                .HasMaxLength(10)
                .HasColumnName("EMAIL_PORTA");

            entity.Property(e => e.EmailSenha)
                .HasMaxLength(30)
                .HasColumnName("EMAIL_SENHA");

            entity.Property(e => e.EmailSsl)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMAIL_SSL");

            entity.Property(e => e.EmailUsuario)
                .HasMaxLength(30)
                .HasColumnName("EMAIL_USUARIO");

            entity.Property(e => e.EmiteGer)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMITE_GER");

            entity.Property(e => e.EmitePdv)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMITE_PDV");

            entity.Property(e => e.ExibeQrcode)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBE_QRCODE");

            entity.Property(e => e.ExibirImpostoItem)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXIBIR_IMPOSTO_ITEM");

            entity.Property(e => e.ExportarDia).HasColumnName("EXPORTAR_DIA");

            entity.Property(e => e.ExportarEmailPadrao)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR_EMAIL_PADRAO");

            entity.Property(e => e.ExportarEmails)
                .IsRequired()
                .HasMaxLength(400)
                .HasColumnName("EXPORTAR_EMAILS");

            entity.Property(e => e.ExportarPorEmail)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR_POR_EMAIL");

            entity.Property(e => e.ExportarRelatorio)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR_RELATORIO");

            entity.Property(e => e.ExportarVerificarXml)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR_VERIFICAR_XML");

            entity.Property(e => e.Formaemissao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("FORMAEMISSAO");

            entity.Property(e => e.ImprimeSemperguntar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMPRIME_SEMPERGUNTAR");

            entity.Property(e => e.ImprimirObsPedido)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMPRIMIR_OBS_PEDIDO");

            entity.Property(e => e.ImprimirPdf)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMPRIMIR_PDF");

            entity.Property(e => e.ImprimirSaldoDivida)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMPRIMIR_SALDO_DIVIDA");

            entity.Property(e => e.ImprimirTipoPreco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMPRIMIR_TIPO_PRECO");

            entity.Property(e => e.LembrarAuto)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LEMBRAR_AUTO");

            entity.Property(e => e.Logomarca).HasColumnName("LOGOMARCA");

            entity.Property(e => e.ProxyHost)
                .HasMaxLength(30)
                .HasColumnName("PROXY_HOST");

            entity.Property(e => e.ProxyPorta)
                .HasMaxLength(10)
                .HasColumnName("PROXY_PORTA");

            entity.Property(e => e.ProxySenha)
                .HasMaxLength(30)
                .HasColumnName("PROXY_SENHA");

            entity.Property(e => e.ProxyUsuario)
                .HasMaxLength(30)
                .HasColumnName("PROXY_USUARIO");

            entity.Property(e => e.SalvarPdf)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SALVAR_PDF");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TipoImpPadrao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_IMP_PADRAO");

            entity.Property(e => e.UltimaExportacaoData)
                .HasColumnType("DATE")
                .HasColumnName("ULTIMA_EXPORTACAO_DATA");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.WsAmbiente)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("WS_AMBIENTE");

            entity.Property(e => e.WsUf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("WS_UF");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceConfig> entity);
    }
}
