// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceConfigLocalConfiguration : IEntityTypeConfiguration<NfceConfigLocal>
    {
        public void Configure(EntityTypeBuilder<NfceConfigLocal> entity)
        {
            entity.HasKey(e => e.NumTerminal);

            entity.ToTable("NFCE_CONFIG_LOCAL");

            entity.HasIndex(e => e.NumTerminal, "PK_NFCE_CONFIG_LOCAL")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.CdCertificado).HasColumnName("CD_CERTIFICADO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.EmissaoExtraordinaria)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMISSAO_EXTRAORDINARIA");

            entity.Property(e => e.EmissaoExtraordinariaIcms)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMISSAO_EXTRAORDINARIA_ICMS");

            entity.Property(e => e.EmissaoExtraordinariaNcm)
                .HasMaxLength(19999)
                .HasColumnName("EMISSAO_EXTRAORDINARIA_NCM");

            entity.Property(e => e.EmiteGer)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMITE_GER");

            entity.Property(e => e.EmitePdv)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMITE_PDV");

            entity.Property(e => e.EmitePedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMITE_PEDIDO");

            entity.Property(e => e.ExportarCaminho)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("EXPORTAR_CAMINHO");

            entity.Property(e => e.FormatoImpressao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("FORMATO_IMPRESSAO");

            entity.Property(e => e.IdDfeSerieNumeracao).HasColumnName("ID_DFE_SERIE_NUMERACAO");

            entity.Property(e => e.ImpAtivarguilhotina)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_ATIVARGUILHOTINA");

            entity.Property(e => e.ImpBobina)
                .HasMaxLength(20)
                .HasColumnName("IMP_BOBINA");

            entity.Property(e => e.ImpFormatoitem).HasColumnName("IMP_FORMATOITEM");

            entity.Property(e => e.ImpIndiceCrediario)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_INDICE_CREDIARIO");

            entity.Property(e => e.ImpLogoFatorx).HasColumnName("IMP_LOGO_FATORX");

            entity.Property(e => e.ImpLogoFatory).HasColumnName("IMP_LOGO_FATORY");

            entity.Property(e => e.ImpLogoImprimir)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_LOGO_IMPRIMIR");

            entity.Property(e => e.ImpLogoKc1).HasColumnName("IMP_LOGO_KC1");

            entity.Property(e => e.ImpLogoKc2).HasColumnName("IMP_LOGO_KC2");

            entity.Property(e => e.ImpMargemesquerda).HasColumnName("IMP_MARGEMESQUERDA");

            entity.Property(e => e.ImpPagCodigo).HasColumnName("IMP_PAG_CODIGO");

            entity.Property(e => e.ImpPorta)
                .HasMaxLength(40)
                .HasColumnName("IMP_PORTA");

            entity.Property(e => e.ImpQrcodelateral)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_QRCODELATERAL");

            entity.Property(e => e.ImpSaltolinha).HasColumnName("IMP_SALTOLINHA");

            entity.Property(e => e.ImpTipoimpwin)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_TIPOIMPWIN");

            entity.Property(e => e.ImpViaconsumidor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMP_VIACONSUMIDOR");

            entity.Property(e => e.ImpWin)
                .HasMaxLength(200)
                .HasColumnName("IMP_WIN");

            entity.Property(e => e.Numeracao).HasColumnName("NUMERACAO");

            entity.Property(e => e.NumeracaoAnterior).HasColumnName("NUMERACAO_ANTERIOR");

            entity.Property(e => e.Numeracaopdv).HasColumnName("NUMERACAOPDV");

            entity.Property(e => e.NumeracaopdvAnterior).HasColumnName("NUMERACAOPDV_ANTERIOR");

            entity.Property(e => e.PathCaminhoPadrao)
                .HasMaxLength(200)
                .HasColumnName("PATH_CAMINHO_PADRAO");

            entity.Property(e => e.PreVisualizacao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PRE_VISUALIZACAO");

            entity.Property(e => e.QuebraLinhaDetalhamento)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("QUEBRA_LINHA_DETALHAMENTO");

            entity.Property(e => e.Serie).HasColumnName("SERIE");

            entity.Property(e => e.SerieAnterior).HasColumnName("SERIE_ANTERIOR");

            entity.Property(e => e.Seriepdv).HasColumnName("SERIEPDV");

            entity.Property(e => e.SeriepdvAnterior).HasColumnName("SERIEPDV_ANTERIOR");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TokenCsc)
                .HasMaxLength(50)
                .HasColumnName("TOKEN_CSC");

            entity.Property(e => e.TokenId)
                .HasMaxLength(20)
                .HasColumnName("TOKEN_ID");

            entity.Property(e => e.UltNumHomolog).HasColumnName("ULT_NUM_HOMOLOG");

            entity.Property(e => e.UltNumProd).HasColumnName("ULT_NUM_PROD");

            entity.Property(e => e.UltNumpdvProd).HasColumnName("ULT_NUMPDV_PROD");

            entity.Property(e => e.UltSerieHomolog).HasColumnName("ULT_SERIE_HOMOLOG");

            entity.Property(e => e.UltSerieProd).HasColumnName("ULT_SERIE_PROD");

            entity.Property(e => e.UltSeriepdvProd).HasColumnName("ULT_SERIEPDV_PROD");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceConfigLocal> entity);
    }
}
