// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceCanceladaXmlConfiguration : IEntityTypeConfiguration<NfceCanceladaXml>
    {
        public void Configure(EntityTypeBuilder<NfceCanceladaXml> entity)
        {
            entity.HasKey(e => new { e.NumNfce, e.SerieNfce, e.NumTerminal, e.CdEmpresa });

            entity.ToTable("NFCE_CANCELADA_XML");

            entity.HasIndex(e => new { e.NumNfce, e.NumTerminal, e.SerieNfce, e.CdEmpresa }, "PK_NFCE_CANCELADA_XML")
                .IsUnique();

            entity.Property(e => e.NumNfce).HasColumnName("NUM_NFCE");

            entity.Property(e => e.SerieNfce).HasColumnName("SERIE_NFCE");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.ArqXmlProc).HasColumnName("ARQ_XML_PROC");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceCanceladaXml> entity);
    }
}
