// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfcePedidoItemConfiguration : IEntityTypeConfiguration<NfcePedidoItem>
    {
        public void Configure(EntityTypeBuilder<NfcePedidoItem> entity)
        {
            entity.HasKey(e => new { e.NumNfce, e.SerieNfce, e.NumTerminal, e.CdEmpresa, e.Nitem });

            entity.ToTable("NFCE_PEDIDO_ITEM");

            entity.HasIndex(e => new { e.NumNfce, e.NumTerminal, e.SerieNfce, e.Nitem, e.CdEmpresa }, "PK_NFCE_PEDIDO_ITEM")
                .IsUnique();

            entity.Property(e => e.NumNfce).HasColumnName("NUM_NFCE");

            entity.Property(e => e.SerieNfce).HasColumnName("SERIE_NFCE");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.Nitem).HasColumnName("NITEM");

            entity.Property(e => e.Ambiente)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("AMBIENTE");

            entity.Property(e => e.Cean)
                .HasMaxLength(14)
                .HasColumnName("CEAN");

            entity.Property(e => e.Ceantrib)
                .HasMaxLength(14)
                .HasColumnName("CEANTRIB");

            entity.Property(e => e.Cfop)
                .HasMaxLength(6)
                .HasColumnName("CFOP");

            entity.Property(e => e.Cprod)
                .HasMaxLength(30)
                .HasColumnName("CPROD");

            entity.Property(e => e.Csosn)
                .HasMaxLength(4)
                .HasColumnName("CSOSN");

            entity.Property(e => e.Cst)
                .HasMaxLength(2)
                .HasColumnName("CST");

            entity.Property(e => e.DtEmissao).HasColumnName("DT_EMISSAO");

            entity.Property(e => e.Extipi)
                .HasMaxLength(10)
                .HasColumnName("EXTIPI");

            entity.Property(e => e.Icmstot)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMSTOT");

            entity.Property(e => e.Infadprod)
                .HasMaxLength(400)
                .HasColumnName("INFADPROD");

            entity.Property(e => e.Modbc)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("MODBC");

            entity.Property(e => e.Modbcst)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("MODBCST");

            entity.Property(e => e.Ncm)
                .HasMaxLength(12)
                .HasColumnName("NCM");

            entity.Property(e => e.Orig)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ORIG");

            entity.Property(e => e.Picms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PICMS");

            entity.Property(e => e.Picmsst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PICMSST");

            entity.Property(e => e.Pmvast)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PMVAST");

            entity.Property(e => e.Predbc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PREDBC");

            entity.Property(e => e.Predbcst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PREDBCST");

            entity.Property(e => e.Qcom)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QCOM");

            entity.Property(e => e.Qtrib)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QTRIB");

            entity.Property(e => e.Ucom)
                .HasMaxLength(4)
                .HasColumnName("UCOM");

            entity.Property(e => e.Utrib)
                .HasMaxLength(4)
                .HasColumnName("UTRIB");

            entity.Property(e => e.Vbc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VBC");

            entity.Property(e => e.Vbcst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VBCST");

            entity.Property(e => e.Vdesc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VDESC");

            entity.Property(e => e.Vfrete)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VFRETE");

            entity.Property(e => e.Vicms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VICMS");

            entity.Property(e => e.Vicmsst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VICMSST");

            entity.Property(e => e.Voutro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VOUTRO");

            entity.Property(e => e.Vprod)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VPROD");

            entity.Property(e => e.Vseg)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VSEG");

            entity.Property(e => e.Vtottrib)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VTOTTRIB");

            entity.Property(e => e.Vuncom)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VUNCOM");

            entity.Property(e => e.Vuntrib)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VUNTRIB");

            entity.Property(e => e.Xprod)
                .HasMaxLength(100)
                .HasColumnName("XPROD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfcePedidoItem> entity);
    }
}
