// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfcePedidoConfiguration : IEntityTypeConfiguration<NfcePedido>
    {
        public void Configure(EntityTypeBuilder<NfcePedido> entity)
        {
            entity.HasKey(e => new { e.NumNfce, e.SerieNfce, e.NumTerminal, e.CdEmpresa, e.Ambiente });

            entity.ToTable("NFCE_PEDIDO");

            entity.HasIndex(e => new { e.Ambiente, e.NumDocumento, e.DtEmissao }, "NFCE_PEDIDO_IDX1");

            entity.HasIndex(e => new { e.Ambiente, e.NumNfce, e.NumTerminal, e.SerieNfce, e.CdEmpresa }, "PK_NFCE_PEDIDO")
                .IsUnique();

            entity.Property(e => e.NumNfce).HasColumnName("NUM_NFCE");

            entity.Property(e => e.SerieNfce).HasColumnName("SERIE_NFCE");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.Ambiente)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("AMBIENTE");

            entity.Property(e => e.ArqXmlNfce).HasColumnName("ARQ_XML_NFCE");

            entity.Property(e => e.CdCertificado).HasColumnName("CD_CERTIFICADO");

            entity.Property(e => e.CdCliente).HasColumnName("CD_CLIENTE");

            entity.Property(e => e.CdMensagem).HasColumnName("CD_MENSAGEM");

            entity.Property(e => e.CdVendedor).HasColumnName("CD_VENDEDOR");

            entity.Property(e => e.ChaveNfce)
                .HasMaxLength(200)
                .HasColumnName("CHAVE_NFCE");

            entity.Property(e => e.CodSituacao)
                .HasMaxLength(2)
                .HasColumnName("COD_SITUACAO");

            entity.Property(e => e.ContingenciaDatahora).HasColumnName("CONTINGENCIA_DATAHORA");

            entity.Property(e => e.ContingenciaEnviando).HasColumnName("CONTINGENCIA_ENVIANDO");

            entity.Property(e => e.ContingenciaJust)
                .HasMaxLength(200)
                .HasColumnName("CONTINGENCIA_JUST");

            entity.Property(e => e.DestCpfcnpj)
                .HasMaxLength(18)
                .HasColumnName("DEST_CPFCNPJ");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtEmissao).HasColumnName("DT_EMISSAO");

            entity.Property(e => e.DtEmissaoSped)
                .HasMaxLength(10)
                .HasColumnName("DT_EMISSAO_SPED");

            entity.Property(e => e.DtRecebimento).HasColumnName("DT_RECEBIMENTO");

            entity.Property(e => e.EmitCpfcnpj)
                .HasMaxLength(18)
                .HasColumnName("EMIT_CPFCNPJ");

            entity.Property(e => e.Extraordinaria)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXTRAORDINARIA");

            entity.Property(e => e.Flag)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("FLAG");

            entity.Property(e => e.IdLocal).HasColumnName("ID_LOCAL");

            entity.Property(e => e.InfAdfisco)
                .HasMaxLength(2000)
                .HasColumnName("INF_ADFISCO");

            entity.Property(e => e.InfCpl)
                .HasMaxLength(5000)
                .HasColumnName("INF_CPL");

            entity.Property(e => e.Inutilizada)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INUTILIZADA");

            entity.Property(e => e.Mensagem)
                .HasMaxLength(100)
                .HasColumnName("MENSAGEM");

            entity.Property(e => e.ModeloDoc)
                .HasMaxLength(2)
                .HasColumnName("MODELO_DOC");

            entity.Property(e => e.NumDocumento).HasColumnName("NUM_DOCUMENTO");

            entity.Property(e => e.NumDocumentoAux).HasColumnName("NUM_DOCUMENTO_AUX");

            entity.Property(e => e.NumItens).HasColumnName("NUM_ITENS");

            entity.Property(e => e.NumTerminalEnviando).HasColumnName("NUM_TERMINAL_ENVIANDO");

            entity.Property(e => e.ProtAutorizacao)
                .HasMaxLength(40)
                .HasColumnName("PROT_AUTORIZACAO");

            entity.Property(e => e.Sincronizado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZADO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Status)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("STATUS");

            entity.Property(e => e.TipoEmissao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_EMISSAO");

            entity.Property(e => e.TipoFrete)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_FRETE");

            entity.Property(e => e.TipoOperacao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_OPERACAO");

            entity.Property(e => e.TipoPgto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_PGTO");

            entity.Property(e => e.TokenCsc)
                .HasMaxLength(50)
                .HasColumnName("TOKEN_CSC");

            entity.Property(e => e.TokenId)
                .HasMaxLength(20)
                .HasColumnName("TOKEN_ID");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.VersaoApp)
                .HasMaxLength(200)
                .HasColumnName("VERSAO_APP");

            entity.Property(e => e.VlAbatNt)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_ABAT_NT");

            entity.Property(e => e.VlBcIcms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_BC_ICMS");

            entity.Property(e => e.VlBcIcmsSt)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_BC_ICMS_ST");

            entity.Property(e => e.VlCofins)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_COFINS");

            entity.Property(e => e.VlCofinsSt)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_COFINS_ST");

            entity.Property(e => e.VlIcms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_ICMS");

            entity.Property(e => e.VlIcmsSt)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_ICMS_ST");

            entity.Property(e => e.VlIpi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_IPI");

            entity.Property(e => e.VlPis)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_PIS");

            entity.Property(e => e.VlPisSt)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_PIS_ST");

            entity.Property(e => e.VlTotalAcres)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_TOTAL_ACRES");

            entity.Property(e => e.VlTotalDesc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_TOTAL_DESC");

            entity.Property(e => e.VlTotalFrete)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_TOTAL_FRETE");

            entity.Property(e => e.VlTotalMercadorias)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_TOTAL_MERCADORIAS");

            entity.Property(e => e.VlTotalNfce)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_TOTAL_NFCE");

            entity.Property(e => e.VlTotalSeguro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VL_TOTAL_SEGURO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfcePedido> entity);
    }
}
