// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceXmlConfiguration : IEntityTypeConfiguration<NfceXml>
    {
        public void Configure(EntityTypeBuilder<NfceXml> entity)
        {
            entity.HasKey(e => new { e.NumNfce, e.SerieNfce, e.NumTerminal, e.CdEmpresa });

            entity.ToTable("NFCE_XML");

            entity.HasIndex(e => new { e.NumNfce, e.NumTerminal, e.SerieNfce, e.CdEmpresa }, "PK_NFCE_XML")
                .IsUnique();

            entity.Property(e => e.NumNfce).HasColumnName("NUM_NFCE");

            entity.Property(e => e.SerieNfce).HasColumnName("SERIE_NFCE");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.ArqXml).HasColumnName("ARQ_XML");

            entity.Property(e => e.Compactado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("COMPACTADO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.EnviadaTecnospeed)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ENVIADA_TECNOSPEED");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceXml> entity);
    }
}
