// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceContingControllerConfiguration : IEntityTypeConfiguration<NfceContingController>
    {
        public void Configure(EntityTypeBuilder<NfceContingController> entity)
        {
            entity.ToTable("NFCE_CONTING_CONTROLLER");

            entity.HasIndex(e => e.Id, "PK_NFCE_CONTING_CONTROLLER")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.ContingenciaChave)
                .HasMaxLength(200)
                .HasColumnName("CONTINGENCIA_CHAVE");

            entity.Property(e => e.Data).HasColumnName("DATA");

            entity.Property(e => e.ErroChave)
                .HasMaxLength(200)
                .HasColumnName("ERRO_CHAVE");

            entity.Property(e => e.ErroNumero).HasColumnName("ERRO_NUMERO");

            entity.Property(e => e.ErroSerie).HasColumnName("ERRO_SERIE");

            entity.Property(e => e.ErroXml).HasColumnName("ERRO_XML");

            entity.Property(e => e.NumDocumento).HasColumnName("NUM_DOCUMENTO");

            entity.Property(e => e.Origem)
                .HasMaxLength(4)
                .HasColumnName("ORIGEM");

            entity.Property(e => e.ProximaConsulta).HasColumnName("PROXIMA_CONSULTA");

            entity.Property(e => e.Status).HasColumnName("STATUS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceContingController> entity);
    }
}
