// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class NfceInutilizadaXmlConfiguration : IEntityTypeConfiguration<NfceInutilizadaXml>
    {
        public void Configure(EntityTypeBuilder<NfceInutilizadaXml> entity)
        {
            entity.HasKey(e => e.CdNfceInutilizada);

            entity.ToTable("NFCE_INUTILIZADA_XML");

            entity.HasIndex(e => e.CdNfceInutilizada, "PK_NFCE_INUTILIZADA_XML")
                .IsUnique();

            entity.Property(e => e.CdNfceInutilizada).HasColumnName("CD_NFCE_INUTILIZADA");

            entity.Property(e => e.ArqXml).HasColumnName("ARQ_XML");

            entity.Property(e => e.CdUsuario).HasColumnName("CD_USUARIO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NfceInutilizadaXml> entity);
    }
}
