// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class PedidoCompraPagamentoConfiguration : IEntityTypeConfiguration<PedidoCompraPagamento>
    {
        public void Configure(EntityTypeBuilder<PedidoCompraPagamento> entity)
        {
            entity.ToTable("PEDIDO_COMPRA_PAGAMENTO");

            entity.HasIndex(e => e.Id, "PK_PEDIDO_COMPRA_PAGAMENTO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.BxData).HasColumnName("BX_DATA");

            entity.Property(e => e.BxLogin)
                .HasMaxLength(80)
                .HasColumnName("BX_LOGIN");

            entity.Property(e => e.DataCadastro).HasColumnName("DATA_CADASTRO");

            entity.Property(e => e.DtUltimaAlteracao).HasColumnName("DT_ULTIMA_ALTERACAO");

            entity.Property(e => e.FornecedorId).HasColumnName("FORNECEDOR_ID");

            entity.Property(e => e.MarcaId).HasColumnName("MARCA_ID");

            entity.Property(e => e.Parcela).HasColumnName("PARCELA");

            entity.Property(e => e.PedidoCompraId).HasColumnName("PEDIDO_COMPRA_ID");

            entity.Property(e => e.Periodicidade).HasColumnName("PERIODICIDADE");

            entity.Property(e => e.Status)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("STATUS");

            entity.Property(e => e.UsuarioId).HasColumnName("USUARIO_ID");

            entity.Property(e => e.ValorEntrada).HasColumnName("VALOR_ENTRADA");

            entity.Property(e => e.ValorTotalMarca).HasColumnName("VALOR_TOTAL_MARCA");

            entity.Property(e => e.ValorTotalPedidoCompra).HasColumnName("VALOR_TOTAL_PEDIDO_COMPRA");

            entity.Property(e => e.Vencimento).HasColumnName("VENCIMENTO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PedidoCompraPagamento> entity);
    }
}
