// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class PedidoPagamentoConfiguration : IEntityTypeConfiguration<PedidoPagamento>
    {
        public void Configure(EntityTypeBuilder<PedidoPagamento> entity)
        {
            entity.ToTable("PEDIDO_PAGAMENTO");

            entity.HasIndex(e => e.NumDocumento, "PEDIDO_PAGAMENTO_IDX1");

            entity.HasIndex(e => e.Id, "PK_PEDIDO_PAGAMENTO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.Arquivolocal)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ARQUIVOLOCAL");

            entity.Property(e => e.CartaoCodcartao).HasColumnName("CARTAO_CODCARTAO");

            entity.Property(e => e.CartaoDiasrepasse)
                .HasColumnType("VARCHAR(19999)")
                .HasColumnName("CARTAO_DIASREPASSE");

            entity.Property(e => e.CartaoNomecartao)
                .HasMaxLength(80)
                .HasColumnName("CARTAO_NOMECARTAO");

            entity.Property(e => e.CartaoNumparcelas).HasColumnName("CARTAO_NUMPARCELAS");

            entity.Property(e => e.CartaoParceladesctaxa)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CARTAO_PARCELADESCTAXA");

            entity.Property(e => e.CartaoTaxa)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CARTAO_TAXA");

            entity.Property(e => e.CartaoTipocartao).HasColumnName("CARTAO_TIPOCARTAO");

            entity.Property(e => e.CartaoValoracrescimo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CARTAO_VALORACRESCIMO");

            entity.Property(e => e.CartaoValordesctaxa)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CARTAO_VALORDESCTAXA");

            entity.Property(e => e.CartaoValorparcela)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CARTAO_VALORPARCELA");

            entity.Property(e => e.ChequeAgencia)
                .HasMaxLength(8)
                .HasColumnName("CHEQUE_AGENCIA");

            entity.Property(e => e.ChequeBanco)
                .HasColumnType("CHAR(3) ")
                .HasColumnName("CHEQUE_BANCO");

            entity.Property(e => e.ChequeConta)
                .HasMaxLength(10)
                .HasColumnName("CHEQUE_CONTA");

            entity.Property(e => e.ChequeNumero)
                .HasMaxLength(15)
                .HasColumnName("CHEQUE_NUMERO");

            entity.Property(e => e.ChequeTitularCpf)
                .HasMaxLength(18)
                .HasColumnName("CHEQUE_TITULAR_CPF");

            entity.Property(e => e.ChequeTitularNome)
                .HasMaxLength(40)
                .HasColumnName("CHEQUE_TITULAR_NOME");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.NumDocumento).HasColumnName("NUM_DOCUMENTO");

            entity.Property(e => e.NumDocumentoAux).HasColumnName("NUM_DOCUMENTO_AUX");

            entity.Property(e => e.Obs)
                .HasMaxLength(800)
                .HasColumnName("OBS");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TipoPagamento).HasColumnName("TIPO_PAGAMENTO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Valor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALOR");

            entity.Property(e => e.Vencimento)
                .HasColumnType("DATE")
                .HasColumnName("VENCIMENTO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PedidoPagamento> entity);
    }
}
