// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class PedidoItemNumserieConfiguration : IEntityTypeConfiguration<PedidoItemNumserie>
    {
        public void Configure(EntityTypeBuilder<PedidoItemNumserie> entity)
        {
            entity.HasKey(e => new { e.IdPedidoItem, e.Numserie });

            entity.ToTable("PEDIDO_ITEM_NUMSERIE");

            entity.HasIndex(e => new { e.Numserie, e.IdPedidoItem }, "PK_PEDIDO_ITEM_NUMSERIE")
                .IsUnique();

            entity.Property(e => e.IdPedidoItem).HasColumnName("ID_PEDIDO_ITEM");

            entity.Property(e => e.Numserie)
                .HasMaxLength(50)
                .HasColumnName("NUMSERIE");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.IdAux).HasColumnName("ID_AUX");

            entity.Property(e => e.NumDocumentoAux).HasColumnName("NUM_DOCUMENTO_AUX");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PedidoItemNumserie> entity);
    }
}
