// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class PedidoConfiguration : IEntityTypeConfiguration<Pedido>
    {
        public void Configure(EntityTypeBuilder<Pedido> entity)
        {
            entity.HasKey(e => e.NumDocumento);

            entity.ToTable("PEDIDO");

            entity.HasIndex(e => e.NumDocumento, "PEDIDO_IDX1");

            entity.HasIndex(e => e.CdCliente, "PEDIDO_IDX2");

            entity.HasIndex(e => e.DtFechamento, "PEDIDO_IDX3");

            entity.HasIndex(e => e.DtEntrega, "PEDIDO_IDX4");

            entity.HasIndex(e => e.CdVendedor, "PEDIDO_IDX5");

            entity.HasIndex(e => e.Categoria, "PEDIDO_IDX6");

            entity.HasIndex(e => e.TipoDocumento, "PEDIDO_IDX7");

            entity.HasIndex(e => e.DtAbertura, "PEDIDO_IDX8");

            entity.HasIndex(e => e.NumDocumento, "PK_PEDIDO")
                .IsUnique();

            entity.Property(e => e.NumDocumento).HasColumnName("NUM_DOCUMENTO");

            entity.Property(e => e.AcresDescLogin)
                .HasMaxLength(80)
                .HasColumnName("ACRES_DESC_LOGIN");

            entity.Property(e => e.AcresDescPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_PORC");

            entity.Property(e => e.AcresDescPorcEspecial)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_PORC_ESPECIAL");

            entity.Property(e => e.AcresDescTipo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ACRES_DESC_TIPO");

            entity.Property(e => e.AcresDescUnitPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_UNIT_PORC");

            entity.Property(e => e.AcresDescUnitValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_UNIT_VALOR");

            entity.Property(e => e.AcresDescValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_VALOR");

            entity.Property(e => e.Alt)
                .HasMaxLength(10)
                .HasColumnName("ALT");

            entity.Property(e => e.Alteraestoque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALTERAESTOQUE");

            entity.Property(e => e.Arquivolocal)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ARQUIVOLOCAL");

            entity.Property(e => e.Cancelado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CANCELADO");

            entity.Property(e => e.Reforma)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("REFORMA");

            entity.Property(e => e.CanceladoCdUsuario).HasColumnName("CANCELADO_CD_USUARIO");

            entity.Property(e => e.CanceladoDatahora).HasColumnName("CANCELADO_DATAHORA");

            entity.Property(e => e.CanceladoDescontacaixa)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CANCELADO_DESCONTACAIXA");

            entity.Property(e => e.CanceladoDevolveestoque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CANCELADO_DEVOLVEESTOQUE");

            entity.Property(e => e.CanceladoEliminacontas)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CANCELADO_ELIMINACONTAS");

            entity.Property(e => e.CanceladoMotivo)
                .HasMaxLength(200)
                .HasColumnName("CANCELADO_MOTIVO");

            entity.Property(e => e.CanceladoNumTerminal).HasColumnName("CANCELADO_NUM_TERMINAL");

            entity.Property(e => e.Categoria).HasColumnName("CATEGORIA");

            entity.Property(e => e.CdCertificado).HasColumnName("CD_CERTIFICADO");

            entity.Property(e => e.CdCliente).HasColumnName("CD_CLIENTE");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.CdFormapagamento).HasColumnName("CD_FORMAPAGAMENTO");

            entity.Property(e => e.CdMesas).HasColumnName("CD_MESAS");

            entity.Property(e => e.CdTipopreco).HasColumnName("CD_TIPOPRECO");

            entity.Property(e => e.CdVendedor).HasColumnName("CD_VENDEDOR");

            entity.Property(e => e.CliApelido)
                .HasMaxLength(80)
                .HasColumnName("CLI_APELIDO");

            entity.Property(e => e.CliBairro)
                .HasMaxLength(35)
                .HasColumnName("CLI_BAIRRO");

            entity.Property(e => e.CliCdMunicipio).HasColumnName("CLI_CD_MUNICIPIO");

            entity.Property(e => e.CliCep)
                .HasMaxLength(9)
                .HasColumnName("CLI_CEP");

            entity.Property(e => e.CliCidade)
                .HasMaxLength(35)
                .HasColumnName("CLI_CIDADE");

            entity.Property(e => e.CliCpf)
                .HasMaxLength(18)
                .HasColumnName("CLI_CPF");

            entity.Property(e => e.CliEndereco)
                .HasMaxLength(400)
                .HasColumnName("CLI_ENDERECO");

            entity.Property(e => e.CliEnderecoNum)
                .HasMaxLength(20)
                .HasColumnName("CLI_ENDERECO_NUM");

            entity.Property(e => e.CliNmCliente)
                .HasMaxLength(80)
                .HasColumnName("CLI_NM_CLIENTE");

            entity.Property(e => e.CliUf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("CLI_UF");

            entity.Property(e => e.Comanda)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("COMANDA");

            entity.Property(e => e.Conferido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CONFERIDO");

            entity.Property(e => e.CooDav).HasColumnName("COO_DAV");

            entity.Property(e => e.Despesa)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESPESA");

            entity.Property(e => e.DespesaDescr)
                .HasMaxLength(100)
                .HasColumnName("DESPESA_DESCR");

            entity.Property(e => e.DtAbertura).HasColumnName("DT_ABERTURA");

            entity.Property(e => e.DtEntrega)
                .HasColumnType("DATE")
                .HasColumnName("DT_ENTREGA");

            entity.Property(e => e.DtFechamento).HasColumnName("DT_FECHAMENTO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.Entregue)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ENTREGUE");

            entity.Property(e => e.Exportar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR");

            entity.Property(e => e.Flag)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("FLAG");

            entity.Property(e => e.Frete)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETE");

            entity.Property(e => e.FreteDescr)
                .HasMaxLength(100)
                .HasColumnName("FRETE_DESCR");

            entity.Property(e => e.Fretechegada)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETECHEGADA");

            entity.Property(e => e.Fretesaidabruto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETESAIDABRUTO");

            entity.Property(e => e.Fretesaidaliquido)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETESAIDALIQUIDO");

            entity.Property(e => e.IdSellerWeb)
                .HasMaxLength(20)
                .HasColumnName("ID_SELLER_WEB");

            entity.Property(e => e.Imprimiu)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMPRIMIU");

            entity.Property(e => e.LoginAbertura)
                .HasMaxLength(80)
                .HasColumnName("LOGIN_ABERTURA");

            entity.Property(e => e.LoginFechamento)
                .HasMaxLength(80)
                .HasColumnName("LOGIN_FECHAMENTO");

            entity.Property(e => e.MesaAnterior).HasColumnName("MESA_ANTERIOR");

            entity.Property(e => e.NmVendedor)
                .HasMaxLength(80)
                .HasColumnName("NM_VENDEDOR");

            entity.Property(e => e.NumControle)
                .HasMaxLength(15)
                .HasColumnName("NUM_CONTROLE");

            entity.Property(e => e.NumDocSeller).HasColumnName("NUM_DOC_SELLER");

            entity.Property(e => e.NumDocumentoAux).HasColumnName("NUM_DOCUMENTO_AUX");

            entity.Property(e => e.NumTerminalAbertura).HasColumnName("NUM_TERMINAL_ABERTURA");

            entity.Property(e => e.NumTerminalEdicao).HasColumnName("NUM_TERMINAL_EDICAO");

            entity.Property(e => e.NumTerminalFechamento).HasColumnName("NUM_TERMINAL_FECHAMENTO");

            entity.Property(e => e.NumecfDav).HasColumnName("NUMECF_DAV");

            entity.Property(e => e.Obs)
                .HasMaxLength(800)
                .HasColumnName("OBS");

            entity.Property(e => e.OrcFinalizado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ORC_FINALIZADO");

            entity.Property(e => e.Ordem).HasColumnName("ORDEM");

            entity.Property(e => e.OrigemAbertura)
                .HasMaxLength(3)
                .HasColumnName("ORIGEM_ABERTURA");

            entity.Property(e => e.OrigemFechamento)
                .HasMaxLength(3)
                .HasColumnName("ORIGEM_FECHAMENTO");

            entity.Property(e => e.PagCartaoCredito)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_CARTAO_CREDITO");

            entity.Property(e => e.PagCartaoDebito)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_CARTAO_DEBITO");

            entity.Property(e => e.PagCartaoParcelado)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_CARTAO_PARCELADO");

            entity.Property(e => e.PagChequeato)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_CHEQUEATO");

            entity.Property(e => e.PagChequepre)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_CHEQUEPRE");

            entity.Property(e => e.PagCredcli)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_CREDCLI");

            entity.Property(e => e.PagCrediario)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_CREDIARIO");

            entity.Property(e => e.PagDinheiro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_DINHEIRO");

            entity.Property(e => e.PagDinheirocomtroco)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_DINHEIROCOMTROCO");

            entity.Property(e => e.PagMoedasocial)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_MOEDASOCIAL");

            entity.Property(e => e.PagOutros)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_OUTROS");

            entity.Property(e => e.PagTicket)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PAG_TICKET");

            entity.Property(e => e.Palmcodpedido)
                .HasMaxLength(10)
                .HasColumnName("PALMCODPEDIDO");

            entity.Property(e => e.Palmnumdoc)
                .HasMaxLength(20)
                .HasColumnName("PALMNUMDOC");

            entity.Property(e => e.Palmserie)
                .HasMaxLength(20)
                .HasColumnName("PALMSERIE");

            entity.Property(e => e.PedChave)
                .HasMaxLength(50)
                .HasColumnName("PED_CHAVE");

            entity.Property(e => e.PedModelo)
                .HasMaxLength(3)
                .HasColumnName("PED_MODELO");

            entity.Property(e => e.PedNumero).HasColumnName("PED_NUMERO");

            entity.Property(e => e.PedSerie)
                .HasMaxLength(3)
                .HasColumnName("PED_SERIE");

            entity.Property(e => e.Pesobruto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOBRUTO");

            entity.Property(e => e.Pesoliquido)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOLIQUIDO");

            entity.Property(e => e.QtdeAcresUnit).HasColumnName("QTDE_ACRES_UNIT");

            entity.Property(e => e.QtdeDescUnit).HasColumnName("QTDE_DESC_UNIT");

            entity.Property(e => e.QtdeItens).HasColumnName("QTDE_ITENS");

            entity.Property(e => e.QtdePecas)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QTDE_PECAS");

            entity.Property(e => e.Qtdecheques).HasColumnName("QTDECHEQUES");

            entity.Property(e => e.Qtdeparccred).HasColumnName("QTDEPARCCRED");

            entity.Property(e => e.RefCaixaDtAbertura).HasColumnName("REF_CAIXA_DT_ABERTURA");

            entity.Property(e => e.RefCoo).HasColumnName("REF_COO");

            entity.Property(e => e.SellerStatus)
                .HasMaxLength(10)
                .HasColumnName("SELLER_STATUS");

            entity.Property(e => e.SeqdiarioLocal)
                .HasMaxLength(10)
                .HasColumnName("SEQDIARIO_LOCAL");

            entity.Property(e => e.Sequencialdiario).HasColumnName("SEQUENCIALDIARIO");

            entity.Property(e => e.Sincronizado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZADO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TipoDocumento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_DOCUMENTO");

            entity.Property(e => e.TipoFood)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_FOOD");

            entity.Property(e => e.TipoVenda)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPO_VENDA");

            entity.Property(e => e.TotalBruto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TOTAL_BRUTO");

            entity.Property(e => e.TotalComissao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TOTAL_COMISSAO");

            entity.Property(e => e.TotalFrete)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TOTAL_FRETE");

            entity.Property(e => e.TotalLiquido)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TOTAL_LIQUIDO");

            entity.Property(e => e.Troco)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("TROCO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Ultimologin)
                .HasMaxLength(80)
                .HasColumnName("ULTIMOLOGIN");

            entity.Property(e => e.UltimonumTerminal).HasColumnName("ULTIMONUM_TERMINAL");

            entity.Property(e => e.Valorcusto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALORCUSTO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Pedido> entity);
    }
}
