// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class PedidoItemConfiguration : IEntityTypeConfiguration<PedidoItem>
    {
        public void Configure(EntityTypeBuilder<PedidoItem> entity)
        {
            entity.HasKey(e => new { e.Id, e.NumTerminal });

            entity.ToTable("PEDIDO_ITEM");

            entity.HasIndex(e => e.NumDocumento, "PEDIDO_ITEM_IDX1");

            entity.HasIndex(e => e.CdProduto, "PEDIDO_ITEM_IDX2");

            entity.HasIndex(e => e.CdKit, "PEDIDO_ITEM_IDX3");

            entity.HasIndex(e => e.CdKit, "PEDIDO_ITEM_KIT");

            entity.HasIndex(e => new { e.Id, e.NumTerminal }, "PK_PEDIDO_ITEM")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.AcresDescPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_PORC");

            entity.Property(e => e.AcresDescPorcAutomatico)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_PORC_AUTOMATICO");

            entity.Property(e => e.AcresDescPorcManual)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_PORC_MANUAL");

            entity.Property(e => e.AcresDescPorcReal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_PORC_REAL");

            entity.Property(e => e.AcresDescTipo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ACRES_DESC_TIPO");

            entity.Property(e => e.AcresDescTipoManual)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ACRES_DESC_TIPO_MANUAL");

            entity.Property(e => e.AcresDescValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_VALOR");

            entity.Property(e => e.AcresDescValorAutomatico)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_VALOR_AUTOMATICO");

            entity.Property(e => e.AcresDescValorManual)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_VALOR_MANUAL");

            entity.Property(e => e.AcresDescValorReal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ACRES_DESC_VALOR_REAL");

            entity.Property(e => e.Alt)
                .HasMaxLength(10)
                .HasColumnName("ALT");

            entity.Property(e => e.Alteroudescricao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALTEROUDESCRICAO");

            entity.Property(e => e.Alterouestoque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ALTEROUESTOQUE");

            entity.Property(e => e.Arquivolocal)
                .IsRequired()
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ARQUIVOLOCAL");

            entity.Property(e => e.Cancelado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CANCELADO");

            entity.Property(e => e.CanceladoCdUsuario).HasColumnName("CANCELADO_CD_USUARIO");

            entity.Property(e => e.CanceladoDatahora).HasColumnName("CANCELADO_DATAHORA");

            entity.Property(e => e.CanceladoMotivo)
                .HasMaxLength(400)
                .HasColumnName("CANCELADO_MOTIVO");

            entity.Property(e => e.CanceladoTerminal).HasColumnName("CANCELADO_TERMINAL");

            entity.Property(e => e.Casasdecimais).HasColumnName("CASASDECIMAIS");

            entity.Property(e => e.CdGrade).HasColumnName("CD_GRADE");

            entity.Property(e => e.CdKit).HasColumnName("CD_KIT");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.CdPromocao).HasColumnName("CD_PROMOCAO");

            entity.Property(e => e.CdSetor).HasColumnName("CD_SETOR");

            entity.Property(e => e.CdTipopreco).HasColumnName("CD_TIPOPRECO");

            entity.Property(e => e.CdVendedor).HasColumnName("CD_VENDEDOR");

            entity.Property(e => e.CodBarras)
                .HasMaxLength(14)
                .HasColumnName("COD_BARRAS");

            entity.Property(e => e.ComissaoPorc)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMISSAO_PORC");

            entity.Property(e => e.ComissaoTipo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("COMISSAO_TIPO");

            entity.Property(e => e.ComissaoValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMISSAO_VALOR");

            entity.Property(e => e.Conferido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CONFERIDO");

            entity.Property(e => e.DataHoraItem).HasColumnName("DATA_HORA_ITEM");

            entity.Property(e => e.DimComprimento)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DIM_COMPRIMENTO");

            entity.Property(e => e.DimEspessura)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DIM_ESPESSURA");

            entity.Property(e => e.DimLargura)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DIM_LARGURA");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.EcfAliquota)
                .HasMaxLength(10)
                .HasColumnName("ECF_ALIQUOTA");

            entity.Property(e => e.Emlote)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EMLOTE");

            entity.Property(e => e.FlagPeso)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("FLAG_PESO");

            entity.Property(e => e.FoodMotivoCancel)
                .HasMaxLength(100)
                .HasColumnName("FOOD_MOTIVO_CANCEL");

            entity.Property(e => e.FreteValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETE_VALOR");

            entity.Property(e => e.Fretechegada)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETECHEGADA");

            entity.Property(e => e.Fretesaida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETESAIDA");

            entity.Property(e => e.Iat)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IAT");

            entity.Property(e => e.IdAux).HasColumnName("ID_AUX");

            entity.Property(e => e.IdPromocaokit).HasColumnName("ID_PROMOCAOKIT");

            entity.Property(e => e.Imprimiu)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IMPRIMIU");

            entity.Property(e => e.Ippt)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IPPT");

            entity.Property(e => e.Login)
                .HasMaxLength(80)
                .HasColumnName("LOGIN");

            entity.Property(e => e.NmProduto)
                .HasMaxLength(100)
                .HasColumnName("NM_PRODUTO");

            entity.Property(e => e.NumDocumento).HasColumnName("NUM_DOCUMENTO");

            entity.Property(e => e.NumDocumentoAux).HasColumnName("NUM_DOCUMENTO_AUX");

            entity.Property(e => e.NumItem).HasColumnName("NUM_ITEM");

            entity.Property(e => e.Obs)
                .HasMaxLength(100)
                .HasColumnName("OBS");

            entity.Property(e => e.Origem)
                .HasMaxLength(3)
                .HasColumnName("ORIGEM");

            entity.Property(e => e.Pesobruto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOBRUTO");

            entity.Property(e => e.Pesochegada)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOCHEGADA");

            entity.Property(e => e.Pesoliquido)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOLIQUIDO");

            entity.Property(e => e.Pesosaida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOSAIDA");

            entity.Property(e => e.Preco)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO");

            entity.Property(e => e.PrecoEscolhido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PRECO_ESCOLHIDO");

            entity.Property(e => e.PrecoPedido)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO_PEDIDO");

            entity.Property(e => e.Precocusto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTO");

            entity.Property(e => e.Precotabela)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOTABELA");

            entity.Property(e => e.PromocaoScanntechId).HasColumnName("PROMOCAO_SCANNTECH_ID");

            entity.Property(e => e.PromocaoScanntechQuantidade).HasColumnName("PROMOCAO_SCANNTECH_QUANTIDADE");

            entity.Property(e => e.PromocaoScanntechTipo).HasColumnName("PROMOCAO_SCANNTECH_TIPO");

            entity.Property(e => e.QtdeDevolvida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QTDE_DEVOLVIDA");

            entity.Property(e => e.QtdePedida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QTDE_PEDIDA");

            entity.Property(e => e.Quantidade)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QUANTIDADE");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.St)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ST");

            entity.Property(e => e.Subtotal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("SUBTOTAL");

            entity.Property(e => e.SubtotalReal)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("SUBTOTAL_REAL");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.UltimoPedido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("ULTIMO_PEDIDO");

            entity.Property(e => e.Unidade)
                .HasColumnType("CHAR(3) ")
                .HasColumnName("UNIDADE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PedidoItem> entity);
    }
}
