// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class PedidoCategoriaConfiguration : IEntityTypeConfiguration<PedidoCategoria>
    {
        public void Configure(EntityTypeBuilder<PedidoCategoria> entity)
        {
            entity.HasKey(e => e.CdPedidoCategoria);

            entity.ToTable("PEDIDO_CATEGORIA");

            entity.HasIndex(e => e.CdPedidoCategoria, "PK_PEDIDO_CATEGORIA")
                .IsUnique();

            entity.Property(e => e.CdPedidoCategoria).HasColumnName("CD_PEDIDO_CATEGORIA");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DescontosPermitidos)
                .HasMaxLength(100)
                .HasColumnName("DESCONTOS_PERMITIDOS");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.NmPedidoCategoria)
                .HasMaxLength(80)
                .HasColumnName("NM_PEDIDO_CATEGORIA");

            entity.Property(e => e.Obs)
                .HasMaxLength(400)
                .HasColumnName("OBS");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TipoNota).HasColumnName("TIPO_NOTA");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PedidoCategoria> entity);
    }
}
