// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutosFotoConfiguration : IEntityTypeConfiguration<ProdutosFoto>
    {
        public void Configure(EntityTypeBuilder<ProdutosFoto> entity)
        {
            entity.HasKey(e => new { e.Id, e.CdProduto });

            entity.ToTable("PRODUTOS_FOTO");

            entity.HasIndex(e => new { e.Id, e.CdProduto }, "PK_PRODUTOS_FOTO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.Foto).HasColumnName("FOTO");

            entity.Property(e => e.Ordem).HasColumnName("ORDEM");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProdutosFoto> entity);
    }
}
