// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutosTributacaoConfiguration : IEntityTypeConfiguration<ProdutosTributacao>
    {
        public void Configure(EntityTypeBuilder<ProdutosTributacao> entity)
        {
            entity.ToTable("PRODUTOS_TRIBUTACAO");

            entity.HasIndex(e => e.Id, "PK_PRODUTOS_TRIBUTACAO")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.AliquotaInterestadual)
                .HasColumnType("CHAR(6) ")
                .HasColumnName("ALIQUOTA_INTERESTADUAL");

            entity.Property(e => e.Cfop).HasColumnName("CFOP");

            entity.Property(e => e.CodBeneficioFiscal)
                .HasMaxLength(10)
                .HasColumnName("COD_BENEFICIO_FISCAL");

            entity.Property(e => e.Cofins)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINS");

            entity.Property(e => e.CofinsCst).HasColumnName("COFINS_CST");

            entity.Property(e => e.Cst)
                .HasMaxLength(2)
                .HasColumnName("CST");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDataHora).HasColumnName("DELETADO_DATA_HORA");

            entity.Property(e => e.Descricao)
                .HasMaxLength(100)
                .HasColumnName("DESCRICAO");

            entity.Property(e => e.Fecp)
                .HasColumnType("CHAR(6) ")
                .HasColumnName("FECP");

            entity.Property(e => e.Icms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS");

            entity.Property(e => e.IcmsAliquotaCalcDesoneracao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_ALIQUOTA_CALC_DESONERACAO");

            entity.Property(e => e.Ipi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI");

            entity.Property(e => e.IpiCst).HasColumnName("IPI_CST");

            entity.Property(e => e.Ippt)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IPPT");

            entity.Property(e => e.MotivoDesoneracaoIcms).HasColumnName("MOTIVO_DESONERACAO_ICMS");

            entity.Property(e => e.Mva12)
                .HasColumnType("CHAR(6) ")
                .HasColumnName("MVA_12");

            entity.Property(e => e.Mva4)
                .HasColumnType("CHAR(6) ")
                .HasColumnName("MVA_4");

            entity.Property(e => e.Operacao).HasColumnName("OPERACAO");

            entity.Property(e => e.Origem).HasColumnName("ORIGEM");

            entity.Property(e => e.Pis)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PIS");

            entity.Property(e => e.PisCst).HasColumnName("PIS_CST");

            entity.Property(e => e.ReducaoBaseCalculo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REDUCAO_BASE_CALCULO");

            entity.Property(e => e.Substtributaria)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SUBSTTRIBUTARIA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProdutosTributacao> entity);
    }
}
