// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutosReajustesConfiguration : IEntityTypeConfiguration<ProdutosReajustes>
    {
        public void Configure(EntityTypeBuilder<ProdutosReajustes> entity)
        {
            entity.HasKey(e => new { e.CdProduto, e.DataHora });

            entity.ToTable("PRODUTOS_REAJUSTES");

            entity.HasIndex(e => new { e.DataHora, e.CdProduto }, "PK_PRODUTOS_REAJUSTES")
                .IsUnique();

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.DataHora).HasColumnName("DATA_HORA");

            entity.Property(e => e.DescontofixoAnterior)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOFIXO_ANTERIOR");

            entity.Property(e => e.DescontofixoNovo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOFIXO_NOVO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Login)
                .HasMaxLength(80)
                .HasColumnName("LOGIN");

            entity.Property(e => e.LoginUltimaalteracao)
                .HasMaxLength(80)
                .HasColumnName("LOGIN_ULTIMAALTERACAO");

            entity.Property(e => e.PrecocustoAnterior)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTO_ANTERIOR");

            entity.Property(e => e.PrecocustoNovo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTO_NOVO");

            entity.Property(e => e.PrecovendaAnterior)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOVENDA_ANTERIOR");

            entity.Property(e => e.PrecovendaNovo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOVENDA_NOVO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Tabela).HasColumnName("TABELA");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProdutosReajustes> entity);
    }
}
