// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutosUrlConfiguration : IEntityTypeConfiguration<ProdutosUrl>
    {
        public void Configure(EntityTypeBuilder<ProdutosUrl> entity)
        {
            entity.ToTable("PRODUTOS_URL");

            entity.HasIndex(e => e.Id, "RDB$PRIMARY8")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahota).HasColumnName("DELETADO_DATAHOTA");

            entity.Property(e => e.Url)
                .HasMaxLength(400)
                .HasColumnName("URL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProdutosUrl> entity);
    }
}
