// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutoSimilarConfiguration : IEntityTypeConfiguration<ProdutoSimilar>
    {
        public void Configure(EntityTypeBuilder<ProdutoSimilar> entity)
        {
            entity.HasKey(e => e.CdSimilar);

            entity.ToTable("PRODUTO_SIMILAR");

            entity.HasIndex(e => e.CdSimilar, "PK_PRODUTO_SIMILAR")
                .IsUnique();

            entity.Property(e => e.CdSimilar).HasColumnName("CD_SIMILAR");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.NmSimilar)
                .HasMaxLength(40)
                .HasColumnName("NM_SIMILAR");

            entity.Property(e => e.Obs)
                .HasMaxLength(200)
                .HasColumnName("OBS");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProdutoSimilar> entity);
    }
}
