// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutosRefConfiguration : IEntityTypeConfiguration<ProdutosRef>
    {
        public void Configure(EntityTypeBuilder<ProdutosRef> entity)
        {
            entity.HasKey(e => e.CdProduto);

            entity.ToTable("PRODUTOS_REF");

            entity.HasIndex(e => e.CdProduto, "PK_PRODUTOS_REF")
                .IsUnique();

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtUltimacompra).HasColumnName("DT_ULTIMACOMPRA");

            entity.Property(e => e.DtUltimavenda).HasColumnName("DT_ULTIMAVENDA");

            entity.Property(e => e.Loginultimacompra)
                .HasMaxLength(80)
                .HasColumnName("LOGINULTIMACOMPRA");

            entity.Property(e => e.Loginultimavenda)
                .HasMaxLength(80)
                .HasColumnName("LOGINULTIMAVENDA");

            entity.Property(e => e.Mediavenda)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MEDIAVENDA");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.TemGrade)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TEM_GRADE");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Ultimofornecedor).HasColumnName("ULTIMOFORNECEDOR");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProdutosRef> entity);
    }
}
