// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutosConfiguration : IEntityTypeConfiguration<Produtos>
    {
        public void Configure(EntityTypeBuilder<Produtos> entity)
        {
            entity.HasKey(e => e.CdProduto);

            entity.ToTable("PRODUTOS");

            entity.HasIndex(e => e.Aplicacao, "IDX_APLICACAO");

            entity.HasIndex(e => e.Classfiscal, "IDX_CLASSFISCAL");

            entity.HasIndex(e => e.BalCodBalanca, "IDX_CODBALANCA");

            entity.HasIndex(e => e.CxCodBarraCaixa, "IDX_CODCAIXA");

            entity.HasIndex(e => e.Codigo02, "IDX_CODIGO2");

            entity.HasIndex(e => e.Codigo03, "IDX_CODIGO3");

            entity.HasIndex(e => e.Codigo04, "IDX_CODIGO4");

            entity.HasIndex(e => e.Inativo, "IDX_PRODINATIVO");

            entity.HasIndex(e => e.CdProduto, "PK_PRODUTOS")
                .IsUnique();

            entity.HasIndex(e => e.NmProduto, "PRODUTOS_IDX1");

            entity.HasIndex(e => e.CodBarras, "PRODUTOS_IDX2");

            entity.HasIndex(e => e.CdGrupo, "PRODUTOS_IDX3");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.Adremicmsret)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ADREMICMSRET");

            entity.Property(e => e.AliquotaEcf)
                .HasMaxLength(10)
                .HasColumnName("ALIQUOTA_ECF");

            entity.Property(e => e.Aplicacao)
                .HasMaxLength(400)
                .HasColumnName("APLICACAO");

            entity.Property(e => e.BalCodBalanca).HasColumnName("BAL_COD_BALANCA");

            entity.Property(e => e.BalGerarcodbalanca)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("BAL_GERARCODBALANCA");

            entity.Property(e => e.CdEmpresa).HasColumnName("CD_EMPRESA");

            entity.Property(e => e.CdEngradado).HasColumnName("CD_ENGRADADO");

            entity.Property(e => e.CdGrupo).HasColumnName("CD_GRUPO");

            entity.Property(e => e.CdModelo).HasColumnName("CD_MODELO");

            entity.Property(e => e.CdProdEstoqueCompartilhado).HasColumnName("CD_PROD_ESTOQUE_COMPARTILHADO");

            entity.Property(e => e.CdSimilar).HasColumnName("CD_SIMILAR");

            entity.Property(e => e.Cest)
                .HasMaxLength(7)
                .HasColumnName("CEST");

            entity.Property(e => e.CestaBasica)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CESTA_BASICA");

            entity.Property(e => e.Classfiscal)
                .HasMaxLength(12)
                .HasColumnName("CLASSFISCAL");

            entity.Property(e => e.CodBarras)
                .HasMaxLength(14)
                .HasColumnName("COD_BARRAS");

            entity.Property(e => e.CodBeneficioFiscal)
                .HasMaxLength(10)
                .HasColumnName("COD_BENEFICIO_FISCAL");

            entity.Property(e => e.CodFornecedor)
                .HasMaxLength(20)
                .HasColumnName("COD_FORNECEDOR");

            entity.Property(e => e.Codigo02)
                .HasMaxLength(20)
                .HasColumnName("CODIGO02");

            entity.Property(e => e.Codigo03)
                .HasMaxLength(20)
                .HasColumnName("CODIGO03");

            entity.Property(e => e.Codigo04)
                .HasMaxLength(20)
                .HasColumnName("CODIGO04");

            entity.Property(e => e.Cofins)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COFINS");

            entity.Property(e => e.CofinsCst).HasColumnName("COFINS_CST");

            entity.Property(e => e.CombAliqcide)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_ALIQCIDE");

            entity.Property(e => e.CombBccide)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_BCCIDE");

            entity.Property(e => e.CombCodanp)
                .HasMaxLength(30)
                .HasColumnName("COMB_CODANP");

            entity.Property(e => e.CombCodif)
                .HasMaxLength(30)
                .HasColumnName("COMB_CODIF");

            entity.Property(e => e.CombDescanp)
                .HasMaxLength(30)
                .HasColumnName("COMB_DESCANP");

            entity.Property(e => e.CombEncNbico)
                .HasMaxLength(30)
                .HasColumnName("COMB_ENC_NBICO");

            entity.Property(e => e.CombEncNbomba)
                .HasMaxLength(30)
                .HasColumnName("COMB_ENC_NBOMBA");

            entity.Property(e => e.CombEncNtanque)
                .HasMaxLength(30)
                .HasColumnName("COMB_ENC_NTANQUE");

            entity.Property(e => e.CombEncVencfin)
                .HasMaxLength(30)
                .HasColumnName("COMB_ENC_VENCFIN");

            entity.Property(e => e.CombEncVencini)
                .HasMaxLength(30)
                .HasColumnName("COMB_ENC_VENCINI");

            entity.Property(e => e.CombPglp)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_PGLP");

            entity.Property(e => e.CombPgni)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_PGNI");

            entity.Property(e => e.CombPgnn)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_PGNN");

            entity.Property(e => e.CombQtfattempamb)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_QTFATTEMPAMB");

            entity.Property(e => e.CombUfConsumo)
                .HasMaxLength(2)
                .HasColumnName("COMB_UF_CONSUMO");

            entity.Property(e => e.CombValcide)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_VALCIDE");

            entity.Property(e => e.CombVpart)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMB_VPART");

            entity.Property(e => e.Comissao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMISSAO");

            entity.Property(e => e.ControlaLote)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CONTROLA_LOTE");

            entity.Property(e => e.Controlanumserie)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CONTROLANUMSERIE");

            entity.Property(e => e.Cst)
                .HasMaxLength(2)
                .HasColumnName("CST");

            entity.Property(e => e.Custocompra)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CUSTOCOMPRA");

            entity.Property(e => e.Customanual)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("CUSTOMANUAL");

            entity.Property(e => e.Customedio)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CUSTOMEDIO");

            entity.Property(e => e.CxCodBarraCaixa)
                .HasMaxLength(14)
                .HasColumnName("CX_COD_BARRA_CAIXA");

            entity.Property(e => e.CxUndconversao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("CX_UNDCONVERSAO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.Descfixomargem10)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM10");

            entity.Property(e => e.Descfixomargem11)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM11");

            entity.Property(e => e.Descfixomargem2)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM2");

            entity.Property(e => e.Descfixomargem3)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM3");

            entity.Property(e => e.Descfixomargem4)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM4");

            entity.Property(e => e.Descfixomargem5)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM5");

            entity.Property(e => e.Descfixomargem6)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM6");

            entity.Property(e => e.Descfixomargem7)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM7");

            entity.Property(e => e.Descfixomargem8)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM8");

            entity.Property(e => e.Descfixomargem9)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOMARGEM9");

            entity.Property(e => e.Descfixopreco10)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO10");

            entity.Property(e => e.Descfixopreco11)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO11");

            entity.Property(e => e.Descfixopreco2)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO2");

            entity.Property(e => e.Descfixopreco3)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO3");

            entity.Property(e => e.Descfixopreco4)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO4");

            entity.Property(e => e.Descfixopreco5)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO5");

            entity.Property(e => e.Descfixopreco6)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO6");

            entity.Property(e => e.Descfixopreco7)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO7");

            entity.Property(e => e.Descfixopreco8)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO8");

            entity.Property(e => e.Descfixopreco9)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCFIXOPRECO9");

            entity.Property(e => e.Descontofixo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOFIXO");

            entity.Property(e => e.Descontomaximo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOMAXIMO");

            entity.Property(e => e.DescricaoAbrev)
                .HasMaxLength(20)
                .HasColumnName("DESCRICAO_ABREV");

            entity.Property(e => e.DestaqueAutomatico)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESTAQUE_AUTOMATICO");

            entity.Property(e => e.DiasValidade).HasColumnName("DIAS_VALIDADE");

            entity.Property(e => e.Dimensoes)
                .HasMaxLength(50)
                .HasColumnName("DIMENSOES");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtExpPalm).HasColumnName("DT_EXP_PALM");

            entity.Property(e => e.DtExpWeb).HasColumnName("DT_EXP_WEB");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtSincWeb).HasColumnName("DT_SINC_WEB");

            entity.Property(e => e.DtUltimoreajuste).HasColumnName("DT_ULTIMOREAJUSTE");

            entity.Property(e => e.ECombustivel)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("E_COMBUSTIVEL");

            entity.Property(e => e.EMedicamento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("E_MEDICAMENTO");

            entity.Property(e => e.EmDestaque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EM_DESTAQUE");

            entity.Property(e => e.EngradadoQtde)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ENGRADADO_QTDE");

            entity.Property(e => e.Estoqueminimo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ESTOQUEMINIMO");

            entity.Property(e => e.Exportar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("EXPORTAR");

            entity.Property(e => e.Extipi)
                .HasMaxLength(3)
                .HasColumnName("EXTIPI");

            entity.Property(e => e.Fabricante)
                .HasMaxLength(30)
                .HasColumnName("FABRICANTE");

            entity.Property(e => e.Foto).HasColumnName("FOTO");

            entity.Property(e => e.FreteValor)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETE_VALOR");

            entity.Property(e => e.Fretechegada)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETECHEGADA");

            entity.Property(e => e.Fretesaida)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("FRETESAIDA");

            entity.Property(e => e.Iat)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IAT");

            entity.Property(e => e.Icms)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS");

            entity.Property(e => e.IcmsAliquotaCalcDesoneracao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ICMS_ALIQUOTA_CALC_DESONERACAO");

            entity.Property(e => e.IdPromocaokit).HasColumnName("ID_PROMOCAOKIT");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.IntegraMarketplace)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INTEGRA_MARKETPLACE");

            entity.Property(e => e.Ipi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("IPI");

            entity.Property(e => e.IpiCst).HasColumnName("IPI_CST");

            entity.Property(e => e.Ippt)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("IPPT");

            entity.Property(e => e.ItemAbatedouro).HasColumnName("ITEM_ABATEDOURO");

            entity.Property(e => e.Localizacao)
                .HasMaxLength(20)
                .HasColumnName("LOCALIZACAO");

            entity.Property(e => e.LoginUltimaalteracao)
                .HasMaxLength(80)
                .HasColumnName("LOGIN_ULTIMAALTERACAO");

            entity.Property(e => e.MarcaId).HasColumnName("MARCA_ID");

            entity.Property(e => e.Margem)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM");

            entity.Property(e => e.Margem10)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM10");

            entity.Property(e => e.Margem11)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM11");

            entity.Property(e => e.Margem2)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM2");

            entity.Property(e => e.Margem3)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM3");

            entity.Property(e => e.Margem4)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM4");

            entity.Property(e => e.Margem5)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM5");

            entity.Property(e => e.Margem6)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM6");

            entity.Property(e => e.Margem7)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM7");

            entity.Property(e => e.Margem8)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM8");

            entity.Property(e => e.Margem9)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("MARGEM9");

            entity.Property(e => e.MotivoDesoneracaoIcms).HasColumnName("MOTIVO_DESONERACAO_ICMS");

            entity.Property(e => e.NaoVende)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("NAO_VENDE");

            entity.Property(e => e.NmProduto)
                .HasMaxLength(100)
                .HasColumnName("NM_PRODUTO");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.ObsInterna)
                .HasMaxLength(400)
                .HasColumnName("OBS_INTERNA");

            entity.Property(e => e.OfertaObrigatoria)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("OFERTA_OBRIGATORIA");

            entity.Property(e => e.Origem).HasColumnName("ORIGEM");

            entity.Property(e => e.PdvPrecovenda)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PDV_PRECOVENDA");

            entity.Property(e => e.Pesobruto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOBRUTO");

            entity.Property(e => e.Pesoliquido)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PESOLIQUIDO");

            entity.Property(e => e.Pis)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PIS");

            entity.Property(e => e.PisCst).HasColumnName("PIS_CST");

            entity.Property(e => e.PorcPerdaEstoque)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PORC_PERDA_ESTOQUE");

            entity.Property(e => e.PossuiDimensoes)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("POSSUI_DIMENSOES");

            entity.Property(e => e.Preco10)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO10");

            entity.Property(e => e.Preco11)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO11");

            entity.Property(e => e.Preco2)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO2");

            entity.Property(e => e.Preco3)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO3");

            entity.Property(e => e.Preco4)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO4");

            entity.Property(e => e.Preco5)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO5");

            entity.Property(e => e.Preco6)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO6");

            entity.Property(e => e.Preco7)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO7");

            entity.Property(e => e.Preco8)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO8");

            entity.Property(e => e.Preco9)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECO9");

            entity.Property(e => e.Precocusto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTO");

            entity.Property(e => e.Precocustoanterior)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOCUSTOANTERIOR");

            entity.Property(e => e.Precopropeso)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PRECOPROPESO");

            entity.Property(e => e.Precovenda)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOVENDA");

            entity.Property(e => e.Precovendaanterior)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("PRECOVENDAANTERIOR");
             

            entity.Property(e => e.Qbcmonoret)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QBCMONORET");

            entity.Property(e => e.Quanttroca)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("QUANTTROCA");

            entity.Property(e => e.ReducaoBaseCalculo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("REDUCAO_BASE_CALCULO");

            entity.Property(e => e.RefPromocao).HasColumnName("REF_PROMOCAO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Substtributaria)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SUBSTTRIBUTARIA");

           

            entity.Property(e => e.Tipocusto)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TIPOCUSTO");

            entity.Property(e => e.Trescasas)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("TRESCASAS");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Ultimocusto)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ULTIMOCUSTO");

            entity.Property(e => e.Ultimofrete)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ULTIMOFRETE");

            entity.Property(e => e.Ultimoicmsst)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ULTIMOICMSST");

            entity.Property(e => e.Ultimoipi)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ULTIMOIPI");

            entity.Property(e => e.Ultimooutros)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ULTIMOOUTROS");

            entity.Property(e => e.Ultimoseguro)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("ULTIMOSEGURO");

            entity.Property(e => e.UndFracionada)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("UND_FRACIONADA");

            entity.Property(e => e.Undconversaoentrada)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("UNDCONVERSAOENTRADA");

            entity.Property(e => e.Unidade)
                .HasColumnType("CHAR(3) ")
                .HasColumnName("UNIDADE");

            entity.Property(e => e.Usaestoquecompartilhado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("USAESTOQUECOMPARTILHADO");

            entity.Property(e => e.VariacaoId).HasColumnName("VARIACAO_ID");

            entity.Property(e => e.WebId).HasColumnName("WEB_ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Produtos> entity);
    }
}
