// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdfornecConfiguration : IEntityTypeConfiguration<Prodfornec>
    {
        public void Configure(EntityTypeBuilder<Prodfornec> entity)
        {
            entity.HasKey(e => new { e.CdFornecedor, e.CdProduto })
                .HasName("PK_PRODFORN");

            entity.ToTable("PRODFORNEC");

            entity.HasIndex(e => new { e.CdProduto, e.CdFornecedor }, "PK_PRODFORN")
                .IsUnique();

            entity.HasIndex(e => e.CdFornecedor, "PRODFORNEC_IDX1");

            entity.HasIndex(e => e.CodProdFornec, "PRODFORNEC_IDX2");

            entity.Property(e => e.CdFornecedor).HasColumnName("CD_FORNECEDOR");

            entity.Property(e => e.CdProduto).HasColumnName("CD_PRODUTO");

            entity.Property(e => e.CdGrade).HasColumnName("CD_GRADE");

            entity.Property(e => e.CdUltimanota).HasColumnName("CD_ULTIMANOTA");

            entity.Property(e => e.CodProdFornec)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("COD_PROD_FORNEC");

            entity.Property(e => e.DtUltimacompra)
                .HasColumnType("DATE")
                .HasColumnName("DT_ULTIMACOMPRA");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Prodfornec> entity);
    }
}
