// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class ProdutosMarketplaceConfiguration : IEntityTypeConfiguration<ProdutosMarketplace>
    {
        public void Configure(EntityTypeBuilder<ProdutosMarketplace> entity)
        {
            entity.HasKey(e => new { e.Id, e.ProdutoId });

            entity.ToTable("PRODUTOS_MARKETPLACE");

            entity.HasIndex(e => new { e.Id, e.ProdutoId }, "PK_PRODUTOS_MARKETPLACE")
                .IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.Property(e => e.ProdutoId).HasColumnName("PRODUTO_ID");

            entity.Property(e => e.Altura).HasColumnName("ALTURA");

            entity.Property(e => e.CategoriaId).HasColumnName("CATEGORIA_ID");

            entity.Property(e => e.Comprimento).HasColumnName("COMPRIMENTO");

            entity.Property(e => e.Descricao).HasColumnName("DESCRICAO");

            entity.Property(e => e.Destaque)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DESTAQUE");

            entity.Property(e => e.Digital)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DIGITAL");

            entity.Property(e => e.DisponibilidadeDias).HasColumnName("DISPONIBILIDADE_DIAS");

            entity.Property(e => e.DtLancamento).HasColumnName("DT_LANCAMENTO");

            entity.Property(e => e.Ean)
                .HasMaxLength(120)
                .HasColumnName("EAN");

            entity.Property(e => e.EstoqueTaxa).HasColumnName("ESTOQUE_TAXA");

            entity.Property(e => e.Garantia)
                .HasMaxLength(100)
                .HasColumnName("GARANTIA");

            entity.Property(e => e.Indisponivel)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INDISPONIVEL");

            entity.Property(e => e.ItensInclusos)
                .HasMaxLength(200)
                .HasColumnName("ITENS_INCLUSOS");

            entity.Property(e => e.Lancamento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("LANCAMENTO");

            entity.Property(e => e.Largura).HasColumnName("LARGURA");

            entity.Property(e => e.MensagemAdicional)
                .HasMaxLength(200)
                .HasColumnName("MENSAGEM_ADICIONAL");

            entity.Property(e => e.Modelo)
                .HasMaxLength(100)
                .HasColumnName("MODELO");

            entity.Property(e => e.PalavrasChave).HasColumnName("PALAVRAS_CHAVE");

            entity.Property(e => e.Peso).HasColumnName("PESO");

            entity.Property(e => e.PrecoPromocionalTaxa).HasColumnName("PRECO_PROMOCIONAL_TAXA");

            entity.Property(e => e.PrecoSobConsulta)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PRECO_SOB_CONSULTA");

            entity.Property(e => e.PrecoVendaTaxa).HasColumnName("PRECO_VENDA_TAXA");

            entity.Property(e => e.PromocaoFim).HasColumnName("PROMOCAO_FIM");

            entity.Property(e => e.PromocaoInicio).HasColumnName("PROMOCAO_INICIO");

            entity.Property(e => e.TrayId).HasColumnName("TRAY_ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProdutosMarketplace> entity);
    }
}
