// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class TerminaisRefConfiguration : IEntityTypeConfiguration<TerminaisRef>
    {
        public void Configure(EntityTypeBuilder<TerminaisRef> entity)
        {
            entity.HasKey(e => e.NumTerminal);

            entity.ToTable("TERMINAIS_REF");

            entity.HasIndex(e => e.NumTerminal, "PK_TERMINAIS_REF")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.UltimaExportacao).HasColumnName("ULTIMA_EXPORTACAO");

            entity.Property(e => e.UltimaImportacao).HasColumnName("ULTIMA_IMPORTACAO");

            entity.Property(e => e.UltimaSincCompleta).HasColumnName("ULTIMA_SINC_COMPLETA");

            entity.Property(e => e.UltimaSincParcial).HasColumnName("ULTIMA_SINC_PARCIAL");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Ultimoacesso).HasColumnName("ULTIMOACESSO");

            entity.Property(e => e.Ultimooperador)
                .HasMaxLength(10)
                .HasColumnName("ULTIMOOPERADOR");

            entity.Property(e => e.VersaoFirebird)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_FIREBIRD");

            entity.Property(e => e.VersaoFocusAnterior)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_FOCUS_ANTERIOR");

            entity.Property(e => e.VersaoFocusAtual)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_FOCUS_ATUAL");

            entity.Property(e => e.VersaoFoodAnterior)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_FOOD_ANTERIOR");

            entity.Property(e => e.VersaoFoodAtual)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_FOOD_ATUAL");

            entity.Property(e => e.VersaoNfeAnterior)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_NFE_ANTERIOR");

            entity.Property(e => e.VersaoNfeAtual)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_NFE_ATUAL");

            entity.Property(e => e.VersaoOsAnterior)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_OS_ANTERIOR");

            entity.Property(e => e.VersaoOsAtual)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_OS_ATUAL");

            entity.Property(e => e.VersaoPdvAnterior)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_PDV_ANTERIOR");

            entity.Property(e => e.VersaoPdvAtual)
                .HasMaxLength(10)
                .HasColumnName("VERSAO_PDV_ATUAL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TerminaisRef> entity);
    }
}
