// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class TerminaisLigadosConfiguration : IEntityTypeConfiguration<TerminaisLigados>
    {
        public void Configure(EntityTypeBuilder<TerminaisLigados> entity)
        {
            entity.HasKey(e => e.NumTerminal);

            entity.ToTable("TERMINAIS_LIGADOS");

            entity.HasIndex(e => e.NumTerminal, "PK_TERMINAIS_LIGADOS")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.Derrubar)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DERRUBAR");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Login)
                .HasMaxLength(80)
                .HasColumnName("LOGIN");

            entity.Property(e => e.Quandoligou).HasColumnName("QUANDOLIGOU");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimoping).HasColumnName("ULTIMOPING");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TerminaisLigados> entity);
    }
}
