// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class TerminaisConfiguration : IEntityTypeConfiguration<Terminais>
    {
        public void Configure(EntityTypeBuilder<Terminais> entity)
        {
            entity.HasKey(e => e.NumTerminal);

            entity.ToTable("TERMINAIS");

            entity.HasIndex(e => e.NumTerminal, "PK_TERMINAIS")
                .IsUnique();

            entity.HasIndex(e => e.Serialunico, "UNQ1_TERMINAIS")
                .IsUnique();

            entity.Property(e => e.NumTerminal).HasColumnName("NUM_TERMINAL");

            entity.Property(e => e.CdArea).HasColumnName("CD_AREA");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.Descricao)
                .HasMaxLength(100)
                .HasColumnName("DESCRICAO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.Serialunico)
                .HasMaxLength(150)
                .HasColumnName("SERIALUNICO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Terminais> entity);
    }
}
