// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class TipoprecoConfiguration : IEntityTypeConfiguration<Tipopreco>
    {
        public void Configure(EntityTypeBuilder<Tipopreco> entity)
        {
            entity.HasKey(e => e.CdTipopreco);

            entity.ToTable("TIPOPRECO");

            entity.HasIndex(e => e.CdTipopreco, "PK_TIPOPRECO")
                .IsUnique();

            entity.Property(e => e.CdTipopreco).HasColumnName("CD_TIPOPRECO");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.Descontofixo)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DESCONTOFIXO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.NmTipopreco)
                .HasMaxLength(80)
                .HasColumnName("NM_TIPOPRECO");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.OpMargem)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("OP_MARGEM");

            entity.Property(e => e.OpMargemxpreco)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("OP_MARGEMXPRECO");

            entity.Property(e => e.OpPreco)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("OP_PRECO");

            entity.Property(e => e.PermiteDescAutPagamento)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITE_DESC_AUT_PAGAMENTO");

            entity.Property(e => e.PermiteVendaComcliente)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITE_VENDA_COMCLIENTE");

            entity.Property(e => e.PermiteVendaSomentepj)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("PERMITE_VENDA_SOMENTEPJ");

            entity.Property(e => e.QtdMinimaProdutos).HasColumnName("QTD_MINIMA_PRODUTOS");

            entity.Property(e => e.Referenciamargem)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("REFERENCIAMARGEM");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Valormargem)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALORMARGEM");

            entity.Property(e => e.Valorminimo).HasColumnName("VALORMINIMO");

            entity.Property(e => e.Valorpreco)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("VALORPRECO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tipopreco> entity);
    }
}
