// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class UnidadeConfiguration : IEntityTypeConfiguration<Unidade>
    {
        public void Configure(EntityTypeBuilder<Unidade> entity)
        {
            entity.HasKey(e => e.CdUnidade);

            entity.ToTable("UNIDADE");

            entity.HasIndex(e => e.CdUnidade, "PK_UNIDADE")
                .IsUnique();

            entity.HasIndex(e => e.Sigla, "UNIDADE_IDX1");

            entity.Property(e => e.CdUnidade).HasColumnName("CD_UNIDADE");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.NmUnidade)
                .HasMaxLength(80)
                .HasColumnName("NM_UNIDADE");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.Sigla)
                .HasMaxLength(3)
                .HasColumnName("SIGLA");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Unidade> entity);
    }
}
