// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class UsuariosRefConfiguration : IEntityTypeConfiguration<UsuariosRef>
    {
        public void Configure(EntityTypeBuilder<UsuariosRef> entity)
        {
            entity.HasKey(e => e.CdUsuario);

            entity.ToTable("USUARIOS_REF");

            entity.HasIndex(e => e.CdUsuario, "PK_USUARIOS_REF")
                .IsUnique();

            entity.Property(e => e.CdUsuario).HasColumnName("CD_USUARIO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            entity.Property(e => e.Ultimologin).HasColumnName("ULTIMOLOGIN");

            entity.Property(e => e.Ultimoorcamento).HasColumnName("ULTIMOORCAMENTO");

            entity.Property(e => e.Ultimopedido).HasColumnName("ULTIMOPEDIDO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsuariosRef> entity);
    }
}
