// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class UsuariosConfiguration : IEntityTypeConfiguration<Usuarios>
    {
        public void Configure(EntityTypeBuilder<Usuarios> entity)
        {
            entity.HasKey(e => e.CdUsuario);

            entity.ToTable("USUARIOS");

            entity.HasIndex(e => e.Inativo, "IDX_USUINATIVO");

            entity.HasIndex(e => e.CdUsuario, "PK_USUARIOS")
                .IsUnique();

            entity.HasIndex(e => e.Login, "USUARIOS_IDX1");

            entity.Property(e => e.CdUsuario).HasColumnName("CD_USUARIO");

            entity.Property(e => e.Apelido)
                .HasMaxLength(60)
                .HasColumnName("APELIDO");

            entity.Property(e => e.Cargahoraria).HasColumnName("CARGAHORARIA");

            entity.Property(e => e.Cargo)
                .HasMaxLength(40)
                .HasColumnName("CARGO");

            entity.Property(e => e.CdSetor).HasColumnName("CD_SETOR");

            entity.Property(e => e.CdUsuarioCategoria).HasColumnName("CD_USUARIO_CATEGORIA");

            entity.Property(e => e.Celular)
                .HasMaxLength(70)
                .HasColumnName("CELULAR");

            entity.Property(e => e.Comissao)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMISSAO");

            entity.Property(e => e.ComissaoFaixa).HasColumnName("COMISSAO_FAIXA");

            entity.Property(e => e.ComissaoServ)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("COMISSAO_SERV");

            entity.Property(e => e.Conjuge)
                .HasMaxLength(40)
                .HasColumnName("CONJUGE");

            entity.Property(e => e.Cpf)
                .HasMaxLength(18)
                .HasColumnName("CPF");

            entity.Property(e => e.CtpsN)
                .HasMaxLength(6)
                .HasColumnName("CTPS_N");

            entity.Property(e => e.CtpsSerie)
                .HasMaxLength(7)
                .HasColumnName("CTPS_SERIE");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.Demitido)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DEMITIDO");

            entity.Property(e => e.Dependentes).HasColumnName("DEPENDENTES");

            entity.Property(e => e.DpSalarioatual)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("DP_SALARIOATUAL");

            entity.Property(e => e.DtAdmissao)
                .HasColumnType("DATE")
                .HasColumnName("DT_ADMISSAO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtCasamento)
                .HasColumnType("DATE")
                .HasColumnName("DT_CASAMENTO");

            entity.Property(e => e.DtDemissao)
                .HasColumnType("DATE")
                .HasColumnName("DT_DEMISSAO");

            entity.Property(e => e.DtExpPalm).HasColumnName("DT_EXP_PALM");

            entity.Property(e => e.DtNascimento)
                .HasColumnType("DATE")
                .HasColumnName("DT_NASCIMENTO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.DtSincSeller).HasColumnName("DT_SINC_SELLER");

            entity.Property(e => e.DtUltimaImpressaoItensPed).HasColumnName("DT_ULTIMA_IMPRESSAO_ITENS_PED");

            entity.Property(e => e.EMotorista)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("E_MOTORISTA");

            entity.Property(e => e.ETecnico)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("E_TECNICO");

            entity.Property(e => e.EUsuario)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("E_USUARIO");

            entity.Property(e => e.EVendedor)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("E_VENDEDOR");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("EMAIL");

            entity.Property(e => e.EndBairro)
                .HasMaxLength(35)
                .HasColumnName("END_BAIRRO");

            entity.Property(e => e.EndCdMunicipio).HasColumnName("END_CD_MUNICIPIO");

            entity.Property(e => e.EndCdPais).HasColumnName("END_CD_PAIS");

            entity.Property(e => e.EndCep)
                .HasMaxLength(9)
                .HasColumnName("END_CEP");

            entity.Property(e => e.EndComplemento)
                .HasMaxLength(60)
                .HasColumnName("END_COMPLEMENTO");

            entity.Property(e => e.EndLogradouro)
                .HasMaxLength(60)
                .HasColumnName("END_LOGRADOURO");

            entity.Property(e => e.EndNmMunicipio)
                .HasMaxLength(35)
                .HasColumnName("END_NM_MUNICIPIO");

            entity.Property(e => e.EndNumero)
                .HasMaxLength(20)
                .HasColumnName("END_NUMERO");

            entity.Property(e => e.EndReferencia)
                .HasMaxLength(200)
                .HasColumnName("END_REFERENCIA");

            entity.Property(e => e.EndUf)
                .HasColumnType("CHAR(2) ")
                .HasColumnName("END_UF");

            entity.Property(e => e.Estcivil)
                .HasMaxLength(10)
                .HasColumnName("ESTCIVIL");

            entity.Property(e => e.Fax)
                .HasMaxLength(70)
                .HasColumnName("FAX");

            entity.Property(e => e.Foto).HasColumnName("FOTO");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.Login)
                .HasMaxLength(80)
                .HasColumnName("LOGIN");

            entity.Property(e => e.LoginPassword)
                .HasMaxLength(400)
                .HasColumnName("LOGIN_PASSWORD");

            entity.Property(e => e.Menupersonalizado)
                .HasMaxLength(1000)
                .HasColumnName("MENUPERSONALIZADO");

            entity.Property(e => e.Motivodemissao)
                .HasMaxLength(100)
                .HasColumnName("MOTIVODEMISSAO");

            entity.Property(e => e.Multisessao)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("MULTISESSAO");

            entity.Property(e => e.NmMae)
                .HasMaxLength(80)
                .HasColumnName("NM_MAE");

            entity.Property(e => e.NmPai)
                .HasMaxLength(80)
                .HasColumnName("NM_PAI");

            entity.Property(e => e.NmUsuario)
                .HasMaxLength(80)
                .HasColumnName("NM_USUARIO");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.Pis)
                .HasMaxLength(18)
                .HasColumnName("PIS");

            entity.Property(e => e.Referencia)
                .HasMaxLength(40)
                .HasColumnName("REFERENCIA");

            entity.Property(e => e.Rg)
                .HasMaxLength(15)
                .HasColumnName("RG");

            entity.Property(e => e.Salario)
                .HasColumnType("DECIMAL(18,3)")
                .HasColumnName("SALARIO");

            entity.Property(e => e.Seller)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SELLER");

            entity.Property(e => e.Sexo)
                .HasMaxLength(4)
                .HasColumnName("SEXO");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Telefone)
                .HasMaxLength(70)
                .HasColumnName("TELEFONE");

            entity.Property(e => e.TempoSessaoInativa).HasColumnName("TEMPO_SESSAO_INATIVA");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Usuarios> entity);
    }
}
