// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus.Configurations
{
    public partial class UsuariosCategoriaConfiguration : IEntityTypeConfiguration<UsuariosCategoria>
    {
        public void Configure(EntityTypeBuilder<UsuariosCategoria> entity)
        {
            entity.HasKey(e => e.CdUsuariocategoria);

            entity.ToTable("USUARIOS_CATEGORIA");

            entity.HasIndex(e => e.CdUsuariocategoria, "PK_USUARIOS_CATEGORIA")
                .IsUnique();

            entity.Property(e => e.CdUsuariocategoria).HasColumnName("CD_USUARIOCATEGORIA");

            entity.Property(e => e.Cor).HasColumnName("COR");

            entity.Property(e => e.Deletado)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("DELETADO");

            entity.Property(e => e.DeletadoDatahora).HasColumnName("DELETADO_DATAHORA");

            entity.Property(e => e.DeletadoLogin)
                .HasMaxLength(80)
                .HasColumnName("DELETADO_LOGIN");

            entity.Property(e => e.Descricao)
                .HasMaxLength(200)
                .HasColumnName("DESCRICAO");

            entity.Property(e => e.DtCadastro).HasColumnName("DT_CADASTRO");

            entity.Property(e => e.DtSincFocus).HasColumnName("DT_SINC_FOCUS");

            entity.Property(e => e.Inativo)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("INATIVO");

            entity.Property(e => e.NmUsuariocategoria)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("NM_USUARIOCATEGORIA");

            entity.Property(e => e.Obs).HasColumnName("OBS");

            entity.Property(e => e.Sincronizando)
                .HasColumnType("CHAR(1) ")
                .HasColumnName("SINCRONIZANDO");

            entity.Property(e => e.Ultimaalteracao).HasColumnName("ULTIMAALTERACAO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsuariosCategoria> entity);
    }
}
