// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class CaixaSituacao
    {
        public short NumTerminal { get; set; }
        public string Situacao { get; set; }
        public DateTime? DtAbertura { get; set; }
        public DateTime? DtUltFechamento { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
    }
}