// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    /// <summary>
    /// Esta tabela contém apenas os Caixas Fechados.
    /// Os valores dos Caixas Abertos são obtidos através da soma dos Eventos.
    /// </summary>
    public partial class Caixa
    {
        public short NumTerminal { get; set; }
        public DateTime DtAbertura { get; set; }
        public DateTime DtFechamento { get; set; }
        public string OrigemAbertura { get; set; }
        public string Obs { get; set; }
        public string LoginFechamento { get; set; }
        public string ObsFechamento { get; set; }
        public decimal? Fundotroco { get; set; }
        public decimal? VenDinheiro { get; set; }
        public decimal? VenChequeAto { get; set; }
        public decimal? VenChequePre { get; set; }
        public decimal? VenTickets { get; set; }
        public decimal? VenCredcli { get; set; }
        public decimal? VenCrediarios { get; set; }
        public decimal? VenCartaoCred { get; set; }
        public decimal? VenCartaoDeb { get; set; }
        public decimal? VenCartaoParc { get; set; }
        public decimal? VendasVal { get; set; }
        public decimal? GavDinheiro { get; set; }
        public decimal? GavChequeAto { get; set; }
        public decimal? GavChequePre { get; set; }
        public decimal? GavTickets { get; set; }
        public decimal? GavCrediarios { get; set; }
        public decimal? GavCartaoCred { get; set; }
        public decimal? GavCartaoDeb { get; set; }
        public decimal? GavCartaoParc { get; set; }
        public decimal? SangriaVal { get; set; }
        public short? SangriaQtd { get; set; }
        public decimal? SuprimentoVal { get; set; }
        public short? SuprimentoQtd { get; set; }
        public decimal? AcrescimosVal { get; set; }
        public short? AcrescimosQtd { get; set; }
        public decimal? DescontosVal { get; set; }
        public short? DescontosQtd { get; set; }
        public decimal? DescontosUnitVal { get; set; }
        public short? DescontosUnitQtd { get; set; }
        public decimal? DevolucoesVal { get; set; }
        public short? DevolucoesQtd { get; set; }
        public decimal? ContasrecebVal { get; set; }
        public short? ContasrecebQtd { get; set; }
        public decimal? CancelVendasVal { get; set; }
        public short? CancelVendasQtd { get; set; }
        public decimal? CancelPedidosVal { get; set; }
        public short? CancelPedidosQtd { get; set; }
        public decimal? CancelItensVal { get; set; }
        public short? CancelItensQtd { get; set; }
        public short? QtdeConsultas { get; set; }
        public string Deletado { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Reducaoz { get; set; }
        public decimal? EstVendasQtde { get; set; }
        public decimal? EstVendasMaiorvlr { get; set; }
        public decimal? EstVendasMenorvlr { get; set; }
        public decimal? EstItensQtde { get; set; }
        public decimal? EstItensMaiorvlr { get; set; }
        public decimal? EstItensMenorvlr { get; set; }
        public decimal? EstPecasQtde { get; set; }
        public decimal? EstPecasMaiorvlr { get; set; }
        public decimal? EstPecasMenorvlr { get; set; }
        public decimal? GavCredcli { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
        public decimal? ConfDinheiro { get; set; }
        public decimal? ConfCheque { get; set; }
        public decimal? ConfTickets { get; set; }
        public decimal? ConfCrediarios { get; set; }
        public decimal? ConfCartao { get; set; }
        public decimal? ConfCredcli { get; set; }
        public string OrigemFechamento { get; set; }
        public decimal? AcrescimoUnitVal { get; set; }
        public int? AcrescimoUnitQtd { get; set; }
        public int? ConfQtdeMoeda01 { get; set; }
        public int? ConfQtdeMoeda5 { get; set; }
        public int? ConfQtdeMoeda10 { get; set; }
        public int? ConfQtdeMoeda25 { get; set; }
        public int? ConfQtdeMoeda50 { get; set; }
        public int? ConfQtdeMoeda1 { get; set; }
        public int? ConfQtdeCedula100 { get; set; }
        public int? ConfQtdeCedula50 { get; set; }
        public int? ConfQtdeCedula20 { get; set; }
        public int? ConfQtdeCedula10 { get; set; }
        public int? ConfQtdeCedula5 { get; set; }
        public int? ConfQtdeCedula2 { get; set; }
        public decimal? VenMoedasocial { get; set; }
        public decimal? GavMoedasocial { get; set; }
        public decimal? VenOutros { get; set; }
        public decimal? GavOutros { get; set; }
    }
}