// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class CaixaEventos
    {
        public short NumTerminal { get; set; }
        public DateTime DtEvento { get; set; }
        public string Origem { get; set; }
        public short CodEvento { get; set; }
        public string Evento { get; set; }
        public decimal? Valor { get; set; }
        public string Obs { get; set; }
        public string Login { get; set; }
        public decimal? RefDinheiro { get; set; }
        public decimal? RefChequeAto { get; set; }
        public decimal? RefChequePre { get; set; }
        public decimal? RefCartaoCred { get; set; }
        public decimal? RefCartaoDeb { get; set; }
        public decimal? RefCartaoParc { get; set; }
        public decimal? RefTickets { get; set; }
        public decimal? RefCrediario { get; set; }
        public decimal? RefCredcli { get; set; }
        public string Especie { get; set; }
        public decimal? AcrescimosVal { get; set; }
        public decimal? DescontosVal { get; set; }
        public decimal? DescontosUnitVal { get; set; }
        public short? DescontosUnitQtd { get; set; }
        public int? QtdeItens { get; set; }
        public int? QtdePecas { get; set; }
        public int? CdCliente { get; set; }
        public int? NumDocServer { get; set; }
        public int? NumDocLocal { get; set; }
        public int? CrId { get; set; }
        public int? DevolucaoId { get; set; }
        public string Deletado { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public DateTime? RefCaixaDtAbertura { get; set; }
        public string DescontarCaixa { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string RegEcf { get; set; }
        public decimal? ItemMaiorValor { get; set; }
        public decimal? ItemMenorValor { get; set; }
        public decimal? PecaMaiorValor { get; set; }
        public decimal? PecaMenorValor { get; set; }
        public string Historico { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
        public string Cancelado { get; set; }
        public int? NumDocOrdem { get; set; }
        public decimal? AcrescimoUnitVal { get; set; }
        public int? AcrescimoUnitQtd { get; set; }
        public decimal? RefMoedasocial { get; set; }
        public decimal? RefOutros { get; set; }
    }
}