// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class CestNcm
    {
        public int Id { get; set; }
        public string Cest { get; set; }
        public string Ncm { get; set; }
        public string Obs { get; set; }
    }
}