// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ClienteComputador
    {
        public int Id { get; set; }
        public string Ip { get; set; }
        public DateTime? DataSincronia { get; set; }
        public string NomeFisico { get; set; }
        public string NomeFocus { get; set; }
        public string WindowsVersao { get; set; }
        public string FirebirdVersao { get; set; }
        public string AntivirusNome { get; set; }
        public DateTime DataApuracao { get; set; }
    }
}