// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ClienteGrupos
    {
        public int CdClienteGrupos { get; set; }
        public string NmClienteGrupos { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public string Deletado { get; set; }
        public string Inativo { get; set; }
        public string Obs { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
    }
}