// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ClienteComputadorSistema
    {
        public int ComputadorId { get; set; }
        public int SistemaId { get; set; }
        public DateTime? DataSincronia { get; set; }
        public DateTime UltimoAcesso { get; set; }
        public string Versao { get; set; }
    }
}