// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ClienteCategoriasFormpag
    {
        public int CdClienteCategoria { get; set; }
        public int CdFormapagamento { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public decimal? FaixaInicial { get; set; }
        public decimal? FaixaFinal { get; set; }
    }
}