// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ClienteComputadorDisco
    {
        public int Id { get; set; }
        public int? ComputadorId { get; set; }
        public string Disco { get; set; }
        public float? EspacoDisponivel { get; set; }
        public float? EspacoTotal { get; set; }
        public DateTime? DataApuracao { get; set; }
        public DateTime? DataSincronia { get; set; }
    }
}