// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ClientesRef
    {
        public int CdCliente { get; set; }
        public DateTime? DtUltimacompra { get; set; }
        public string Bloqueado { get; set; }
        public string Bloqueiomanual { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public short? Maioratraso { get; set; }
        public decimal? Creditoaberto { get; set; }
        public decimal? Saldodadivida { get; set; }
        public decimal? Dividavencida { get; set; }
        public decimal? Dividaavencer { get; set; }
        public int? Pontuacaoatual { get; set; }
        public int? Pontuacaototal { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public decimal? Dividasemjuros { get; set; }
        public decimal? Juros { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public DateTime? DtUltimoservico { get; set; }
        public int? ProgFidelidadePontos { get; set; }
        public DateTime? DtBloqueado { get; set; }
    }
}