// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Clientes
    {
        public int CdCliente { get; set; }
        public string NmCliente { get; set; }
        public string Apelido { get; set; }
        public string Email { get; set; }
        public DateTime? DtNascimento { get; set; }
        public string Conjuge { get; set; }
        public DateTime? DtCasamento { get; set; }
        public string EndLogradouro { get; set; }
        public string EndBairro { get; set; }
        public string EndNmMunicipio { get; set; }
        public string EndUf { get; set; }
        public string EndCep { get; set; }
        public string Telefone { get; set; }
        public string Fax { get; set; }
        public string RgIe { get; set; }
        public string CpfCnpj { get; set; }
        public string ProfProfissao { get; set; }
        public string ProfEmpresa { get; set; }
        public string ProfTelefone { get; set; }
        public string ProfFax { get; set; }
        public string ProfEmail { get; set; }
        public string ProfSite { get; set; }
        public string NmPai { get; set; }
        public string NmMae { get; set; }
        public string Referencia1 { get; set; }
        public string Referencia2 { get; set; }
        public decimal? Limitecredito { get; set; }
        public short? Prazopagamento { get; set; }
        public decimal? AtrasoJurosaodia { get; set; }
        public string Pessoa { get; set; }
        public string Website { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtCadastro { get; set; }
        public string Obs { get; set; }
        public string Contato { get; set; }
        public string ImpSaldodivida { get; set; }
        public string BloqAutomatico { get; set; }
        public int? CdVendedor { get; set; }
        public string Exportar { get; set; }
        public string Condicoespagamento { get; set; }
        public int? CdPraca { get; set; }
        public string Lembrete { get; set; }
        public string Inativo { get; set; }
        public string Refbanco { get; set; }
        public string EndReferencia { get; set; }
        public DateTime? DtExpPalm { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public int? CdClienteCategoria { get; set; }
        public string CondicoesPersonalizadas { get; set; }
        public decimal? AtrasoMulta { get; set; }
        public byte[] Foto { get; set; }
        public string EndNumero { get; set; }
        public string EndComplemento { get; set; }
        public int? EndCdMunicipio { get; set; }
        public string Estcivil { get; set; }
        public string Sexo { get; set; }
        public int? EndCdPais { get; set; }
        public string Suframa { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public int? CdClienteSeller { get; set; }
        public string TipoCliente { get; set; }
        public string AcresDescEspecial { get; set; }
        public string Deletado { get; set; }
        public string ProfEndereco { get; set; }
        public string Spc { get; set; }
        public string SpcNumero { get; set; }
        public DateTime? SpcData { get; set; }
        public string Referencia3 { get; set; }
        public string TelRef1 { get; set; }
        public string TelRef2 { get; set; }
        public string TelRef3 { get; set; }
        public short? Crt { get; set; }
        public string InscMunicipal { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string Celular { get; set; }
        public string Selecionado { get; set; }
        public string TipoContribIcms { get; set; }
        public int? CdClienteGrupos { get; set; }
        public string BloqAutoImune { get; set; }
        public string IdSellerWeb { get; set; }
        public string IeCpf { get; set; }
        public int? CdTipoPreco { get; set; } 
        public string Sincronizado { get; set; }
        public string ObsCobranca { get; set; }
        public int? TrayId { get; set; }
        public DateTime? DtSincMarketplace { get; set; }
        public string EnviarEmailAniversario { get; set; }
    }
}