// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ClienteUsuario
    {
        public int ClienteId { get; set; }
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Ativo { get; set; }
        public string Email { get; set; }
        public DateTime? DataSincronia { get; set; }
        public DateTime? UltimoAcesso { get; set; }
    }
}