// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ConfigSincronizacao
    {
        public int? Id { get; set; }
        public string Caminho { get; set; }
        public string Ip { get; set; }
        public string Porta { get; set; }
        public DateTime? Ultimasinccliente { get; set; }
        public DateTime? Ultimasincusuarios { get; set; }
        public DateTime? Ultimasincclientecategoria { get; set; }
        public DateTime? Ultimasincformaspagamento { get; set; }
        public string Ativado { get; set; }
        public DateTime? Ultimasincfornecedor { get; set; }
        public DateTime? Ultimasincfaixadesconto { get; set; }
    }
}