// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ConfigEmpresaConsulta
    {
        public int Id { get; set; }
        public string Loja { get; set; }
        public string Caminho { get; set; }
        public string Porta { get; set; }
        public string Ip { get; set; }
    }
}