// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ConfigPedido
    {
        public int Id { get; set; }
        public string Ocultaclientesbloq { get; set; }
        public string Ocultaclientesbloqman { get; set; }
        public string Mostramargemlucro { get; set; }
        public string Exibmargemlucro { get; set; }
        public string Pedirtipopreco { get; set; }
        public string Pedirdataentrega { get; set; }
        public string Mostrarbotoespeso { get; set; }
        public string Pedirnumpedido { get; set; }
        public string Pedirdespesa { get; set; }
        public short? Quantmaxitens { get; set; }
        public string Pedirordem { get; set; }
        public string Pedirdataabertura { get; set; }
        public string Pedircategoria { get; set; }
        public short? Categoriapadrao { get; set; }
        public string Pedirfrete { get; set; }
        public string Incluirfretenascontas { get; set; }
        public string Numserieobrigatorio { get; set; }
        public string Permitirvalorzerado { get; set; }
        public string Indicardimensoesitens { get; set; }
        public decimal? DescMaxDoc { get; set; }
        public decimal? DescMaxItem { get; set; }
        public short? Tipodescmaxitem { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public short? AcaoAltSubtotal { get; set; }
        public string PassaCampoQuantidade { get; set; }
        public string PassaCampoPreco { get; set; }
        public string PassaCampoDimensoes { get; set; }
        public string PassaCampoDesconto { get; set; }
        public string PassaCampoSubtotal { get; set; }
        public string AltCampoPreco { get; set; }
        public string AltCampoDesconto { get; set; }
        public string AltCampoSubtotal { get; set; }
        public string Quantidadefracionada { get; set; }
        public string DescmaxConsdescunit { get; set; }
        public string PdvExibetroco { get; set; }
        public string PdvExibefinalOrcped { get; set; }
        public string PdvMsgFinalVenda { get; set; }
        public string PdvMsgFinalOrcped { get; set; }
        public string ItemEstoqueNegativo { get; set; }
        public string ItemDataExpirada { get; set; }
        public int? ItemDataExpiradaDias { get; set; }
        public short? ItemDataExpiradaTipo { get; set; }
        public string BloqItemSemEstoque { get; set; }
        public string CalculaSt { get; set; }
        public string CorDestaqueSt { get; set; }
        public string PdvPesquisarproduto { get; set; }
        public string PdvSoarbeep { get; set; }
        public string PdvCadastrarcliente { get; set; }
        public string PdvPedirvendedor { get; set; }
        public string PdvAbrecupomcodbarras { get; set; }
        public string PdvImpAuto { get; set; }
        public string PdvImpAutocond { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string ModoCompacto { get; set; }
        public string IncluirFrete { get; set; }
        public string IncluirDespesa { get; set; }
        public string AltCampoDescricao { get; set; }
        public string VenderProdutoInativo { get; set; }
        public string SugerirObsContasXObsPedido { get; set; }
        public string PdvIncluirProdF3 { get; set; }
        public string PdvManterPedAberto { get; set; }
        public string NaoselecClientesbloq { get; set; }
        public string NaoselecClientesbloqman { get; set; }
        public string PdvImpAutoFiscal { get; set; }
        public string PdvImpAutoFiscalDinheiro { get; set; }
        public string PdvImpAutoFiscalCartao { get; set; }
        public string PdvImpAutoFiscalCheque { get; set; }
        public string PdvImpAutoFiscalCrediario { get; set; }
        public string PdvImpAutoFiscalPix { get; set; }
        public string PdvImpAutoFiscalTudo { get; set; }
        public string ExibeLembrete { get; set; }
        public string ControlaEngradados { get; set; }
        public string EngradadoTipoSaida { get; set; }
        public string ImpCestNcm { get; set; }
        public short? PdvTempoUltimaTela { get; set; }
        public string PermiteDesconto100 { get; set; }
        public string SolicitaMotivoCancelamento { get; set; }
        public string PdvSenhaSelecVendedor { get; set; }
        public string PdvImpAutoPedido { get; set; }
        public string PdvImpAutoOrcamento { get; set; }
        public string PdvImpAutoVenda { get; set; }
        public string PdvImpAutoCancelado { get; set; }
        public string UsarNmFantasiaApelido { get; set; }
        public string PermiteKitNegativo { get; set; }
        public string PdvUtilizarTpAutomatico { get; set; }
        public string PdvConcatenarDimensoes { get; set; }
        public string PdvBloqInsercaoItemPesquisa { get; set; }
        public string DefinirPesoAoInserir { get; set; }
        public string SolicitarDadosCargaObs { get; set; }
        public string PdvCadastrarProdutos { get; set; }
        public int? TabelaSincSeller { get; set; }
        public string PdvTelaimportarpedido { get; set; }
        public string VerificarPesoAoFaturar { get; set; }
        public string PdvDefinirFormaPgtoPedido { get; set; }
        public string PermiteVendaUsoInterno { get; set; }
        public string Mostrarsubtotalpdv { get; set; }
        public string DesbloquearPedidoEmAberto { get; set; }
        public string IgnorarZero { get; set; }
        public string IgnorarAsteristicoQtd { get; set; }
        public string PdvEscondermouse { get; set; }
        public string Pedirclienteaosalvarpedido { get; set; }
        public string GerarProducao { get; set; }
        public string GerarProducaoAuto { get; set; }
    }
}