// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Confimpdoc
    {
        public string Doc { get; set; }
        public string Papel { get; set; }
        public string ImpCliente { get; set; }
        public string ImpTipopreco { get; set; }
        public string ImpMensagemfinal { get; set; }
        public string ImpObs { get; set; }
        public string ImpQtdeItens { get; set; }
        public string ImpQtdeTotProd { get; set; }
        public string ImpPesototal { get; set; }
        public string ImpNumserie { get; set; }
        public string ImpFormaspagamento { get; set; }
        public string ImpVencimentos { get; set; }
        public string ImpSaldodivida { get; set; }
        public string ComprovReceb { get; set; }
        public string Mensagemfinal { get; set; }
        public string Ordenadopor { get; set; }
        public short? Numvias { get; set; }
        public string Descricaoabreviada { get; set; }
        public string BobCabecalho { get; set; }
        public string BobItens { get; set; }
        public string BobFormato { get; set; }
        public string BobNaocortadescr { get; set; }
        public string BobOmitircodigo { get; set; }
        public short? BobQuantmaxitens { get; set; }
        public string BobCompletaitensEsp { get; set; }
        public string Viacaracteres { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string ImpCabecalho { get; set; }
        public string ImpValeCrediario { get; set; }
        public string ImpJuros { get; set; }
        public string ImpReciboRecebimentos { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string ImpSeqdiario { get; set; }
        public string ImpVendedor { get; set; }
        public string BobPulalinhaitem { get; set; }
        public string ImpDataemissao { get; set; }
        public string ImpExibircodbarras { get; set; }
        public string ImpMatricial { get; set; }
        public string ImpLogotipo { get; set; }
        public string ImpNmFantasia { get; set; }
        public string ImpItemCancelado { get; set; }
        public string ImpOrientacaoLocalizao { get; set; }
        public string ImpConcatenardesc { get; set; }
        public string TipoDocNumVias { get; set; }
        public string ImpVencimentosCrediario { get; set; }
        public string ImpCodbarrasnumpedido { get; set; }
        public string ImpJuntarpedidos { get; set; }
        public string ImpExibeEstoqueLocalizacao { get; set; }
        public string ImpIndiceAtivo { get; set; }
        public string ImpCarneNumvias { get; set; }
        public string ImpIndiceFinalizarvenda { get; set; }
        public string ImpContasAbertas { get; set; }
        public string ImpNumDocVenda { get; set; }
    }
}