// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ConfigLocal
    {
        public short NumTerminal { get; set; }
        public string PdvRecebercontas { get; set; }
        public string PdvLoginautomatico { get; set; }
        public string PdvLoginautousuario { get; set; }
        public string PdvLoginautosenha { get; set; }
        public int? Tipopreco { get; set; }
        public string GerLoginautomatico { get; set; }
        public string GerLoginautousuario { get; set; }
        public string GerLoginautosenha { get; set; }
        public int? BalMarca { get; set; }
        public string BalPorta { get; set; }
        public int? BalBaudrate { get; set; }
        public int? BalDatabits { get; set; }
        public int? BalParity { get; set; }
        public int? BalStopbits { get; set; }
        public int? BalHandshaking { get; set; }
        public int? BalTimeout { get; set; }
        public string BalMonitorar { get; set; }
        public string GavModelo { get; set; }
        public string GavPorta { get; set; }
        public string GavStringlpt { get; set; }
        public string LeitAtivado { get; set; }
        public string LeitPortaserial { get; set; }
        public string LeitBaudrate { get; set; }
        public string LeitDatabits { get; set; }
        public int? LeitParity { get; set; }
        public int? LeitStopbits { get; set; }
        public int? LeitHandshake { get; set; }
        public string LeitSufixo { get; set; }
        public int? LeitIntervalo { get; set; }
        public string LeitExcluirSuf { get; set; }
        public string LeitSoftflow { get; set; }
        public string LeitHardflow { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string PdvMultiplasinstancias { get; set; }
        public string GerMultiplasinstancias { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string PdvPedido { get; set; }
        public string PdvOrcamento { get; set; }
        public string PdvImportReabre { get; set; }
        public string PdvVendaManual { get; set; }
        public string Sincronizando { get; set; }
        public short? CaixaAutoimpAbertura { get; set; }
        public short? CaixaAutoimpFechamento { get; set; }
        public short? CaixaAutoimpSangria { get; set; }
        public string PdvDocPadrao { get; set; }
        public string PdvFaturar { get; set; }
        public string PdvStatus { get; set; }
        public string CaixaSomaCredCli { get; set; }
        public string CaixaVerpedaberto { get; set; }
        public string PdvTipoFiscal { get; set; }
        public string CaixaExibesubtotaldincheq { get; set; }
        public string PdvFaturarPedidoForaPdv { get; set; }
        public string PdvFecharPedidoZerado { get; set; }
        public string PdvAbrirAutomatico { get; set; }
        public string CaixaImpCaixaCego { get; set; }
        public string PdvSalvaGridTerminal { get; set; }
        public int? PdvIndiceSomItem { get; set; }
        public DateTime? Ultimaexecintegracao { get; set; }
        public string CaixaImpValorNfceCaixa { get; set; }
        public string PdvAtivaControleFoco { get; set; }
        public string CaixaImpSangConferencia { get; set; }
        public string Desabilitartransparencia { get; set; }
        public string CaixaLancarFaltasAreceber { get; set; }
        public string CaixaLancarSobrasAreceber { get; set; }
        public int? CaixaFpgtoLancamentoAreceber { get; set; }
        public int? CaixaClientePadraoAreceber { get; set; }
        public string Permitirdescontopgtoconsumidor { get; set; }
        public string PdvUsaTef { get; set; }
        public string Usapesquisasimplificada { get; set; }
        public string ZerarMoedasAberturaCx { get; set; }
    }
}