// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ConfigCadastro
    {
        public int Id { get; set; }
        public string ProdCodigo02 { get; set; }
        public string ProdCodigo03 { get; set; }
        public string ProdCodigo04 { get; set; }
        public string ProdDescCod02 { get; set; }
        public string ProdDescCod03 { get; set; }
        public string ProdDescCod04 { get; set; }
        public string ProdCodigoEan { get; set; }
        public string Gradecampocodigo { get; set; }
        public string Gradecampodescricao { get; set; }
        public string GradeExibircodigo { get; set; }
        public string ProdExibirnumserie { get; set; }
        public string BuscaprodCodbarras { get; set; }
        public string BuscaprodCodbalanca { get; set; }
        public string BuscaprodCodgrade { get; set; }
        public string BuscaprodCodcaixa { get; set; }
        public string BuscaprodCodigo2 { get; set; }
        public string BuscaprodCodigo3 { get; set; }
        public string BuscaprodCodigo4 { get; set; }
        public string BuscaprodNumserie { get; set; }
        public short? Codprodnumdigtotal { get; set; }
        public string Codproddiginicial { get; set; }
        public string Codproddigfinal { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public int? CorEstoqueMinimo { get; set; }
        public string BuscaprodCodfornecedor { get; set; }
        public int? CorEstoqueZerado { get; set; }
        public string ExibirEstoque { get; set; }
        public short? PesqQtdeRegistros { get; set; }
        public string ProdExibirSincPreco { get; set; }
        public string ProdPesqCodigoParcial { get; set; }
        public int? CorProdEmDestaque { get; set; }
        public string PerguntaAtualizaSimilar { get; set; }
        public string CliCategoriaobrigatoria { get; set; }
        public string ExibePreco2 { get; set; }
        public string ExibePreco3 { get; set; }
        public string NomePreco2 { get; set; }
        public string NomePreco3 { get; set; }
        public string PesquisaAbreTelaCheia { get; set; }
        public string LayoutTelaProduto { get; set; }
        public string ExibirVendaMensal { get; set; }
        public string HabilitarExportacaoGas { get; set; }
        public string CodigosProdutosGas { get; set; }
        public string ExibirUltimasCompras { get; set; }
        public string Validarcadastrocliente { get; set; }
        public string ProdExibeprecoTp { get; set; }
        public decimal? Fatorcalculoestoqueminimoaut { get; set; }
        public short? Qtdmesesestoqueminimoautomatico { get; set; }
        public string CliValidaCpf { get; set; }
        public string CliValidaEndereco { get; set; }
        public string CliValidaBairro { get; set; }
        public string CliValidaCep { get; set; }
        public string CliValidaTelefone { get; set; }
        public string ExibirPrecoPromocional { get; set; }
    }
}