// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ConfigSped
    {
        public int IdCdEmpresa { get; set; }
        public string CstPis { get; set; }
        public string CstCofins { get; set; }
        public string CstIpi { get; set; }
        public int? TipoAtividade { get; set; }
        public int? PerfilSped { get; set; }
        public string CodLayout { get; set; }
    }
}