// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class DfeSerieNumeracao
    {
        public int Id { get; set; }
        public int Serie { get; set; }
        public int Numeracao { get; set; }
        public int TipoDocumento { get; set; }
        public int Ambiente { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public int? SerieExtraordinaria { get; set; }
        public int? NumeracaoExtraordinaria { get; set; }
        public int? ValorExtraordinario { get; set; }
    }
}