// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Empresas
    {
        public int CdEmpresa { get; set; }
        public string NmEmpresa { get; set; }
        public string Nomefantasia { get; set; }
        public string CpfCnpj { get; set; }
        public string RgIe { get; set; }
        public string EndLogradouro { get; set; }
        public string EndNmMunicipio { get; set; }
        public string EndBairro { get; set; }
        public string EndUf { get; set; }
        public string EndCep { get; set; }
        public string Telefone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public byte[] Logo { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtCadastro { get; set; }
        public string Obs { get; set; }
        public DateTime? DtFundacao { get; set; }
        public string Website { get; set; }
        public byte[] Logorelatorio { get; set; }
        public DateTime? DtExpWeb { get; set; }
        public string EndNumero { get; set; }
        public string EndComplemento { get; set; }
        public int? EndCdMunicipio { get; set; }
        public decimal? AliquotaPis { get; set; }
        public decimal? AliquotaCofins { get; set; }
        public decimal? AliquotaIcms { get; set; }
        public string ResponsavelNome { get; set; }
        public string ResponsavelCpf { get; set; }
        public int? EndCdPais { get; set; }
        public string InscMunicipal { get; set; }
        public string Suframa { get; set; }
        public string Inativo { get; set; }
        public string Cnaefiscal { get; set; }
        public short? Crt { get; set; }
        public string CstPadrao { get; set; }
        public decimal? Aliquotapadrao { get; set; }
        public string Slogan { get; set; }
        public string Deletado { get; set; }
        public string EndReferencia { get; set; }
        public short? TipoSimplesNacional { get; set; }
        public string EmpresaPadrao { get; set; }
        public int? CdContabilista { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public int? IpiApuracao { get; set; }
        public string RetemCreditoIcmsst { get; set; }
        public string RetemCreditoIcms { get; set; }
        public string UtilizaSeller { get; set; }
        public string EmailHost { get; set; }
        public string EmailPorta { get; set; }
        public string EmailUsuario { get; set; }
        public string EmailSenha { get; set; }
        public string EmailSsl { get; set; }
        public int? EmailTipossl { get; set; }
        public int? EmailTipotls { get; set; }
        public string IncentivadorCultural { get; set; }
        public string QrcodePix { get; set; }
        public string ChavePix { get; set; }
        public string ObsPix { get; set; }
        public string MsgAniversarioClientes { get; set; }
        public double? MetroQuadrado { get; set; }
        public decimal? ValorMeta { get; set; }
        public int? NumFuncionariosAtivos { get; set; }
    }
}