// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EndCertificadoConfig
    {
        public int Id { get; set; }
        public int? CertificadoCd { get; set; }
        public string CertificadoDesc { get; set; }
    }
}