// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EntradaItemMedicamento
    {
        public int CdNota { get; set; }
        public int CdItem { get; set; }
        public string Nlote { get; set; }
        public decimal? Qlote { get; set; }
        public DateTime? Dfab { get; set; }
        public DateTime? Dval { get; set; }
        public decimal? Vpmc { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
    }
}