// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EntradaGradeQuantidade
    {
        public int CdNota { get; set; }
        public int CdGrade { get; set; }
        public int CdItem { get; set; }
        public int CdDeposito { get; set; }
        public int CdProduto { get; set; }
        public decimal? Quantidade { get; set; }
        public DateTime? DtCadastro { get; set; }
        public string Deletado { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
    }
}