// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EntradaConfig
    {
        public short NumTerminal { get; set; }
        public string TruncarValor { get; set; }
        public string ForcarVinculo { get; set; }
        public string ExibirMsgValor { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string ExibirValorOriginal { get; set; }
        public string ExibeMsgPmc { get; set; }
        public string NaoSomarImposto { get; set; }
        public int? CampoPesquisaProduto { get; set; }
        public string AtualizaIcms { get; set; }
        public string AtualizaIpi { get; set; }
        public string AtualizaPis { get; set; }
        public string AtualizaCofins { get; set; }
        public string VinculoApenasCodbarras { get; set; }
        public int? CampoPesqProdVincXml { get; set; }
        public string AlterarCorProduto { get; set; }
        public string AlterarCodFornecedor { get; set; }
        public string BloqPesqAutomaticaCodFornec { get; set; }
        public string CaminhoExportarXml { get; set; }
        public string VerificarGradeZerada { get; set; }
        public string HabilitaMargemGlobal { get; set; }
        public string PreencherFabricanteFornec { get; set; }
        public int? QtdeUltimosCustos { get; set; }
        public string UsaPrevisaoGastoPedidocompra { get; set; }
    }
}