// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EntradaFiscal
    {
        public int CdNota { get; set; }
        public string TipoNota { get; set; }
        public int? CdFornecedor { get; set; }
        public string Cnpj { get; set; }
        public string NmFornecedor { get; set; }
        public int? NumDocumento { get; set; }
        public string Cfop { get; set; }
        public DateTime? DtEmissao { get; set; }
        public DateTime? DtEntrada { get; set; }
        public string Obs { get; set; }
        public string NotaFechada { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public DateTime? DtExpWeb { get; set; }
        public string Deletado { get; set; }
        public string Modelo { get; set; }
        public string ChaveNfe { get; set; }
        public string DescontoPercentual { get; set; }
        public string NatOperacao { get; set; }
        public string Serie { get; set; }
        public string AcresDescEspecial { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
        public string CnpjDest { get; set; }
        public int? CdEmpresa { get; set; }
        public DateTime? DtSaida { get; set; }
        public string Status { get; set; }
        public decimal? IcmsBase { get; set; }
        public decimal? IcmsValor { get; set; }
        public decimal? IcmsBasesubst { get; set; }
        public decimal? IcmsValorsubst { get; set; }
        public decimal? VrTotalProd { get; set; }
        public decimal? ValorFrete { get; set; }
        public decimal? ValorSeguro { get; set; }
        public decimal? OutrasDespesas { get; set; }
        public decimal? ValorIpi { get; set; }
        public decimal? ValorTotalNota { get; set; }
        public decimal? DescontoTotal { get; set; }
        public decimal? Fretechegada { get; set; }
        public decimal? ValorIi { get; set; }
        public decimal? ValorPis { get; set; }
        public decimal? ValorCofins { get; set; }
        public decimal? CustoAdicional { get; set; }
        public decimal? FreteAdicional { get; set; }
        public string IndFrete { get; set; }
        public string IndPgto { get; set; }
        public DateTime? DtFechamento { get; set; }
        public string UsoInterno { get; set; }
        public decimal? ValorTotalNotaOriginal { get; set; }
        public string NfBonificacao { get; set; }
        public byte[] ArquivoXml { get; set; }
        public decimal? IcmsDesonerado { get; set; }
        public decimal? Margemlucro { get; set; }
        public string AtivoImobilizado { get; set; }
    }
}