// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EntradaItemImportacao
    {
        public int CdNota { get; set; }
        public int CdItem { get; set; }
        public int? Ndi { get; set; }
        public DateTime? Ddi { get; set; }
        public string Xlocdesemb { get; set; }
        public string Ufdesemb { get; set; }
        public DateTime? Ddesemb { get; set; }
        public int? Cexportador { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
    }
}