// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EntradaItemImportLacres
    {
        public int CdNota { get; set; }
        public int CdItem { get; set; }
        public int Ndi { get; set; }
        public int? Nadicao { get; set; }
        public int? Nseqadic { get; set; }
        public int? Cfabricante { get; set; }
        public decimal? Vdescdi { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
    }
}