// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EstoqueAlteracaomanual
    {
        public int Id { get; set; }
        public int? CdProduto { get; set; }
        public int? CdGrade { get; set; }
        public int? CdDeposito { get; set; }
        public DateTime? DataHora { get; set; }
    }
}