// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class EstoqueData
    {
        public int CdProduto { get; set; }
        public DateTime Data { get; set; }
        public decimal? Estoque { get; set; }
        public decimal? Precocusto { get; set; }
        public decimal? TotalItem { get; set; }
    }
}