// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Estoque
    {
        public int CdProduto { get; set; }
        public int CdGrade { get; set; }
        public int CdDeposito { get; set; }
        public decimal? Estoqueatual { get; set; }
        public decimal? Estoqueanterior { get; set; }
        public decimal? Pesoatual { get; set; }
        public decimal? Pesoanterior { get; set; }
        public DateTime? Ultimasaida { get; set; }
        public DateTime? Ultimaentrada { get; set; }
        public string Loginultimaentrada { get; set; }
        public string Loginultimasaida { get; set; }
        public DateTime? Ultimacorrecao { get; set; }
        public string Loginultimacorrecao { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtExpPalm { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public DateTime? DtCadastro { get; set; }
        public string Espelho { get; set; }
    }
}