// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Fornecedores
    {
        public int CdFornecedor { get; set; }
        public string NmFornecedor { get; set; }
        public string Nomefantasia { get; set; }
        public DateTime? DtFundacao { get; set; }
        public string EndNmMunicipio { get; set; }
        public string EndLogradouro { get; set; }
        public string EndBairro { get; set; }
        public string EndUf { get; set; }
        public string EndCep { get; set; }
        public string Telefone { get; set; }
        public string Fax { get; set; }
        public string CpfCnpj { get; set; }
        public string RgIe { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Contato { get; set; }
        public string ContTelefone { get; set; }
        public string ContEmail { get; set; }
        public string Obs { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string Exportar { get; set; }
        public DateTime? DtUltimacompra { get; set; }
        public string Inativo { get; set; }
        public string Refbanco { get; set; }
        public string Transporte { get; set; }
        public string TransporteTel { get; set; }
        public string CpUltimotipodoc { get; set; }
        public short? CpQtdparcelas { get; set; }
        public short? CpPeriodicidade { get; set; }
        public string CpPeriodmensal { get; set; }
        public int? CpContabancaria { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public string EndNumero { get; set; }
        public string EndComplemento { get; set; }
        public DateTime? DtExpWeb { get; set; }
        public int? EndCdMunicipio { get; set; }
        public string Pessoa { get; set; }
        public int? EndCdPais { get; set; }
        public string Suframa { get; set; }
        public string Deletado { get; set; }
        public string EndReferencia { get; set; }
        public string Lembrete { get; set; }
        public string InscMunicipal { get; set; }
        public string CnaeFiscal { get; set; }
        public short? Crt { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
        public string IeIsento { get; set; }
        public short? DiasTempoEntrega { get; set; }
    }
}