// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class FotosTransicao
    {
        public int CdFoto { get; set; }
        public int? NumTerminal { get; set; }
        public byte[] Foto { get; set; }
        public string Sincronizando { get; set; }
    }
}