// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Grades
    {
        public int CdProduto { get; set; }
        public int CdGrade { get; set; }
        public string NmGrade { get; set; }
        public string CodBarras { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public DateTime? DtExpWeb { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string IntegraMarketplace { get; set; }
        public int? TrayId { get; set; }
        public DateTime? DtSincMarketplace { get; set; }
    }
}