// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Grids
    {
        public int Id { get; set; }
        public string NmGrid { get; set; }
        public short NumTerminal { get; set; }
        public byte[] GridArquivoLayout { get; set; }
    }
}