// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class GruposProdutos
    {
        public int CdGrupo { get; set; }
        public int? CdPai { get; set; }
        public string Descricao { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public int? CdSetor { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public int? UsuarioId { get; set; }
        public string UsuarioNome { get; set; }
        public string PermiteVendaEstZerado { get; set; }
    }
}