// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfceCancelada
    {
        public int NumNfce { get; set; }
        public int SerieNfce { get; set; }
        public int NumTerminal { get; set; }
        public string Chave { get; set; }
        public string Protocolo { get; set; }
        public string Justificativa { get; set; }
        public string TpAmb { get; set; }
        public int? Cstat { get; set; }
        public string Motivo { get; set; }
        public string Cuf { get; set; }
        public DateTime? DhRecbto { get; set; }
        public byte[] ArqXmlProc { get; set; }
        public string Sincronizando { get; set; }
        public int CdEmpresa { get; set; }
    }
}