// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfceConfig
    {
        public int CdCertificado { get; set; }
        public string Danfe { get; set; }
        public string Formaemissao { get; set; }
        public string Autocontingencia { get; set; }
        public string EmiteGer { get; set; }
        public string EmitePdv { get; set; }
        public string WsUf { get; set; }
        public string WsAmbiente { get; set; }
        public string ProxyPorta { get; set; }
        public string ProxyHost { get; set; }
        public string ProxyUsuario { get; set; }
        public string ProxySenha { get; set; }
        public string EmailHost { get; set; }
        public string EmailPorta { get; set; }
        public string EmailUsuario { get; set; }
        public string EmailSenha { get; set; }
        public string EmailAssunto { get; set; }
        public string EmailMensagem { get; set; }
        public string EmailSsl { get; set; }
        public string EmailAutoenvia { get; set; }
        public string EmailAguardaenvio { get; set; }
        public string TipoImpPadrao { get; set; }
        public string ExibirImpostoItem { get; set; }
        public string SalvarPdf { get; set; }
        public string ImprimirPdf { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string ImprimeSemperguntar { get; set; }
        public byte[] Logomarca { get; set; }
        public string Sincronizando { get; set; }
        public string DesabilitarBotaoNfce { get; set; }
        public string ExibeQrcode { get; set; }
        public string ImprimirSaldoDivida { get; set; }
        public string ImprimirTipoPreco { get; set; }
        public short ExportarDia { get; set; }
        public string LembrarAuto { get; set; }
        public string ExportarEmailPadrao { get; set; }
        public string ExportarRelatorio { get; set; }
        public string ExportarPorEmail { get; set; }
        public string ExportarEmails { get; set; }
        public DateTime UltimaExportacaoData { get; set; }
        public string ExportarVerificarXml { get; set; }
        public string ImprimirObsPedido { get; set; }
    }
}