// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfcePedidoItem
    {
        public int NumNfce { get; set; }
        public int SerieNfce { get; set; }
        public int NumTerminal { get; set; }
        public int CdEmpresa { get; set; }
        public int Nitem { get; set; }
        public string Cprod { get; set; }
        public string Cean { get; set; }
        public string Xprod { get; set; }
        public string Ncm { get; set; }
        public string Extipi { get; set; }
        public string Cfop { get; set; }
        public string Ucom { get; set; }
        public decimal? Qcom { get; set; }
        public decimal? Vuncom { get; set; }
        public decimal? Vprod { get; set; }
        public string Ceantrib { get; set; }
        public string Utrib { get; set; }
        public decimal? Qtrib { get; set; }
        public decimal? Vuntrib { get; set; }
        public decimal? Vfrete { get; set; }
        public decimal? Vseg { get; set; }
        public decimal? Voutro { get; set; }
        public string Infadprod { get; set; }
        public decimal? Vtottrib { get; set; }
        public string Cst { get; set; }
        public string Csosn { get; set; }
        public string Orig { get; set; }
        public string Modbc { get; set; }
        public decimal? Vbc { get; set; }
        public decimal? Picms { get; set; }
        public decimal? Vicms { get; set; }
        public decimal? Icmstot { get; set; }
        public string Modbcst { get; set; }
        public decimal? Pmvast { get; set; }
        public decimal? Predbcst { get; set; }
        public decimal? Vbcst { get; set; }
        public decimal? Picmsst { get; set; }
        public decimal? Vicmsst { get; set; }
        public decimal? Predbc { get; set; }
        public decimal? Vdesc { get; set; }
        public string Ambiente { get; set; }
        public DateTime? DtEmissao { get; set; }
    }
}