// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfcePedido
    {
        public int NumNfce { get; set; }
        public int SerieNfce { get; set; }
        public int NumTerminal { get; set; }
        public int? NumDocumento { get; set; }
        public string ChaveNfce { get; set; }
        public int? NumItens { get; set; }
        public decimal? VlTotalNfce { get; set; }
        public string Mensagem { get; set; }
        public int? CdCliente { get; set; }
        public int? CdVendedor { get; set; }
        public int CdEmpresa { get; set; }
        public int? CdCertificado { get; set; }
        public byte[] ArqXmlNfce { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string TipoOperacao { get; set; }
        public string TipoEmissao { get; set; }
        public string ModeloDoc { get; set; }
        public string CodSituacao { get; set; }
        public DateTime? DtEmissao { get; set; }
        public string DtEmissaoSped { get; set; }
        public string TipoPgto { get; set; }
        public decimal? VlTotalDesc { get; set; }
        public decimal? VlAbatNt { get; set; }
        public decimal? VlTotalMercadorias { get; set; }
        public string TipoFrete { get; set; }
        public decimal? VlTotalFrete { get; set; }
        public decimal? VlTotalSeguro { get; set; }
        public decimal? VlTotalAcres { get; set; }
        public decimal? VlBcIcms { get; set; }
        public decimal? VlIcms { get; set; }
        public decimal? VlBcIcmsSt { get; set; }
        public decimal? VlIcmsSt { get; set; }
        public decimal? VlIpi { get; set; }
        public decimal? VlPis { get; set; }
        public decimal? VlCofins { get; set; }
        public decimal? VlPisSt { get; set; }
        public decimal? VlCofinsSt { get; set; }
        public DateTime? ContingenciaDatahora { get; set; }
        public string ContingenciaJust { get; set; }
        public string Ambiente { get; set; }
        public string ProtAutorizacao { get; set; }
        public DateTime? DtRecebimento { get; set; }
        public string VersaoApp { get; set; }
        public string Inutilizada { get; set; }
        public int? NumDocumentoAux { get; set; }
        public DateTime? ContingenciaEnviando { get; set; }
        public string TokenId { get; set; }
        public string TokenCsc { get; set; }
        public string Sincronizando { get; set; }
        public int? IdLocal { get; set; }
        public string Sincronizado { get; set; }
        public short? CdMensagem { get; set; }
        public string Status { get; set; }
        public short? NumTerminalEnviando { get; set; }
        public string InfCpl { get; set; }
        public string InfAdfisco { get; set; }
        public string EmitCpfcnpj { get; set; }
        public string DestCpfcnpj { get; set; }
        public string Extraordinaria { get; set; }
        public string Flag { get; set; }
    }
}