// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfceContingController
    {
        public int Id { get; set; }
        public string ContingenciaChave { get; set; }
        public short? Status { get; set; }
        public DateTime? Data { get; set; }
        public string ErroChave { get; set; }
        public int? ErroNumero { get; set; }
        public int? ErroSerie { get; set; }
        public string Origem { get; set; }
        public int? NumDocumento { get; set; }
        public byte[] ErroXml { get; set; }
        public DateTime? ProximaConsulta { get; set; }
    }
}