// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfceConfigLocal
    {
        public short NumTerminal { get; set; }
        public int CdCertificado { get; set; }
        public short? Serie { get; set; }
        public int? Numeracao { get; set; }
        public short? SerieAnterior { get; set; }
        public int? NumeracaoAnterior { get; set; }
        public string TokenId { get; set; }
        public string TokenCsc { get; set; }
        public string PreVisualizacao { get; set; }
        public string FormatoImpressao { get; set; }
        public string PathCaminhoPadrao { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string Sincronizando { get; set; }
        public short? Seriepdv { get; set; }
        public int? Numeracaopdv { get; set; }
        public short? SeriepdvAnterior { get; set; }
        public int? NumeracaopdvAnterior { get; set; }
        public int? UltNumHomolog { get; set; }
        public short? UltSerieHomolog { get; set; }
        public int? UltNumProd { get; set; }
        public short? UltSerieProd { get; set; }
        public int? UltNumpdvProd { get; set; }
        public short? UltSeriepdvProd { get; set; }
        public string ImpWin { get; set; }
        public string ImpBobina { get; set; }
        public string ImpPorta { get; set; }
        public short? ImpSaltolinha { get; set; }
        public short? ImpMargemesquerda { get; set; }
        public short? ImpFormatoitem { get; set; }
        public string ImpViaconsumidor { get; set; }
        public string ImpAtivarguilhotina { get; set; }
        public string EmiteGer { get; set; }
        public string EmitePdv { get; set; }
        public short? ImpPagCodigo { get; set; }
        public string EmitePedido { get; set; }
        public string ImpTipoimpwin { get; set; }
        public int? ImpLogoKc1 { get; set; }
        public int? ImpLogoKc2 { get; set; }
        public int? ImpLogoFatorx { get; set; }
        public int? ImpLogoFatory { get; set; }
        public string ImpLogoImprimir { get; set; }
        public string ImpIndiceCrediario { get; set; }
        public int? IdDfeSerieNumeracao { get; set; }
        public string QuebraLinhaDetalhamento { get; set; }
        public string ExportarCaminho { get; set; }
        public string ImpQrcodelateral { get; set; }
        public string EmissaoExtraordinaria { get; set; }
        public string EmissaoExtraordinariaIcms { get; set; }
        public string EmissaoExtraordinariaNcm { get; set; }
    }
}