// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfceInutilizadaXml
    {
        public int CdNfceInutilizada { get; set; }
        public byte[] ArqXml { get; set; }
        public DateTime? DtCadastro { get; set; }
        public short? CdUsuario { get; set; }
    }
}