// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfceCanceladaXml
    {
        public int NumNfce { get; set; }
        public int SerieNfce { get; set; }
        public int NumTerminal { get; set; }
        public int CdEmpresa { get; set; }
        public byte[] ArqXmlProc { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
    }
}