// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class NfceInutilizada
    {
        public int CdNfceInutilizada { get; set; }
        public string Protocolo { get; set; }
        public int? Modelo { get; set; }
        public int? Serie { get; set; }
        public string Cpfcnpj { get; set; }
        public int? Ano { get; set; }
        public int? NumIni { get; set; }
        public int? NumFin { get; set; }
        public string Justificativa { get; set; }
        public int? Cstat { get; set; }
        public string Motivo { get; set; }
        public string Cuf { get; set; }
        public DateTime? DhRecbto { get; set; }
        public string TpAmb { get; set; }
        public byte[] ArqXml { get; set; }
        public string Sincronizando { get; set; }
    }
}