// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class PedidoPagamento
    {
        public int Id { get; set; }
        public int NumDocumento { get; set; }
        public short? TipoPagamento { get; set; }
        public decimal? Valor { get; set; }
        public DateTime? Vencimento { get; set; }
        public int? CartaoCodcartao { get; set; }
        public short? CartaoNumparcelas { get; set; }
        public decimal? CartaoValorparcela { get; set; }
        public short? CartaoTipocartao { get; set; }
        public decimal? CartaoTaxa { get; set; }
        public decimal? CartaoValordesctaxa { get; set; }
        public decimal? CartaoParceladesctaxa { get; set; }
        public decimal? CartaoValoracrescimo { get; set; }
        public string CartaoDiasrepasse { get; set; }
        public string ChequeBanco { get; set; }
        public string ChequeAgencia { get; set; }
        public string ChequeConta { get; set; }
        public string ChequeNumero { get; set; }
        public string ChequeTitularCpf { get; set; }
        public string ChequeTitularNome { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string Deletado { get; set; }
        public string CartaoNomecartao { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public int? NumDocumentoAux { get; set; }
        public DateTime? DtCadastro { get; set; }
        public string Arquivolocal { get; set; }
        public string Obs { get; set; }
    }
}