// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class PedidoCompraPagamento
    {
        public int Id { get; set; }
        public int? FornecedorId { get; set; }
        public int? MarcaId { get; set; }
        public int? PedidoCompraId { get; set; }
        public double? ValorTotalMarca { get; set; }
        public int? Parcela { get; set; }
        public int? UsuarioId { get; set; }
        public DateTime? DataCadastro { get; set; }
        public DateTime? Vencimento { get; set; }
        public double? ValorTotalPedidoCompra { get; set; }
        public int? Periodicidade { get; set; }
        public string Status { get; set; }
        public DateTime? DtUltimaAlteracao { get; set; }
        public double? ValorEntrada { get; set; }
        public DateTime? BxData { get; set; }
        public string BxLogin { get; set; }
    }
}