using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Pedido
    {
        public int NumDocumento { get; set; }
        public int? CdCliente { get; set; }
        public string? LoginAbertura { get; set; }
        public int? CdVendedor { get; set; }
        public short? NumTerminalAbertura { get; set; }
        public DateTime DtFechamento { get; set; }
        public decimal? PagDinheiro { get; set; }
        public decimal? PagCredcli { get; set; }
        public decimal? PagTicket { get; set; }
        public decimal? PagCrediario { get; set; }
        public int? CdTipopreco { get; set; }
        public string? CliCpf { get; set; }
        public string? TipoDocumento { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string? Exportar { get; set; }
        public DateTime? DtEntrega { get; set; }
        public decimal? TotalLiquido { get; set; }
        public decimal? TotalBruto { get; set; }
        public string? CliNmCliente { get; set; }
        public decimal? Despesa { get; set; }
        public string? DespesaDescr { get; set; }
        public decimal? PagDinheirocomtroco { get; set; }
        public decimal? Troco { get; set; }
        public decimal? Valorcusto { get; set; }
        public string? Entregue { get; set; }
        public short? Ordem { get; set; }
        public decimal? Pesobruto { get; set; }
        public short? QtdeItens { get; set; }
        public string? Conferido { get; set; }
        public DateTime? DtAbertura { get; set; }
        public string? Alteraestoque { get; set; }
        public string? Ultimologin { get; set; }
        public short? UltimonumTerminal { get; set; }
        public int? Qtdeparccred { get; set; }
        public int? Qtdecheques { get; set; }
        public string? Obs { get; set; }
        public int? Sequencialdiario { get; set; }
        public decimal? PagChequepre { get; set; }
        public decimal? PagChequeato { get; set; }
        public short? Categoria { get; set; }
        public string? Palmserie { get; set; }
        public string? Palmnumdoc { get; set; }
        public string? Palmcodpedido { get; set; }
        public string? OrigemAbertura { get; set; }
        public string? Cancelado { get; set; }
        public string? Imprimiu { get; set; }
        public decimal? Frete { get; set; }
        public string? FreteDescr { get; set; }
        public DateTime? DtSincWeb { get; set; }
        public decimal? AcresDescValor { get; set; }
        public decimal? AcresDescPorc { get; set; }
        public string? AcresDescTipo { get; set; }
        public decimal? AcresDescUnitValor { get; set; }
        public decimal? AcresDescUnitPorc { get; set; }
        public decimal? Fretechegada { get; set; }
        public decimal? Fretesaidabruto { get; set; }
        public decimal? Fretesaidaliquido { get; set; }
        public int? CdEmpresa { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public decimal? Pesoliquido { get; set; }
        public int? CdCertificado { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public int? NumDocSeller { get; set; }
        public decimal? AcresDescPorcEspecial { get; set; }
        public int? CdFormapagamento { get; set; }
        public short? QtdeDescUnit { get; set; }
        public decimal? PagCartaoCredito { get; set; }
        public decimal? PagCartaoDebito { get; set; }
        public int? RefCoo { get; set; }
        public string? CliEndereco { get; set; }
        public string? TipoVenda { get; set; }
        public string? PedModelo { get; set; }
        public string? PedSerie { get; set; }
        public int? PedNumero { get; set; }
        public string? PedChave { get; set; }
        public string? CliBairro { get; set; }
        public string? CliEnderecoNum { get; set; }
        public string? CliCidade { get; set; }
        public string? CliUf { get; set; }
        public int? CliCdMunicipio { get; set; }
        public string? NumControle { get; set; }
        public int? CooDav { get; set; }
        public short? NumecfDav { get; set; }
        public string? OrcFinalizado { get; set; }
        public string? CliCep { get; set; }
        public decimal? PagCartaoParcelado { get; set; }
        public short? NumTerminalFechamento { get; set; }
        public string? LoginFechamento { get; set; }
        public string? OrigemFechamento { get; set; }
        public DateTime? RefCaixaDtAbertura { get; set; }
        public string? CliApelido { get; set; }
        public string? Alt { get; set; }
        public string? Sincronizado { get; set; }
        public string? Sincronizando { get; set; }
        public int? NumDocumentoAux { get; set; }
        public string? Comanda { get; set; }
        public int? CdMesas { get; set; }
        public int? MesaAnterior { get; set; }
        public string? TipoFood { get; set; }
        public string? SeqdiarioLocal { get; set; }
        public int? CanceladoCdUsuario { get; set; }
        public short? CanceladoNumTerminal { get; set; }
        public string? CanceladoMotivo { get; set; }
        public short? NumTerminalEdicao { get; set; }
        public DateTime? CanceladoDatahora { get; set; }
        public decimal? QtdePecas { get; set; }
        public string? NmVendedor { get; set; }
        public decimal? TotalComissao { get; set; }
        public decimal? TotalFrete { get; set; }
        public string? IdSellerWeb { get; set; }
        public string? SellerStatus { get; set; }
        public string? AcresDescLogin { get; set; }
        public string? CanceladoDevolveestoque { get; set; }
        public string? CanceladoDescontacaixa { get; set; }
        public string? CanceladoEliminacontas { get; set; }
        public int? QtdeAcresUnit { get; set; }
        public string? Arquivolocal { get; set; }
        public decimal? PagMoedasocial { get; set; }
        public string? Flag { get; set; }
        public decimal? PagOutros { get; set; }
        public string? Reforma { get; set; }
    }
}