// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class PedidoCategoria
    {
        public int CdPedidoCategoria { get; set; }
        public string NmPedidoCategoria { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public string Deletado { get; set; }
        public string Inativo { get; set; }
        public string Obs { get; set; }
        public int? TipoNota { get; set; }
        public string DescontosPermitidos { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public string Sincronizando { get; set; }
    }
}