// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class PedidoItem
    {
        public int Id { get; set; }
        public int NumDocumento { get; set; }
        public int? CdProduto { get; set; }
        public decimal? Quantidade { get; set; }
        public string Login { get; set; }
        public decimal? Preco { get; set; }
        public decimal? Precocusto { get; set; }
        public decimal? Pesosaida { get; set; }
        public decimal? Pesochegada { get; set; }
        public decimal? Subtotal { get; set; }
        public string FlagPeso { get; set; }
        public string Emlote { get; set; }
        public string Conferido { get; set; }
        public decimal? QtdePedida { get; set; }
        public decimal? PrecoPedido { get; set; }
        public decimal? QtdeDevolvida { get; set; }
        public decimal? Precotabela { get; set; }
        public string Obs { get; set; }
        public decimal? DimLargura { get; set; }
        public decimal? DimComprimento { get; set; }
        public decimal? DimEspessura { get; set; }
        public string NmProduto { get; set; }
        public int? CdGrade { get; set; }
        public int? CdTipopreco { get; set; }
        public decimal? AcresDescValor { get; set; }
        public decimal? AcresDescPorc { get; set; }
        public string AcresDescTipo { get; set; }
        public string EcfAliquota { get; set; }
        public decimal? Fretechegada { get; set; }
        public decimal? Fretesaida { get; set; }
        public decimal? Pesoliquido { get; set; }
        public decimal? Pesobruto { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public short? NumItem { get; set; }
        public string Cancelado { get; set; }
        public string Alteroudescricao { get; set; }
        public string Unidade { get; set; }
        public short? Casasdecimais { get; set; }
        public string Iat { get; set; }
        public string Ippt { get; set; }
        public decimal? St { get; set; }
        public DateTime? DataHoraItem { get; set; }
        public string Alt { get; set; }
        public int? CdSetor { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public int? NumDocumentoAux { get; set; }
        public int? IdAux { get; set; }
        public string FoodMotivoCancel { get; set; }
        public int? CanceladoCdUsuario { get; set; }
        public DateTime? CanceladoDatahora { get; set; }
        public short? CanceladoTerminal { get; set; }
        public short NumTerminal { get; set; }
        public string Origem { get; set; }
        public decimal? SubtotalReal { get; set; }
        public decimal? AcresDescValorReal { get; set; }
        public decimal? AcresDescPorcReal { get; set; }
        public int? CdVendedor { get; set; }
        public decimal? ComissaoPorc { get; set; }
        public decimal? ComissaoValor { get; set; }
        public string ComissaoTipo { get; set; }
        public decimal? FreteValor { get; set; }
        public string Imprimiu { get; set; }
        public int? CdPromocao { get; set; }
        public string UltimoPedido { get; set; }
        public string CanceladoMotivo { get; set; }
        public string PrecoEscolhido { get; set; }
        public string Alterouestoque { get; set; }
        public int? CdKit { get; set; }
        public int? IdPromocaokit { get; set; }
        public string Arquivolocal { get; set; }
        public decimal? AcresDescPorcManual { get; set; }
        public decimal? AcresDescValorManual { get; set; }
        public string AcresDescTipoManual { get; set; }
        public int? PromocaoScanntechId { get; set; }
        public short? PromocaoScanntechTipo { get; set; }
        public int? PromocaoScanntechQuantidade { get; set; }
        public decimal? AcresDescValorAutomatico { get; set; }
        public decimal? AcresDescPorcAutomatico { get; set; }
        public string CodBarras { get; set; }
    }
}