// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ProdutosTributacao
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int? Operacao { get; set; }
        public decimal? Icms { get; set; }
        public decimal? IcmsAliquotaCalcDesoneracao { get; set; }
        public int? MotivoDesoneracaoIcms { get; set; }
        public decimal? ReducaoBaseCalculo { get; set; }
        public decimal? Ipi { get; set; }
        public short? IpiCst { get; set; }
        public short? Origem { get; set; }
        public string CodBeneficioFiscal { get; set; }
        public string Substtributaria { get; set; }
        public string Cst { get; set; }
        public decimal? Pis { get; set; }
        public short? PisCst { get; set; }
        public decimal? Cofins { get; set; }
        public short? CofinsCst { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDataHora { get; set; }
        public string Ippt { get; set; }
        public string Fecp { get; set; }
        public int? Cfop { get; set; }
        public string AliquotaInterestadual { get; set; }
        public string Mva12 { get; set; }
        public string Mva4 { get; set; }
    }
}