// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ProdutosFoto
    {
        public int Id { get; set; }
        public int CdProduto { get; set; }
        public byte[] Foto { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string Deletado { get; set; }
        public short? Ordem { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public DateTime? DtSincSeller { get; set; }
    }
}