// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Prodfornec
    {
        public string CodProdFornec { get; set; }
        public int CdFornecedor { get; set; }
        public int CdProduto { get; set; }
        public DateTime? DtUltimacompra { get; set; }
        public int? CdUltimanota { get; set; }
        public int? CdGrade { get; set; }
        public string Sincronizando { get; set; }
    }
}