// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ProdutosMarcas
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public byte[] Foto { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string Deletado { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
    }
}