// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ProdutosMarketplace
    {
        public int Id { get; set; }
        public int ProdutoId { get; set; }
        public double? Peso { get; set; }
        public double? Comprimento { get; set; }
        public double? Largura { get; set; }
        public double? Altura { get; set; }
        public double? PrecoVendaTaxa { get; set; }
        public double? EstoqueTaxa { get; set; }
        public string Descricao { get; set; }
        public double? PrecoPromocionalTaxa { get; set; }
        public string Ean { get; set; }
        public DateTime? PromocaoInicio { get; set; }
        public DateTime? PromocaoFim { get; set; }
        public string Indisponivel { get; set; }
        public string Lancamento { get; set; }
        public string Digital { get; set; }
        public string Destaque { get; set; }
        public string PrecoSobConsulta { get; set; }
        public DateTime? DtLancamento { get; set; }
        public int? DisponibilidadeDias { get; set; }
        public string PalavrasChave { get; set; }
        public int? TrayId { get; set; }
        public string ItensInclusos { get; set; }
        public string MensagemAdicional { get; set; }
        public string Garantia { get; set; }
        public int? CategoriaId { get; set; }
        public string Modelo { get; set; }
    }
}