// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ProdutosReajustes
    {
        public int CdProduto { get; set; }
        public DateTime DataHora { get; set; }
        public decimal? PrecovendaAnterior { get; set; }
        public decimal? PrecovendaNovo { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public decimal? PrecocustoAnterior { get; set; }
        public decimal? PrecocustoNovo { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string Login { get; set; }
        public string LoginUltimaalteracao { get; set; }
        public int? Tabela { get; set; }
        public decimal? DescontofixoAnterior { get; set; }
        public decimal? DescontofixoNovo { get; set; }
    }
}