// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ProdutosRef
    {
        public int CdProduto { get; set; }
        public DateTime? DtUltimacompra { get; set; }
        public DateTime? DtUltimavenda { get; set; }
        public int? Ultimofornecedor { get; set; }
        public decimal? Mediavenda { get; set; }
        public string Loginultimavenda { get; set; }
        public string Loginultimacompra { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string TemGrade { get; set; }
    }
}