// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class ProdutosUrl
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public int? CdProduto { get; set; }
        public string Deletado { get; set; }
        public DateTime? DeletadoDatahota { get; set; }
    }
}