// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class TerminaisRef
    {
        public short NumTerminal { get; set; }
        public DateTime? Ultimoacesso { get; set; }
        public string Ultimooperador { get; set; }
        public DateTime? UltimaImportacao { get; set; }
        public DateTime? UltimaExportacao { get; set; }
        public DateTime? UltimaSincCompleta { get; set; }
        public DateTime? UltimaSincParcial { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string VersaoFirebird { get; set; }
        public string VersaoFocusAtual { get; set; }
        public string VersaoFocusAnterior { get; set; }
        public string VersaoPdvAtual { get; set; }
        public string VersaoPdvAnterior { get; set; }
        public string VersaoNfeAtual { get; set; }
        public string VersaoNfeAnterior { get; set; }
        public string VersaoOsAtual { get; set; }
        public string VersaoOsAnterior { get; set; }
        public string VersaoFoodAtual { get; set; }
        public string VersaoFoodAnterior { get; set; }
    }
}