// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class TerminaisLigados
    {
        public short NumTerminal { get; set; }
        public string Login { get; set; }
        public string Derrubar { get; set; }
        public DateTime? Quandoligou { get; set; }
        public DateTime? Ultimoping { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
    }
}