// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Tipopreco
    {
        public int CdTipopreco { get; set; }
        public string NmTipopreco { get; set; }
        public decimal? Valormargem { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string Inativo { get; set; }
        public string Referenciamargem { get; set; }
        public string OpMargem { get; set; }
        public decimal? Valorpreco { get; set; }
        public string OpPreco { get; set; }
        public string OpMargemxpreco { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public string Deletado { get; set; }
        public string Obs { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public string PermiteVendaSomentepj { get; set; }
        public string PermiteVendaComcliente { get; set; }
        public string PermiteDescAutPagamento { get; set; }
        public double? Valorminimo { get; set; }
        public int? QtdMinimaProdutos { get; set; }
        public decimal? Descontofixo { get; set; }
    }
}