// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class UsuariosRef
    {
        public int CdUsuario { get; set; }
        public DateTime? Ultimologin { get; set; }
        public DateTime? Ultimopedido { get; set; }
        public DateTime? Ultimoorcamento { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
    }
}