// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ControleFiscal.Infrastructure.Sql.Focus
{
    public partial class Usuarios
    {
        public int CdUsuario { get; set; }
        public string Login { get; set; }
        public string NmUsuario { get; set; }
        public DateTime? DtCadastro { get; set; }
        public DateTime? Ultimaalteracao { get; set; }
        public string Obs { get; set; }
        public string Inativo { get; set; }
        public string EndLogradouro { get; set; }
        public string EndBairro { get; set; }
        public string EndNmMunicipio { get; set; }
        public string EndUf { get; set; }
        public string EndCep { get; set; }
        public string Telefone { get; set; }
        public string Cargo { get; set; }
        public DateTime? DtNascimento { get; set; }
        public string Sexo { get; set; }
        public string Rg { get; set; }
        public string Cpf { get; set; }
        public string Pis { get; set; }
        public string CtpsN { get; set; }
        public string CtpsSerie { get; set; }
        public DateTime? DtAdmissao { get; set; }
        public DateTime? DtDemissao { get; set; }
        public string Motivodemissao { get; set; }
        public string Email { get; set; }
        public string Estcivil { get; set; }
        public string Conjuge { get; set; }
        public string NmPai { get; set; }
        public string NmMae { get; set; }
        public string Referencia { get; set; }
        public short? Dependentes { get; set; }
        public decimal? Salario { get; set; }
        public decimal? Comissao { get; set; }
        public DateTime? DtCasamento { get; set; }
        public string Fax { get; set; }
        public string Demitido { get; set; }
        public string Apelido { get; set; }
        public string EVendedor { get; set; }
        public short? Cargahoraria { get; set; }
        public byte[] Foto { get; set; }
        public string LoginPassword { get; set; }
        public string Deletado { get; set; }
        public string EndNumero { get; set; }
        public string EndComplemento { get; set; }
        public int? EndCdMunicipio { get; set; }
        public int? EndCdPais { get; set; }
        public string EndReferencia { get; set; }
        public string Multisessao { get; set; }
        public int? TempoSessaoInativa { get; set; }
        public decimal? DpSalarioatual { get; set; }
        public string Seller { get; set; }
        public int? CdUsuarioCategoria { get; set; }
        public string EUsuario { get; set; }
        public int? CdSetor { get; set; }
        public DateTime? DeletadoDatahora { get; set; }
        public string DeletadoLogin { get; set; }
        public DateTime? DtSincFocus { get; set; }
        public string Sincronizando { get; set; }
        public DateTime? DtSincSeller { get; set; }
        public DateTime? DtExpPalm { get; set; }
        public string Celular { get; set; }
        public string ETecnico { get; set; }
        public decimal? ComissaoServ { get; set; }
        public short? ComissaoFaixa { get; set; }
        public string EMotorista { get; set; }
        public string Menupersonalizado { get; set; }
        public DateTime? DtUltimaImpressaoItensPed { get; set; }
    }
}