/* ============================================================
   MIGRAÃ‡ÃƒO: PKs INTEGER â†’ UUID (CHAR(36)) + Colunas de Sync
   Banco: Firebird LOCAL (ContextLocalContext)
   Data: 2026-04-24
   Requer: Firebird 3.0+ (usa UUID_TO_CHAR, GEN_UUID)

   ANTES DE EXECUTAR:
   1. FaÃ§a backup do banco (gbak -b local backup.fbk)
   2. Verifique os nomes reais dos constraints com a query abaixo:
      SELECT RC.RDB$CONSTRAINT_NAME, RC.RDB$CONSTRAINT_TYPE, RC.RDB$RELATION_NAME
      FROM RDB$RELATION_CONSTRAINTS RC
      WHERE RC.RDB$CONSTRAINT_TYPE IN ('PRIMARY KEY','FOREIGN KEY')
      ORDER BY RC.RDB$RELATION_NAME;
   3. Ajuste os nomes de constraints nas seÃ§Ãµes 5 e 6 se necessÃ¡rio.
   4. Execute em uma transaÃ§Ã£o: CONNECT 'local'; SET AUTODDL OFF;
============================================================ */

SET TERM ^ ;

/* ============================================================
   SEÃ‡ÃƒO 1: ADICIONAR COLUNAS UUID TEMPORÃRIAS
   ============================================================ */

ALTER TABLE LOJA              ADD ID_NEW                    CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE USUARIOS          ADD ID_NEW                    CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE NCM               ADD ID_NEW                    CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE TIPO_VALOR_CAIXA  ADD ID_NEW                    CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE PERMISSOES        ADD ID_NEW                    CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE CAIXA             ADD ID_NEW                    CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE CAIXA             ADD LOJA_ID_NEW               CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE CAIXA_MOVIMENTACAO ADD ID_NEW                   CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE CAIXA_MOVIMENTACAO ADD CAIXA_ID_NEW             CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE CAIXA_MOVIMENTACAO ADD TIPO_VALOR_CAIXA_ID_NEW  CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE PERMISSOES_USUARIOS ADD ID_NEW                  CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE PERMISSOES_USUARIOS ADD USUARIO_ID_NEW          CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE PERMISSOES_USUARIOS ADD PERMISSAO_ID_NEW        CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE FORNECEDOR      ADD ID_NEW                    CHAR(36) CHARACTER SET ASCII ^
ALTER TABLE FORNECEDOR      ADD LOJA_ID_NEW               CHAR(36) CHARACTER SET ASCII ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 2: POPULAR UUID NAS TABELAS PAI (sem FK de outras tabelas)
   ============================================================ */

UPDATE LOJA             SET ID_NEW = UUID_TO_CHAR(GEN_UUID()) ^
UPDATE USUARIOS         SET ID_NEW = UUID_TO_CHAR(GEN_UUID()) ^
UPDATE NCM              SET ID_NEW = UUID_TO_CHAR(GEN_UUID()) ^
UPDATE TIPO_VALOR_CAIXA SET ID_NEW = UUID_TO_CHAR(GEN_UUID()) ^
UPDATE PERMISSOES       SET ID_NEW = UUID_TO_CHAR(GEN_UUID()) ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 3: POPULAR UUID NAS TABELAS FILHAS (propagando FKs)
   ============================================================ */

-- CAIXA: ID prÃ³prio + FK para LOJA
UPDATE CAIXA C
SET C.ID_NEW      = UUID_TO_CHAR(GEN_UUID()),
    C.LOJA_ID_NEW = (SELECT L.ID_NEW FROM LOJA L WHERE L.ID = C.LOJA_ID) ^

-- CAIXA_MOVIMENTACAO: ID prÃ³prio + FKs para CAIXA e TIPO_VALOR_CAIXA
UPDATE CAIXA_MOVIMENTACAO CM
SET CM.ID_NEW                  = UUID_TO_CHAR(GEN_UUID()),
    CM.CAIXA_ID_NEW            = (SELECT C.ID_NEW FROM CAIXA C WHERE C.ID = CM.CAIXA_ID),
    CM.TIPO_VALOR_CAIXA_ID_NEW = (SELECT T.ID_NEW FROM TIPO_VALOR_CAIXA T WHERE T.ID = CM.TIPO_VALOR_CAIXA_ID) ^

-- PERMISSOES_USUARIOS: ID prÃ³prio + FKs para USUARIOS e PERMISSOES
UPDATE PERMISSOES_USUARIOS PU
SET PU.ID_NEW           = UUID_TO_CHAR(GEN_UUID()),
    PU.USUARIO_ID_NEW   = (SELECT U.ID_NEW FROM USUARIOS U WHERE U.ID = PU.USUARIO_ID),
    PU.PERMISSAO_ID_NEW = (SELECT P.ID_NEW FROM PERMISSOES P WHERE P.ID = PU.PERMISSAO_ID) ^

-- FORNECEDOR: ID prÃ³prio + FK para LOJA
UPDATE FORNECEDOR F
SET F.ID_NEW      = UUID_TO_CHAR(GEN_UUID()),
    F.LOJA_ID_NEW = (SELECT L.ID_NEW FROM LOJA L WHERE L.ID = F.ID_LOJA) ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 4: MARCAR NOVAS COLUNAS COMO NOT NULL
   ============================================================ */

ALTER TABLE LOJA              ALTER ID_NEW                    SET NOT NULL ^
ALTER TABLE USUARIOS          ALTER ID_NEW                    SET NOT NULL ^
ALTER TABLE NCM               ALTER ID_NEW                    SET NOT NULL ^
ALTER TABLE TIPO_VALOR_CAIXA  ALTER ID_NEW                    SET NOT NULL ^
ALTER TABLE PERMISSOES        ALTER ID_NEW                    SET NOT NULL ^
ALTER TABLE CAIXA             ALTER ID_NEW                    SET NOT NULL ^
ALTER TABLE CAIXA             ALTER LOJA_ID_NEW               SET NOT NULL ^
ALTER TABLE CAIXA_MOVIMENTACAO ALTER ID_NEW                   SET NOT NULL ^
ALTER TABLE CAIXA_MOVIMENTACAO ALTER CAIXA_ID_NEW             SET NOT NULL ^
ALTER TABLE CAIXA_MOVIMENTACAO ALTER TIPO_VALOR_CAIXA_ID_NEW  SET NOT NULL ^
ALTER TABLE PERMISSOES_USUARIOS ALTER ID_NEW                  SET NOT NULL ^
ALTER TABLE PERMISSOES_USUARIOS ALTER USUARIO_ID_NEW          SET NOT NULL ^
ALTER TABLE PERMISSOES_USUARIOS ALTER PERMISSAO_ID_NEW        SET NOT NULL ^
ALTER TABLE FORNECEDOR      ALTER ID_NEW                    SET NOT NULL ^
ALTER TABLE FORNECEDOR      ALTER LOJA_ID_NEW               SET NOT NULL ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 5: REMOVER FOREIGN KEY CONSTRAINTS
   ATENÃ‡ÃƒO: Verifique os nomes reais com a query mencionada no cabeÃ§alho.
   Nomes abaixo seguem a convenÃ§Ã£o EF Core Firebird.
   ============================================================ */

-- FK CAIXA â†’ LOJA (EF pode gerar nome como FK_CAIXA_LOJA_ID ou similar)
ALTER TABLE CAIXA DROP CONSTRAINT FK_CAIXA_LOJA ^

-- FK CAIXA_MOVIMENTACAO â†’ CAIXA e TIPO_VALOR_CAIXA
ALTER TABLE CAIXA_MOVIMENTACAO DROP CONSTRAINT FK_CAIXAMOV_CAIXA ^
ALTER TABLE CAIXA_MOVIMENTACAO DROP CONSTRAINT FK_CAIXAMOV_TIPOVALOR ^

-- FK FORNECEDOR â†’ LOJA
ALTER TABLE FORNECEDOR DROP CONSTRAINT FK_FORNECEDOR_LOJA ^

-- FK PERMISSOES_USUARIOS â†’ USUARIOS e PERMISSOES
ALTER TABLE PERMISSOES_USUARIOS DROP CONSTRAINT FK_PERMUSUARIO_USUARIO ^
ALTER TABLE PERMISSOES_USUARIOS DROP CONSTRAINT FK_PERMUSUARIO_PERMISSAO ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 6: REMOVER PRIMARY KEY CONSTRAINTS
   ============================================================ */

ALTER TABLE LOJA              DROP CONSTRAINT PK_LOJA ^
ALTER TABLE USUARIOS          DROP CONSTRAINT PK_USUARIOS ^
ALTER TABLE NCM               DROP CONSTRAINT PK_NCM ^
ALTER TABLE TIPO_VALOR_CAIXA  DROP CONSTRAINT PK_TIPO_VALOR_CAIXA ^
ALTER TABLE PERMISSOES        DROP CONSTRAINT PK_PERMISSOES ^
ALTER TABLE CAIXA             DROP CONSTRAINT PK_CAIXA ^
ALTER TABLE CAIXA_MOVIMENTACAO DROP CONSTRAINT PK_CAIXA_MOVIMENTACAO ^
ALTER TABLE PERMISSOES_USUARIOS DROP CONSTRAINT PK_PERMISSOES_USUARIOS ^
ALTER TABLE FORNECEDOR      DROP CONSTRAINT PK_FORNECEDOR ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 7: REMOVER COLUNAS INTEGER ANTIGAS
   ============================================================ */

ALTER TABLE LOJA              DROP ID ^
ALTER TABLE USUARIOS          DROP ID ^
ALTER TABLE NCM               DROP ID ^
ALTER TABLE TIPO_VALOR_CAIXA  DROP ID ^
ALTER TABLE PERMISSOES        DROP ID ^
ALTER TABLE CAIXA             DROP ID ^
ALTER TABLE CAIXA             DROP LOJA_ID ^
ALTER TABLE CAIXA_MOVIMENTACAO DROP ID ^
ALTER TABLE CAIXA_MOVIMENTACAO DROP CAIXA_ID ^
ALTER TABLE CAIXA_MOVIMENTACAO DROP TIPO_VALOR_CAIXA_ID ^
ALTER TABLE PERMISSOES_USUARIOS DROP ID ^
ALTER TABLE PERMISSOES_USUARIOS DROP USUARIO_ID ^
ALTER TABLE PERMISSOES_USUARIOS DROP PERMISSAO_ID ^
ALTER TABLE FORNECEDOR      DROP CD_FORNECEDOR ^
ALTER TABLE FORNECEDOR      DROP ID_LOJA ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 8: RENOMEAR COLUNAS UUID PARA NOMES DEFINITIVOS
   (Requer Firebird 2.5.3+)
   ============================================================ */

ALTER TABLE LOJA              ALTER ID_NEW               TO ID ^
ALTER TABLE USUARIOS          ALTER ID_NEW               TO ID ^
ALTER TABLE NCM               ALTER ID_NEW               TO ID ^
ALTER TABLE TIPO_VALOR_CAIXA  ALTER ID_NEW               TO ID ^
ALTER TABLE PERMISSOES        ALTER ID_NEW               TO ID ^
ALTER TABLE CAIXA             ALTER ID_NEW               TO ID ^
ALTER TABLE CAIXA             ALTER LOJA_ID_NEW          TO LOJA_ID ^
ALTER TABLE CAIXA_MOVIMENTACAO ALTER ID_NEW              TO ID ^
ALTER TABLE CAIXA_MOVIMENTACAO ALTER CAIXA_ID_NEW        TO CAIXA_ID ^
ALTER TABLE CAIXA_MOVIMENTACAO ALTER TIPO_VALOR_CAIXA_ID_NEW TO TIPO_VALOR_CAIXA_ID ^
ALTER TABLE PERMISSOES_USUARIOS ALTER ID_NEW             TO ID ^
ALTER TABLE PERMISSOES_TOURISTS ALTER USUARIO_ID_NEW     TO USUARIO_ID ^
ALTER TABLE PERMISSOES_USUARIOS ALTER PERMISSAO_ID_NEW   TO PERMISSAO_ID ^
ALTER TABLE FORNECEDOR      ALTER ID_NEW               TO ID ^
ALTER TABLE FORNECEDOR      ALTER LOJA_ID_NEW          TO LOJA_ID ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 9: RECRIAR PRIMARY KEYS
   ============================================================ */

ALTER TABLE LOJA              ADD CONSTRAINT PK_LOJA              PRIMARY KEY (ID) ^
ALTER TABLE USUARIOS          ADD CONSTRAINT PK_USUARIOS          PRIMARY KEY (ID) ^
ALTER TABLE NCM               ADD CONSTRAINT PK_NCM               PRIMARY KEY (ID) ^
ALTER TABLE TIPO_VALOR_CAIXA  ADD CONSTRAINT PK_TIPO_VALOR_CAIXA  PRIMARY KEY (ID) ^
ALTER TABLE PERMISSOES        ADD CONSTRAINT PK_PERMISSOES        PRIMARY KEY (ID) ^
ALTER TABLE CAIXA             ADD CONSTRAINT PK_CAIXA             PRIMARY KEY (ID) ^
ALTER TABLE CAIXA_MOVIMENTACAO ADD CONSTRAINT PK_CAIXA_MOVIMENTACAO PRIMARY KEY (ID) ^
ALTER TABLE PERMISSOES_USUARIOS ADD CONSTRAINT PK_PERMISSOES_USUARIOS PRIMARY KEY (ID) ^
ALTER TABLE FORNECEDOR      ADD CONSTRAINT PK_FORNECEDOR      PRIMARY KEY (ID) ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 10: RECRIAR FOREIGN KEYS
   ============================================================ */

ALTER TABLE CAIXA
    ADD CONSTRAINT FK_CAIXA_LOJA
    FOREIGN KEY (LOJA_ID) REFERENCES LOJA(ID) ^

ALTER TABLE CAIXA_MOVIMENTACAO
    ADD CONSTRAINT FK_CAIXAMOV_CAIXA
    FOREIGN KEY (CAIXA_ID) REFERENCES CAIXA(ID) ^

ALTER TABLE CAIXA_MOVIMENTACAO
    ADD CONSTRAINT FK_CAIXAMOV_TIPOVALOR
    FOREIGN KEY (TIPO_VALOR_CAIXA_ID) REFERENCES TIPO_VALOR_CAIXA(ID) ^

ALTER TABLE FORNECEDOR
    ADD CONSTRAINT FK_FORNECEDOR_LOJA
    FOREIGN KEY (LOJA_ID) REFERENCES LOJA(ID) ^

ALTER TABLE PERMISSOES_USUARIOS
    ADD CONSTRAINT FK_PERMUSUARIO_USUARIO
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ^

ALTER TABLE PERMISSOES_USUARIOS
    ADD CONSTRAINT FK_PERMUSUARIO_PERMISSAO
    FOREIGN KEY (PERMISSAO_ID) REFERENCES PERMISSOES(ID) ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 11: ADICIONAR COLUNAS DE CONTROLE DE SINCRONIZAÃ‡ÃƒO
   ============================================================ */

-- LOJA
ALTER TABLE LOJA ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE LOJA ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE LOJA ADD IS_DELETED  SMALLINT  DEFAULT 0 NOT NULL ^
ALTER TABLE LOJA ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- USUARIOS
ALTER TABLE USUARIOS ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE USUARIOS ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE USUARIOS ADD IS_DELETED  SMALLINT  DEFAULT 0 NOT NULL ^
ALTER TABLE USUARIOS ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- NCM
ALTER TABLE NCM ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE NCM ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE NCM ADD IS_DELETED  SMALLINT  DEFAULT 0 NOT NULL ^
ALTER TABLE NCM ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- TIPO_VALOR_CAIXA
ALTER TABLE TIPO_VALOR_CAIXA ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE TIPO_VALOR_CAIXA ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE TIPO_VALOR_CAIXA ADD IS_DELETED  SMALLINT  DEFAULT 0 NOT NULL ^
ALTER TABLE TIPO_VALOR_CAIXA ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- PERMISSOES
ALTER TABLE PERMISSOES ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE PERMISSOES ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE PERMISSOES ADD IS_DELETED  SMALLINT  DEFAULT 0 NOT NULL ^
ALTER TABLE PERMISSOES ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- CAIXA (jÃ¡ tem ATIVO, adicionamos sÃ³ sync)
ALTER TABLE CAIXA ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE CAIXA ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE CAIXA ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- CAIXA_MOVIMENTACAO (jÃ¡ tem ATIVO)
ALTER TABLE CAIXA_MOVIMENTACAO ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE CAIXA_MOVIMENTACAO ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE CAIXA_MOVIMENTACAO ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- PERMISSOES_USUARIOS
ALTER TABLE PERMISSOES_USUARIOS ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE PERMISSOES_USUARIOS ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE PERMISSOES_USUARIOS ADD IS_DELETED  SMALLINT  DEFAULT 0 NOT NULL ^
ALTER TABLE PERMISSOES_USUARIOS ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

-- FORNECEDOR
ALTER TABLE FORNECEDOR ADD CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ^
ALTER TABLE FORNECEDOR ADD UPDATED_AT  TIMESTAMP ^
ALTER TABLE FORNECEDOR ADD IS_DELETED  SMALLINT  DEFAULT 0 NOT NULL ^
ALTER TABLE FORNECEDOR ADD SYNC_STATUS VARCHAR(10) DEFAULT 'PENDING' NOT NULL ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 12: POPULAR CREATED_AT NOS REGISTROS EXISTENTES
   ============================================================ */

UPDATE LOJA             SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE USUARIOS         SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE NCM              SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE TIPO_VALOR_CAIXA SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE PERMISSOES       SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE CAIXA            SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE CAIXA_MOVIMENTACAO SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE PERMISSOES_USUARIOS SET CREATED_AT = CURRENT_TIMESTAMP ^
UPDATE FORNECEDOR     SET CREATED_AT = CURRENT_TIMESTAMP ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 13: CRIAR TABELAS DE SINCRONIZAÃ‡ÃƒO
   ============================================================ */

CREATE TABLE SYNC_LOG (
    ID          CHAR(36) CHARACTER SET ASCII  NOT NULL,
    TABELA      VARCHAR(50)                   NOT NULL,
    REGISTRO_ID CHAR(36) CHARACTER SET ASCII  NOT NULL,
    OPERACAO    VARCHAR(10)                   NOT NULL,  /* INSERT | UPDATE | DELETE */
    STATUS      VARCHAR(10) DEFAULT 'PENDING' NOT NULL,  /* PENDING | SYNCED | ERRO */
    PAYLOAD     BLOB SUB_TYPE TEXT,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SYNCED_AT   TIMESTAMP,
    CONSTRAINT PK_SYNC_LOG PRIMARY KEY (ID)
) ^

CREATE TABLE SYNC_CONFIG (
    ID                CHAR(36) CHARACTER SET ASCII  NOT NULL,
    ULTIMO_SYNC       TIMESTAMP,
    EM_SINCRONIZACAO  SMALLINT  DEFAULT 0 NOT NULL,
    URL_NUVEM         VARCHAR(500),
    CONSTRAINT PK_SYNC_CONFIG PRIMARY KEY (ID)
) ^

/* Registro inicial de configuraÃ§Ã£o */
INSERT INTO SYNC_CONFIG (ID, EM_SINCRONIZACAO)
VALUES (UUID_TO_CHAR(GEN_UUID()), 0) ^

COMMIT ^

/* ============================================================
   SEÃ‡ÃƒO 14: TRIGGERS â€” UUID automÃ¡tico no INSERT + UPDATED_AT no UPDATE
   ============================================================ */

/* ---- LOJA ---- */
CREATE OR ALTER TRIGGER TRG_LOJA_BI FOR LOJA
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_LOJA_BU FOR LOJA
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- USUARIOS ---- */
CREATE OR ALTER TRIGGER TRG_USUARIOS_BI FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_USUARIOS_BU FOR USUARIOS
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- NCM ---- */
CREATE OR ALTER TRIGGER TRG_NCM_BI FOR NCM
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_NCM_BU FOR NCM
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- TIPO_VALOR_CAIXA ---- */
CREATE OR ALTER TRIGGER TRG_TIPOVALOR_BI FOR TIPO_VALOR_CAIXA
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_TIPOVALOR_BU FOR TIPO_VALOR_CAIXA
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- PERMISSOES ---- */
CREATE OR ALTER TRIGGER TRG_PERMISSOES_BI FOR PERMISSOES
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_PERMISSOES_BU FOR PERMISSOES
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- CAIXA ---- */
CREATE OR ALTER TRIGGER TRG_CAIXA_BI FOR CAIXA
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_CAIXA_BU FOR CAIXA
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- CAIXA_MOVIMENTACAO ---- */
CREATE OR ALTER TRIGGER TRG_CAIXAMOV_BI FOR CAIXA_MOVIMENTACAO
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_CAIXAMOV_BU FOR CAIXA_MOVIMENTACAO
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- PERMISSOES_USUARIOS ---- */
CREATE OR ALTER TRIGGER TRG_PERMUSR_BI FOR PERMISSOES_USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_PERMUSR_BU FOR PERMISSOES_USUARIOS
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- FORNECEDOR ---- */
CREATE OR ALTER TRIGGER TRG_FORNECEDOR_BI FOR FORNECEDOR
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

CREATE OR ALTER TRIGGER TRG_FORNECEDOR_BU FOR FORNECEDOR
ACTIVE BEFORE UPDATE POSITION 0
AS BEGIN
    NEW.UPDATED_AT  = CURRENT_TIMESTAMP;
    NEW.SYNC_STATUS = 'PENDING';
END ^

/* ---- SYNC_LOG ---- */
CREATE OR ALTER TRIGGER TRG_SYNCLOG_BI FOR SYNC_LOG
ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = '') THEN
        NEW.ID = UUID_TO_CHAR(GEN_UUID());
    IF (NEW.CREATED_AT IS NULL) THEN
        NEW.CREATED_AT = CURRENT_TIMESTAMP;
END ^

COMMIT ^

SET TERM ; ^

/* ============================================================
   FIM DA MIGRAÃ‡ÃƒO
   ============================================================
   ApÃ³s execuÃ§Ã£o bem-sucedida:
   - Reinicie a aplicaÃ§Ã£o DSN-API
   - Execute um sync completo via POST /api/Sincronizacao/sincronizar
   ============================================================ */

